#ifndef _PCI_MSI_H
#define _PCI_MSI_H

#include "Pci.h"

#define PCI_MSI_MESSAGE_CONTROL_OFFSET          0x02
#define PCI_MSI_MESSAGE_ADDRESS_LOW_OFFSET      0x04
#define PCI_MSI_MESSAGE_ADDRESS_HIGH_OFFSET     0x08
#define PCI_MSI_MESSAGE_LONG_MODE_SHIFT         0x04
#define PCI_MSI_MESSAGE_DATA_OFFSET             0x08
#define PCI_MSI_MASK_OFFSET                     0x10
#define PCI_MSI_PENDING_OFFSET                  0x14

#define PCI_MSI_MSG_CTRL_ENABLE_MASK            (0x01)
#define PCI_MSI_MSG_CTRL_ENABLE_SHIFT           (0)
#define PCI_MSI_MSG_CTRL_ENABLE                 (PCI_MSI_MSG_CTRL_ENABLE_MASK << PCI_MSI_MSG_CTRL_ENABLE_SHIFT)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_CAP_MASK     (0x07)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_CAP_SHIFT    (1)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_CAP          (PCI_MSI_MSG_CTRL_MULTI_MSG_CAP_MASK << PCI_MSI_MSG_CTRL_MULTI_MSG_CAP_SHIFT)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_ENABLE_MASK  (0x07)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_ENABLE_SHFIT (4)
#define PCI_MSI_MSG_CTRL_MULTI_MSG_ENABLE       (PCI_MSI_MSG_CTRL_MULTI_MSG_ENABLE_MASK << PCI_MSI_MSG_CTRL_MULTI_MSG_ENABLE_SHFIT)
#define PCI_MSI_MSG_CTRL_64BIT_MASK             (0x01)
#define PCI_MSI_MSG_CTRL_64BIT_SHIFT            (7)
#define PCI_MSI_MSG_CTRL_64BIT                  (PCI_MSI_MSG_CTRL_64BIT_MASK << PCI_MSI_MSG_CTRL_64BIT_SHIFT)
#define PCI_MSI_MSG_CTRL_PER_VECT_MASKING_MASK  (0x01)
#define PCI_MSI_MSG_CTRL_PER_VECT_MASKING_SHFIT (8)
#define PCI_MSI_MSG_CTRL_PER_VECT_MASKING       (PCI_MSI_MSG_CTRL_PER_VECT_MASKING_MASK << PCI_MSI_MSG_CTRL_PER_VECT_MASKING_SHFIT)

#define PCI_MSI_MSG_ADDR_DESTINATION_MODE_MASK  (0x01)
#define PCI_MSI_MSG_ADDR_DESTINATION_MODE_SHIFT (2)
#define PCI_MSI_MSG_ADDR_DESTINATION_MODE       (PCI_MSI_MSG_ADDR_DESTINATION_MODE_MASK << PCI_MSI_MSG_ADDR_DESTINATION_MODE_SHIFT)
#define PCI_MSI_MSG_ADDR_REDIRECTION_HINT_MASK  (0x01)
#define PCI_MSI_MSG_ADDR_REDIRECTION_HINT_SHIFT (3)
#define PCI_MSI_MSG_ADDR_REDIRECTION_HINT       (PCI_MSI_MSG_ADDR_REDIRECTION_HINT_MASK << PCI_MSI_MSG_ADDR_REDIRECTION_HINT_SHIFT)
#define PCI_MSI_MSG_ADDR_DESTINATION_ID_MASK    (0xFF)
#define PCI_MSI_MSG_ADDR_DESTINATION_ID_SHIFT   (12)
#define PCI_MSI_MSG_ADDR_DESTINATION_ID         (PCI_MSI_MSG_ADDR_DESTINATION_ID_MASK << PCI_MSI_MSG_ADDR_DESTINATION_ID_SHIFT)

#define PCI_MSI_MSG_DATA_VECTOR_MASK            (0xFF)
#define PCI_MSI_MSG_DATA_VECTOR_SHIFT           (0)
#define PCI_MSI_MSG_DATA_VECTOR                 (PCI_MSI_MSG_DATA_VECTOR_MASK << PCI_MSI_MSG_DATA_VECTOR_SHIFT)
#define PCI_MSI_MSG_DATA_DELIVERY_MODE_MASK     (0x07)
#define PCI_MSI_MSG_DATA_DELIVERY_MODE_SHIFT    (8)
#define PCI_MSI_MSG_DATA_DELIVERY_MODE          (PCI_MSI_MSG_DATA_DELIVERY_MODE_MASK << PCI_MSI_MSG_DATA_DELIVERY_MODE_SHIFT)
#define PCI_MSI_MSG_DATA_LEVEL_MASK             (0x01)
#define PCI_MSI_MSG_DATA_LEVEL_SHIFT            (14)
#define PCI_MSI_MSG_DATA_LEVEL                  (PCI_MSI_MSG_DATA_LEVEL_MASK << PCI_MSI_MSG_DATA_LEVEL_SHIFT)
#define PCI_MSI_MSG_DATA_TRIGGER_MODE_MASK      (0x01)
#define PCI_MSI_MSG_DATA_TRIGGER_MODE_SHIFT     (15)
#define PCI_MSI_MSG_DATA_TRIGGER_MODE           (PCI_MSI_MSG_DATA_TRIGGER_MODE_MASK << PCI_MSI_MSG_DATA_TRIGGER_MODE_SHIFT)

#endif