#ifndef _DRSD_MODESET_LOCK_H
#define _DRSD_MODESET_LOCK_H

#include "DrsdCore.h"

DRIVER_EXPORT
LOUSTATUS 
DrsdModesetLock(
    PDRSD_MODESET_LOCK Lock, 
    PDRSD_MODESET_ACQURE_CONTEXT Ctx
);

DRIVER_EXPORT
LOUSTATUS 
DrsdModesetUnlock(
    PDRSD_MODESET_LOCK Lock
);

#endif