#include <LouAPI.h>

UNUSED static PROCESSOR_PPIN_INFORMATION Ppin[] = {
    [X86_64_VENDOR_INTEL] = {
        .Feature = X86_64_FEATURE_INTEL_PPIN,
        .MsrPPINControl =  MSR_GENERIC_PPIN_CONTROL,
        .MsrPPIN = MSR_GENERIC_PPIN,
    },
    [X86_64_VENDOR_AMD] = {
        .Feature = X86_64_FEATURE_AMD_PPIN,
        .MsrPPINControl =  MSR_AMD_PPIN_CONTROL,
        .MsrPPIN = MSR_AMD_PPIN,
    },
    {0},
};

UNUSED static PPIN_CPU_ID PpinIDs[] = {
    {X86_64_DEFINE_FEATURE(X86_64_FEATURE_AMD_PPIN, &Ppin[X86_64_VENDOR_AMD])},
    {X86_64_DEFINE_FEATURE(X86_64_FEATURE_INTEL_PPIN, &Ppin[X86_64_VENDOR_INTEL])},
    //following legacy models dont have the cpuid enumeration
    {X86_64_DEFINE_VFM(INTEL_IVYBRIDGE_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_HASWELL_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_BROADWELL_D, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_BROADWELL_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_SKYLAKE_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_ICELAKE_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_ICELAKE_D, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_SAPPHIRERAPIDS_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_EMERALDRAPIDS_X, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_XEON_PHI_KNL, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {X86_64_DEFINE_VFM(INTEL_XEON_PHI_KNM, &Ppin[X86_64_FEATURE_INTEL_PPIN])},
    {0},
};

//static void InitializePpinInformation(){

//}