#ifndef _FIBRE_CHANNEL_MS_H
#define _FIBRE_CHANNEL_MS_H

#pragma pack(push, 1)

#define FIBRE_CHANNEL_FDMI_SUB_TYPE             0x10

#define FDMI_VERSION1                           1
#define FDMI_VERSION2                           2

#define FIBRE_CHANNEL_FDMI_REQUEST_GRHL         0x0100
#define FIBRE_CHANNEL_FDMI_REQUEST_GHAT         0x0101
#define FIBRE_CHANNEL_FDMI_REQUEST_GRPL         0x0102
#define FIBRE_CHANNEL_FDMI_REQUEST_GPAT         0x0110
#define FIBRE_CHANNEL_FDMI_REQUEST_RHBA         0x0200
#define FIBRE_CHANNEL_FDMI_REQUEST_RHAT         0x0201
#define FIBRE_CHANNEL_FDMI_REQUEST_RPRT         0x0210
#define FIBRE_CHANNEL_FDMI_REQUEST_RPA          0x0211
#define FIBRE_CHANNEL_FDMI_REQUEST_DHBA         0x0300
#define FIBRE_CHANNEL_FDMI_REQUEST_DHAT         0x0301
#define FIBRE_CHANNEL_FDMI_REQUEST_DPRT         0x0310
#define FIBRE_CHANNEL_FDMI_REQUEST_DPA          0x0311

#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NODE_NAME                      0x01
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MANUFACTURER                   0x02
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_SERIAL_NUMBER                  0x03
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MODEL                          0x04
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MODEL_DESCRIPTION              0x05
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_HARDWARE_VERSION               0x06
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_DRIVER_VERSION                 0x07
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_OPTION_ROM_VERSION             0x08
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_FIRMWARE_VERSION               0x09
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_OS_NAME_VERSION                0x0A
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MAX_CT_PAYLOAD                 0x0B
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NODE_SYMBOL_NAME               0x0C
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_VENDOR_SPECIRFIC_INFO          0x0D
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NUMBER_OF_PORTS                0x0E
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_FABRIC_NAME                    0x0F
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_BIOS_VERSION                   0x10
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_BIOS_STATE                     0x11
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_VENDOR_IDENTIFIER              0xE0

#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NODE_NAME_LENGTH                   8
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MANUFACTURER_LENGTH                64  
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_SERIAL_NUMBER_LENGTH               64
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MODEL_LENGTH                       64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MODEL_DESCRIPTION_LENGTH           64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_HARDWARE_VERSION_LENGTH            64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_DRIVER_VERSION_LENGTH              64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_OPTION_ROM_VERSION_LENGTH          64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_FIRMWARE_VERSION_LENGTH            64 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_OS_NAME_VERSION_LENGTH             128 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_MAX_CT_PAYLOAD_LENGTH              4
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NODE_SYMBOL_NAME_LENGTH            64  
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_VENDOR_SPECIRFIC_INFO_LENGTH       4 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_NUMBER_OF_PORTS_LENGTH             4 
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_FABRIC_NAME_LENGTH                 8  
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_BIOS_VERSION_LENGTH                64  
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_BIOS_STATE_LENGTH                  4
#define FIBRE_CHANNEL_FDMI_HBA_ATTRIBUTE_VENDOR_IDENTIFIER_LENGTH           8

#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_FC4_TYPES                          0x0001
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SUPPORTED_SPEED                    0x0002
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_CURRENT_PORT_SPEED                 0x0003
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_MAX_FRAME_SIZE                     0x0004
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_OS_DEVICE_NAME                     0x0005
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_HOST_NAME                          0x0006
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_NODE_NAME                          0x0007
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_NAME                          0x0008
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SYMBOLIC_NAME                      0x0009
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_TYPE                          0x000A
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SUPPORTED_CLASS_RVC                0x000B
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_FABRIC_NAME                        0x000C
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_CURRENT_FC4_TYPE                   0x000D
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_STATE                         0x0101
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_DISCOVERED_PORTS                   0x0102
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_ID                            0x0103

#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_FC4_TYPES_LENGTH                   32
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SUPPORTED_SPEED_LENGTH             4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_CURRENT_PORT_SPEED_LENGTH          4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_MAX_FRAME_SIZE_LENGTH              4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_OS_DEVICE_NAME_LENGTH              256
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_HOST_NAME_LENGTH                   256
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_NODE_NAME_LENGTH                   8
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_NAME_LENGTH                   8
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SYMBOLIC_NAME_LENGTH               256
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_TYPE_LENGTH                   4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_SUPPORTED_CLASS_RVC_LENGTH         4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_FABRIC_NAME_LENGTH                 8
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_CURRENT_FC4_TYPE_LENGTH            32
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_STATE_LENGTH                  4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_DISCOVERED_PORTS_LeNGTH            4
#define FIBRE_CHANNEL_FDMI_PORT_ATTRIBUTE_PORT_ID_LENGTH                     4

//big endian struct 
typedef struct _FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER{
    uint64_t Identification;
}FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER, * PFIBRE_CHANNEL_FDMI_HBA_IDENTIFIER;

//big Endian Struct 
typedef struct _FIBRE_CHANNEL_FDMI_PORT_NAME{
    uint64_t PortName;
}FIBRE_CHANNEL_FDMI_PORT_NAME, * PFIBRE_CHANNEL_FDMI_PORT_NAME;

#define FIBRE_CHANNEL_FDMI_ATTRIBUTE_HEADER_LENGTH  4

//big endian struct
typedef struct _FIBRE_CHANNEL_FDMI_ATTRIBUTE_ENTRY{
    uint16_t    Type;
    uint16_t    Length;
    uint8_t     Value[];
}FIBRE_CHANNEL_FDMI_ATTRIBUTE_ENTRY, * PFIBRE_CHANNEL_FDMI_ATTRIBUTE_ENTRY;

//big endian struct 
typedef struct _FIBRE_CHANNEL_FDMI_ATTRIBUTE{
    uint32_t                                AttributeCount;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE_ENTRY      AttributeEntry[];
}FIBRE_CHANNEL_FDMI_ATTRIBUTE, * PFIBRE_CHANNEL_FDMI_ATTRIBUTE;

//big Endian Struct 
typedef struct _FIBRE_CHANNEL_FDMI_RPL{
    uint32_t                            PortCount;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE_ENTRY  Port[1];
}FIBRE_CHANNEL_FDMI_RPL, * PFIBRE_CHANNEL_FDMI_RPL;

typedef struct _FIBRE_CHANNEL_FDMI_RHBA{
    FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER       HbaIdentifier;
    FIBRE_CHANNEL_FDMI_RPL                  Port;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE            HbaAttributes;
}FIBRE_CHANNEL_FDMI_RHBA, * PFIBRE_CHANNEL_FDMI_RHBA;

typedef struct _FIBRE_CHANNEL_FDMI_RHAT{
    FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER       HbaIdnetifier;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE            HbaAttributes;
}FIBRE_CHANNEL_FDMI_RHAT, * PFIBRE_CHANNEL_FDMI_RHAT;

typedef struct _FIBRE_CHANNEL_FDMI_RPRT{
    FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER       HbaIdentifier;
    FIBRE_CHANNEL_FDMI_PORT_NAME            Port;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE            HbaAttributes;
}FIBRE_CHANNEL_FDMI_RPRT, * PFIBRE_CHANNEL_FDMI_RPRT;

typedef struct _FIBRE_CHANNEL_FDMI_RPA{
    FIBRE_CHANNEL_FDMI_PORT_NAME        Port;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE        HbaAttributes;
}FIBRE_CHANNEL_FDMI_RPA, * PFIBRE_CHANNEL_FDMI_RPA;

typedef struct _FIBRE_CHANNEL_FDMI_DPA{
    FIBRE_CHANNEL_FDMI_PORT_NAME        Port;
    FIBRE_CHANNEL_FDMI_ATTRIBUTE        HbaAttributes;
}FIBRE_CHANNEL_FDMI_DPA, * PFIBRE_CHANNEL_FDMI_DPA;

typedef struct _FIBRE_CHANNEL_FDMI_DHAT{
    FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER   HbaIdentifier;
}FIBRE_CHANNEL_FDMI_DHAT, * PFIBRE_CHANNEL_FDMI_DHAT;

typedef struct _FIBRE_CHANNEL_FDMI_DHBA{
    FIBRE_CHANNEL_FDMI_HBA_IDENTIFIER   HbaIdentifier;
}FIBRE_CHANNEL_FDMI_DHBA, * PFIBRE_CHANNEL_FDMI_DHBA;

#pragma pack(pop)
#endif //_FIBRE_CHANNEL_MS_H