#ifndef _FIBRE_CHANNEL_FS_H
#define _FIBRE_CHANNEL_FS_H

#ifdef __cplusplus
#include <LouDDK.h>
extern "C" {
#else
#include <LouAPI.h>
#endif

//Big Endian Structure
typedef struct _FIBRE_CHANNEL_FRAME_HEADER{
    uint8_t     RoutingControl;
    uint8_t     DestinationID;
    uint8_t     ClassServiceControl;
    uint8_t     SourceID;
    uint8_t     Type;
    uint8_t     FrameControl[3];
    uint8_t     SequnceID;
    uint8_t     DataFieldControl;
    uint16_t    SequnceCount;
    uint16_t    OxID;
    uint16_t    RxID;
    uint32_t    ParameterOrRelativeOffset;
}FIBRE_CHANNEL_FRAME_HEADER, * PFIBRE_CHANNEL_FRAME_HEADER;

#define FIBRE_CHANNEL_FRAME_HEADER_LENGTH 24

#define FIBRE_CHANNEL_MAXIMUM_PAYLOAD           2112
#define FIBRE_CHANNEL_MINIMUM_MAXIMUM_PAYLOAD   256

#define FIBRE_CHANNEL_FRAME (FIBRE_CHANNEL_MAXIMUM_MAXIMUM_PAYLOAD + FIBRE_CHANNEL_FRAME_HEADER_LENGTH)

#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNCAT             30
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_SOL_DATA          0x01
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_CTL         0x02
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_SOL_CTL           0x03
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_DATA        0x04
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_DATA_DESC         0x05
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_CMD         0x06
#define FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_CMD_STATUS        0x07

#define FIBRE_CHANNEL_ROUTING_CONTROL_ILS_REUEST                    FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_CTL
#define FIBRE_CHANNEL_ROUTING_CONTROL_ILS_REPLY                     FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_SOL_CTL

#define FIBRE_CHANNEL_ROUTING_CONTROL_ELS_REQUEST       0x22
#define FIBRE_CHANNEL_ROUTING_CONTROL_ELS_REPLY         0x23
#define FIBRE_CHANNEL_ROUTING_CONTROL_ELS4_REQUEST      0x32
#define FIBRE_CHANNEL_ROUTING_CONTROL_ELS4_REPLY        0x33

#define FIBRE_CHANNEL_ROUTING_CONTROL_VFTH  0x50
#define FIBRE_CHANNEL_ROUTING_CONTROL_IFRH  0x51
#define FIBRE_CHANNEL_ROUTING_CONTROL_ENCH  0x52

#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_NOP            0x80
#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_ABTS           0x81
#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_RMC            0x82
#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_ACC            0x84
#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_RJT            0x85
#define FIBRE_CHANNEL_ROUTING_CONTROL_BA_PRMT           0x86

#define FIBRE_CHANNEL_ROUTING_CONTROL_ACKNOWLEDGE1      0xC0
#define FIBRE_CHANNEL_ROUTING_CONTROL_ACKNOWLEDGE0      0xC1
#define FIBRE_CHANNEL_ROUTING_CONTROL_PORT_REJECT       0xC2
#define FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_REJECT     0xC3
#define FIBRE_CHANNEL_ROUTING_CONTROL_PORT_BUSY         0xC4
#define FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_BUSY       0xC5
#define FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_BUSYL      0xC6
#define FIBRE_CHANNEL_ROUTING_CONTROL_LINK_CREDIT_RESET 0xC7
#define FIBRE_CHANNEL_ROUTING_CONTROL_END               0xC9

#define FIBRE_CHANNEL_ROUTING_NAMES_INIT {                                                  \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNCAT]           =   "Uncat"                 \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_SOL_DATA]        =   "Sol Data"              \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_CTL]       =   "Unsol Ctl"             \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_SOL_CTL]         =   "Sol Ctl"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_DATA]      =   "Unsol Data"            \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_DATA_DESC]       =   "Data Desc"             \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_UNSOL_CMD]       =   "Unsol Command"         \
    [FIBRE_CHANNEL_ROUTING_CONTROL_DEVICE_DATA_CMD_STATUS]      =   "Command Status"        \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ELS_REQUEST]                 =   "ELS Request"           \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ELS_REPLY]                   =   "ELS Reply"             \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ELS4_REQUEST]                =   "ELS4 Request"          \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ELS4_REPLY]                  =   "ELS4 Reply"            \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_NOP]                      =   "BLS No Op"             \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_ABTS]                     =   "BLS Abort"             \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_RMC]                      =   "BLS RMC"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_ACC]                      =   "BLS ACC"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_RJT]                      =   "BLS RJT"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_BA_PRMT]                     =   "BLS PRMT"              \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ACKNOWLEDGE1]                =   "LC ACK1"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_ACKNOWLEDGE0]                =   "LC ACK0"               \
    [FIBRE_CHANNEL_ROUTING_CONTROL_PORT_REJECT]                 =   "LC Port Reject"        \
    [FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_REJECT]               =   "LC Fabric Reject"      \
    [FIBRE_CHANNEL_ROUTING_CONTROL_PORT_BUSY]                   =   "LC Port Busy"          \
    [FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_BUSY]                 =   "LC Fabric Busy Data"   \
    [FIBRE_CHANNEL_ROUTING_CONTROL_FABRIC_BUSYL]                =   "LC Fabric Busy Control"\
    [FIBRE_CHANNEL_ROUTING_CONTROL_LINK_CREDIT_RESET]           =   "LC Credit Reset"       \
    [FIBRE_CHANNEL_ROUTING_CONTROL_END]                         =   "LC End"                \
}

#define FIBRE_CHANNEL_FID_ADDRESS_NONE                  0x000000
#define FIBRE_CHANNEL_FID_ADDRESS_BROADCAST             0xFFFFFF
#define FIBRE_CHANNEL_FID_ADDRESS_FABRIC_LOGIC          0xFFFFFE
#define FIBRE_CHANNEL_FID_ADDRESS_FABRIC_CONTROL        0xFFFFFD
#define FIBRE_CHANNEL_FID_ADDRESS_DIRECTORY_SERVER      0xFFFFFC
#define FIBRE_CHANNEL_FID_ADDRESS_TIME_SERVER           0xFFFFFB
#define FIBRE_CHANNEL_FID_ADDRESS_MANAGEMENT_SERVER     0xFFFFFA
#define FIBRE_CHANNEL_FID_ADDRESS_QoS                   0xFFFFF9
#define FIBRE_CHANNEL_FID_ADDRESS_ALIASES               0xFFFFF8
#define FIBRE_CHANNEL_FID_ADDRESS_SECURITY_KEY          0xFFFFF7
#define FIBRE_CHANNEL_FID_ADDRESS_CLOCK                 0xFFFFF6
#define FIBRE_CHANNEL_FID_ADDRESS_MULTICAST_SERVER      0xFFFFF5

#define FIBRE_CHANNEL_FID_WELL_KNOWN_MAX                0xFFFFFF
#define FIBRE_CHANNEL_FID_WELL_KNOWN_BASE               0xFFFFF5

#define FIBRE_CHANNEL_FID_DOMAIN_MANAGER                0xFFFC00

#define FIBRE_CHANNEL_FID_DOMAIN                        0
#define FIBRE_CHANNEL_FID_PORT                          1
#define FIBRE_CHANNEL_FID_LINK                          2

#define FIBRE_CHANNEL_TYPE_BASIC_LINK_SERVICE           0x00
#define FIBRE_CHANNEL_TYPE_EXTENDED_LINK_SERVICE        0x01
#define FIBRE_CHANNEL_TYPE_IP_OVER_FC                   0x05
#define FIBRE_CHANNEL_TYPE_SCSI_FCP                     0x08
#define FIBRE_CHANNEL_TYPE_CT_SERVICE                   0x20
#define FIBRE_CHANNEL_TYPE_INTERNAL_LINK_SERVICE        0x22
#define FIBRE_CHANNEL_TYPE_FC_NVME                      0x28

#define FIBRE_CHANNEL_NAMES_INIT {                              \
    [FIBRE_CHANNEL_TYPE_BASIC_LINK_SERVICE]         =   "BLS"   \
    [FIBRE_CHANNEL_TYPE_EXTENDED_LINK_SERVICE]      =   "ELS"   \
    [FIBRE_CHANNEL_TYPE_IP_OVER_FC]                 =   "IP"    \
    [FIBRE_CHANNEL_TYPE_SCSI_FCP]                   =   "FCP"   \
    [FIBRE_CHANNEL_TYPE_CT_SERVICE]                 =   "CT"    \
    [FIBRE_CHANNEL_TYPE_INTERNAL_LINK_SERVICE]      =   "ILS"   \
    [FIBRE_CHANNEL_TYPE_FC_NVME]                    =   "NVME"  \
}

#define FIBRE_CHANNEL_FRAME_CONTROL_EXCHANGE_CONTEXT        1 << 23
#define FIBRE_CHANNEL_FRAME_CONTROL_SEQUENCE_CONTEXT        1 << 22
#define FIBRE_CHANNEL_FRAME_CONTROL_FIRST_SEQUENCE          1 << 21
#define FIBRE_CHANNEL_FRAME_CONTROL_LAST_SEQUENCE           1 << 20
#define FIBRE_CHANNLE_FRAME_CONTROL_END_SEQUENCE            1 << 19
#define FIBRE_CHANNEL_FRAME_CONTROL_END_CONNECTION          1 << 18
#define FIBRE_CHANNEL_FRAME_CONTROL_RESERVED_BIT17          1 << 17
#define FIBRE_CHANNEL_FRAME_CONTROL_SEQUENCE_INITIATIVE     1 << 16
#define FIBRE_CHANNEL_FRAME_CONTROL_X_ID_ADDRESS_CHANGED    1 << 15
#define FIBRE_CHANNEL_FRAME_CONTROL_X_ID_INVALID            1 << 14

#define FIBRE_CHANNEL_FRAME_CONTROL_ACKNOWLEDGE1            1 << 12
#define FIBRE_CHANNEL_FRAME_CONTROL_ACKNOWLEDGEN            2 << 12
#define FIBRE_CHANNEL_FRAME_CONTROL_ACKNOWLEDGE0            3 << 12

#define FIBRE_CHANNEL_FRAME_CONTROL_RESERVED_BIT11          1 << 11
#define FIBRE_CHANNEL_FRAME_CONTROL_RESERVED_BIT10          1 << 10
#define FIBRE_CHANNEL_FRAME_CONTROL_RETRANSMMIT_SEQUENCE    1 << 9
#define FIBRE_CHANNEL_FRAME_CONTROL_UNI_TX                  1 << 8
#define FIBRE_CHANNEL_FRAME_CONTROL_CONT_SEQUENCE(x)        ((x) << 6)
#define FIBRE_CHANNEL_FRAME_CONTROL_ABORT_SEQUENCE(x)       ((x) << 4)
#define FIBRE_CHANNEL_FRAME_CONTROL_RELATIVE_OFFSET         1 << 3
#define FIBRE_CHANNEL_FRAME_CONTROL_RESERVED_BIT2           1 << 2
#define FIBRE_CHANNEL_FRAME_CONTROL_FILL(x)                 ((x) & 0x03)

#define FIBRE_CHANNEL_BA_SEQUENCE_ID_VALUE  0x80

//big Endian Structure
typedef struct _FIBRE_CHANNEL_BA_ACC{
    uint8_t     SeqIdVal;
    uint8_t     Reserved[2];
    uint16_t    OxID;
    uint16_t    RxID;
    uint16_t    LowSequenceCount;
    uint16_t    HighSequenceCount;
}FIBRE_CHANNEL_BA_ACC, * PFIBRE_CHANNEL_BA_ACC;

typedef struct _FIBRE_CHANNEL_BA_REJECT{
    uint8_t     Reserved1;
    uint8_t     Reason;
    uint8_t     Explain;
    uint8_t     Vendor;
}FIBRE_CHANNEL_BA_REJECT, * PFIBRE_CHANNEL_BA_REJECT;

#define FIBRE_CHANNEL_BA_REJECT_NONE                0x00
#define FIBRE_CHANNEL_BA_REJECT_INVALID_COMMAND     0x01
#define FIBRE_CHANNEL_BA_REJECT_LOGICAL_ERROR       0x03
#define FIBRE_CHANNEL_BA_REJECT_LOGICAL_BUSY        0x05
#define FIBRE_CHANNEL_BA_REJECT_PROTOCOL_ERROR      0x07
#define FIBRE_CHANNEL_BA_REJECT_UNABLE              0x09
#define FIBRE_CHANNEL_BA_REJECT_VNEDOR              0xFF

#define FIBRE_CHANNEL_BA_REJECT_EXP_NONE            0x00
#define FIBRE_CHANNEL_BA_REJECT_INVALID_X_ID        0x03
#define FIBRE_CHANNEL_BA_REJECT_ABORT               0x05

typedef struct _FIBRE_CHANNEL_PORT_FABRIC_REJECT{
    uint8_t     Action;
    uint8_t     Reason;
    uint8_t     Reserved;
    uint8_t     Vendor;
}FIBRE_CHANNEL_PORT_FABRIC_REJECT, * PFIBRE_CHANNEL_PORT_FABRIC_REJECT;

#define FIBRE_CHANNEL_REJECT_REASON_NONE                        0x00
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_DID                 0x01
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_SID                 0x02
#define FIBRE_CHANNEL_REJECT_REASON_PORT_UNAVAILABLE_TMP        0x03
#define FIBRE_CHANNEL_REJECT_REASON_PORT_UNAVAILABLE            0x04
#define FIBRE_CHANNEL_REJECT_REASON_CLASS_NOT_SUPPORTED         0x05
#define FIBRE_CHANNEL_REJECT_REASON_DELIMITER_USAGE_ERROR       0x06
#define FIBRE_CHANNEL_REJECT_REASON_TYPE_NOT_SUPPORTED          0x07
#define FIBRE_CHANNEL_REJECT_REASON_LINK_CONTROL                0x08
#define FIBRE_CHANNEL_REJECT_REASON_R_CONTROL_FIELD             0x09
#define FIBRE_CHANNEL_REJECT_REASON_F_CONTROL_FIELD             0x0A
#define FIBRE_CHANNEL_REJECT_REASON_OX_ID                       0x0B
#define FIBRE_CHANNEL_REJECT_REASON_RX_ID                       0x0C
#define FIBRE_CHANNEL_REJECT_REASON_SEQUENCE_ID                 0x0D
#define FIBRE_CHANNEL_REJECT_REASON_DF_CONTROL                  0x0E
#define FIBRE_CHANNEL_REJECT_REASON_SEQUNCE_COUNT               0x0F
#define FIBRE_CHANNEL_REJECT_REASON_PARAMETER                   0x10
#define FIBRE_CHANNEL_REJECT_REASON_EXCHANGE_ERROR              0x11
#define FIBRE_CHANNEL_REJECT_REASON_PROTOCOL_ERROR              0x12
#define FIBRE_CHANNEL_REJECT_REASON_INCORRECT_LENGTH            0x13
#define FIBRE_CHANNEL_REJECT_REASON_UNEXPECTED_ACKNOWLEDGE      0x14
#define FIBRE_CHANNEL_REJECT_REASON_UNSUPPORTED_FABRIC_CLASS    0x15
#define FIBRE_CHANNEL_REJECT_REASON_LOGIN_REQUIRED              0x16
#define FIBRE_CHANNEL_REJECT_REASON_EXCESIVE_SEQUENCE_ATTEMPTED 0x17
#define FIBRE_CHANNEL_REJECT_REASON_UNABLE_TO_ESTABLISH_EXHANGE 0x18
#define FIBRE_CHANNEL_REJECT_REASON_FABRIC_UNAVAILABLE          0x1A
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_VC_ID               0x1B
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_CS_CONTROL          0x1C
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_INSUF_RESOURCE      0x1D
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_CLASS               0x1F
#define FIBRE_CHANNEL_REJECT_REASON_PREEMT_REJECT               0x20
#define FIBRE_CHANNEL_REJECT_REASON_PREEMT_DISABLED             0x21
#define FIBRE_CHANNEL_REJECT_REASON_MULTI_CAST_ERROR            0x22
#define FIBRE_CHANNEL_REJECT_REASON_MULTI_CAST_ERROR_TERMINATE  0x23
#define FIBRE_CHANNEL_REJECT_REASON_PROCESS_LOGIN_REQUEST       0x24
#define FIBRE_CHANNEL_REJECT_REASON_INVALID_ATTACHMENT          0x25
#define FIBRE_CHANNEL_REJECT_REASON_VENDOR_SPECIFIC_REJECT      0xFF

#define FIBRE_CHANNEL_DEFAULT_E_D_TIMEOUT_VALUE 2000
#define FIBRE_CHANNEL_DEFAULT_R_A_TIMEOUT_VALUE 10000

#ifdef __cplusplus
}
#endif
#endif //_FIBRE_CHANNEL_FS_H