#ifndef _HDMI_PICTURE_H
#define _HDMI_PICTURE_H

typedef enum _HDMI_PICTURE_ASPECT{
    HDMI_PICTURE_ASPECT_NONE = 0,
    HDMI_PICTURE_ASPECT_4_3, 
    HDMI_PICTURE_ASPECT_16_9,
    HDMI_PICTURE_ASPECT_64_27,
    HDMI_PICTURE_ASPECT_256_135,
    HDMI_PICTURE_ASPECT_RESERVED,
}HDMI_PICTURE_ASPECT, * PHDMI_PICTURE_ASPECT;

#endif