#ifndef _HDMI_PICTURE_H
#define _HDMI_PICTURE_H

typedef enum _HDMI_PICTURE_ASPECT{
    HDMI_PICTURE_ASPECT_NONE = 0,
    HDMI_PICTURE_ASPECT_4_3, 
    HDMI_PICTURE_ASPECT_16_9,
    HDMI_PICTURE_ASPECT_64_27,
    HDMI_PICTURE_ASPECT_256_135,
    HDMI_PICTURE_ASPECT_RESERVED,
}HDMI_PICTURE_ASPECT, * PHDMI_PICTURE_ASPECT;

typedef enum _HDMI_COLOR_SPACE{
    HDMI_COLORSPACE_RGB = 0,
    HDMI_COLORSPACE_YUV422,
    HDMI_COLORSPACE_YUV444,
    HDMI_COLORSPACE_YUv420,
    HDMI_COLORSPACE_RESERVED4,
    HDMI_COLORSPACE_RESERVED5,
    HDMI_COLORSPACE_RESERVED6,
    HDMI_COLORSPACE_IDO_DEFINED,
}HDMI_COLOR_SPACE, * PHDMI_COLOR_SPACE;

typedef enum _HDMI_SCAN_MODE{
    HDMI_SCAN_MODE_NONE = 0,
    HDMI_SCAN_MODE_OVERSCAN,
    HDMI_SCAN_MODE_UNDERSCAN,
    HDMI_SCAN_MODE_RESERVED,
}HDMI_SCAN_MODE, * PHDMI_SCAN_MODE;

typedef enum _HDMI_COLORIMETRY{
    HDMI_COLORIMETRY_NONE = 0,
    HDMI_COLORIMETRY_4_3,
    HDMI_COLORIMETRY_16_9,
    HDMI_COLORIMETRY_64_27,
    HDMI_COLORIMETRY_256_135,
    HDMI_COLORIMETRY_RESERVED,
}HDMI_COLORIMETRY, * PHDMI_COLORIMETRY;

typedef enum _HDMI_ACTIVE_ASPECT{
    HDMI_ACTIVE_ASPECT_16_9_TOP = 2,
    HDMI_ACTIVE_ASPECT_14_9_TOP = 3,
    HDMI_ACTIVE_ASPECT_16_9_CENCTER = 4,
    HDMI_ACTIVE_ASPECT_PICTURE = 8,
    HDMI_ACTIVE_ASPECT_4_3 = 9,
    HDMI_ACTIVE_ASPECT_16_9 = 10,
    HDMI_ACTIVE_ASPECT_14_9 = 11,
    HDMI_ACTIVE_ASPECT_4_3_SP_14_9 = 13,
    HDMI_ACTIVE_ASPECT_14_9_SP_14_9 = 14,
    HDMI_ACTIVE_ASPECT_14_9_SP_4_3 = 15,
}HDMI_ACTIVE_ASPECT, * PHDMI_ACTIVE_ASPECT;

typedef enum _HDMI_EXTENDED_COLORTIMETRY{
    HDMI_EXTENDED_COLORTIMETRY_XV_YCC_601 = 0,
    HDMI_EXTENDED_COLORTIMETRY_XV_YCC_709,
    HDMI_EXTENDED_COLORTIMETRY_S_YCC_601,
    HDMI_EXTENDED_COLORTIMETRY_OPYCC601,
    HDMI_EXTENDED_COLORTIMETRY_OPRGB,
    HDMI_EXTENDED_COLORTIMETRY_BT2020_CONST_LUM,
    HDMI_EXTENDED_COLORTIMETRY_BT2020,
    HDMI_EXTENDED_COLORTIMETRY_RESERVED,
}HDMI_EXTENDED_COLORTIMETRY, * PHDMI_EXTENDED_COLORTIMETRY;

typedef enum _HDMI_QUANTIZATION_RANGE{
    HDMI_QUANTIZATION_RANGE_DEFAULT = 0,
    HDMI_QUANTIZATION_RANGE_LIMITED,
    HDMI_QUANTIZATION_RANGE_FULL,
    HDMI_QUANTIZATION_RANGE_RESERVED,
}HDMI_QUANTIZATION_RANGE, * PHDMI_QUANTIZATION_RANGE;

typedef enum _HDMI_NUPS{
    HDMI_NUPS_UNKOWN = 0,
    HDMI_NUPS_HORIZONTAL,
    HDMI_NUPS_VERTICAL,
    HDMI_NUPS_BOTH,
}HDMI_NUPS, * PHDMI_NUPS;

typedef enum _HDMI_YCC_QUANTIZATION_RANGE{
    HDMI_QUANTIZATION_YCC_RANGE_LIMITED = 0,
    HDMI_QUANTIZATION_YCC_RANGE_FULL,
}HDMI_YCC_QUANTIZATION_RANGE, * PHDMI_YCC_QUANTIZATION_RANGE;


#endif