#ifndef _HDMI_SOUND_H
#define _HDMI_SOUND_H

#ifdef __cplusplus
extern "C" {
#endif

#include <Sound.h>
#include <drivers/Pcm.h>

typedef enum _HDMI_INFO_FRAME_TYPE{
    HDMI_INFO_FRAME_TYPE_VENDOR = 0x81,
    HDMI_INFO_FRAME_TYPE_AVI,
    HDMI_INFO_FRAME_TYPE_SPD,
    HDMI_INFO_FRAME_TYPE_AUDIO,
    HDMI_INFO_FRAME_TYPE_DRSD = 87,
}HDMI_INFO_FRAME_TYPE, * PHDMI_INFO_FRAME_TYPE;

typedef enum _HDMI_AUDIO_CODING_TYPE{
    HDMI_AUDIO_CODING_TYPE_STREAM = 0,
	HDMI_AUDIO_CODING_TYPE_PCM,
	HDMI_AUDIO_CODING_TYPE_AC3,
	HDMI_AUDIO_CODING_TYPE_MPEG1,
	HDMI_AUDIO_CODING_TYPE_MP3,
	HDMI_AUDIO_CODING_TYPE_MPEG2,
	HDMI_AUDIO_CODING_TYPE_AAC_LC,
	HDMI_AUDIO_CODING_TYPE_DTS,
	HDMI_AUDIO_CODING_TYPE_ATRAC,
	HDMI_AUDIO_CODING_TYPE_DSD,
	HDMI_AUDIO_CODING_TYPE_EAC3,
	HDMI_AUDIO_CODING_TYPE_DTS_HD,
	HDMI_AUDIO_CODING_TYPE_MLP,
	HDMI_AUDIO_CODING_TYPE_DST,
	HDMI_AUDIO_CODING_TYPE_WMA_PRO,
	HDMI_AUDIO_CODING_TYPE_CXT,
}HDMI_AUDIO_CODING_TYPE, * PHDMI_AUDIO_CODING_TYPE;

typedef enum _HDMI_AUDIO_SAMPLE_SIZE{
    HDMI_AUDIO_SAMPLE_SIZE_STREAM = 0,
	HDMI_AUDIO_SAMPLE_SIZE_16,
	HDMI_AUDIO_SAMPLE_SIZE_20,
	HDMI_AUDIO_SAMPLE_SIZE_24,
}HDMI_AUDIO_SAMPLE_SIZE, * PHDMI_AUDIO_SAMPLE_SIZE;

typedef enum _HDMI_AUDIO_SAMPLE_FREQUENCY{
	HDMI_AUDIO_SAMPLE_FREQUENCY_STREAM = 0,
	HDMI_AUDIO_SAMPLE_FREQUENCY_32000,
	HDMI_AUDIO_SAMPLE_FREQUENCY_44100,
	HDMI_AUDIO_SAMPLE_FREQUENCY_48000,
	HDMI_AUDIO_SAMPLE_FREQUENCY_88200,
	HDMI_AUDIO_SAMPLE_FREQUENCY_96000,
	HDMI_AUDIO_SAMPLE_FREQUENCY_176400,
	HDMI_AUDIO_SAMPLE_FREQUENCY_192000,
}HDMI_AUDIO_SAMPLE_FREQUENCY, * PHDMI_AUDIO_SAMPLE_FREQUENCY;

typedef enum _HDMI_AUDIO_CODING_TYPE_EXTENDED{
    HDMI_AUDIO_CODING_TYPE_EXT = 0,
    HDMI_AUDIO_CODING_TYPE_EXT_HE_AAC,
    HDMI_AUDIO_CODING_TYPE_EXT_HE_AAC_V2,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG_SURROUND,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG_HE_ACC,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG_HE_ACC_V2,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG_AAC_LC,
    HDMI_AUDIO_CODING_TYPE_EXT_DRA,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG4_HE_AAC_SURROUND,
    HDMI_AUDIO_CODING_TYPE_EXT_MPEG4_AAC_LE_SURROUND = 10,
}HDMI_AUDIO_CODING_TYPE_EXTENDED, * PHDMI_AUDIO_CODING_TYPE_EXTENDED;

typedef struct _HDMI_AUDIO_INFO_FRAME{
    HDMI_INFO_FRAME_TYPE            Type;
    UINT8                           Version;
    UINT8                           Length;
    UINT                            Channels;
    HDMI_AUDIO_CODING_TYPE          CodingType;
    HDMI_AUDIO_SAMPLE_SIZE          SampleSize;
    HDMI_AUDIO_SAMPLE_FREQUENCY     SampleFrequency;
    HDMI_AUDIO_CODING_TYPE_EXTENDED CodingTypeExtended;
    UINT8                           ChannelAllocation;
    UINT8                           LevelShitValue;
    BOOLEAN                         DownMixInhibit;
}HDMI_AUDIO_INFO_FRAME, * PHDMI_AUDIO_INFO_FRAME;

typedef struct _HDMI_CODEC_DAIFMT{
    enum {
        HDMI_I2S = 0,
        HDMI_RIGHT_J,
        HDMI_LEFT_J,
        HDMI_DSP_A,
        HDMI_DSP_B,
        HDMI_AC97,
        HDMI_SPDIF,
    }Format;
    UINT                 BitClkInv           :   1;
    UINT                 FrameClkInv         :   1;
    UINT                 BitClkProvider      :   1;
    UINT                 FrameClkProvider    :   1;
    SOUND_PCM_FORMAT     BitFormat;
}HDMI_CODEC_DAIFMT, * PHDMI_CODEC_DAIFMT;

typedef struct _HDMI_CODEC_PARAMETERS{
    HDMI_AUDIO_INFO_FRAME   AudioFrame;
    SOUND_AES_IEC958        Iec;
    int                     SampleRate;
    int                     SampleWidth;
    int                     Channel;    
}HDMI_CODEC_PARAMETERS, * PHDMI_CODEC_PARAMETERS;

#ifdef __cplusplus
}
#endif
#endif