#ifndef _ACPI_AML_H
#define _ACPI_AML_H

#ifndef __cplusplus
#include <LouAPI.h>
#else
#include <LouDDK.h>
extern "C" {
#endif

//AML OPCODES
#define AML_PREFIX_EXTENDED_OPCODE 0x5B
#define AML_OPCODE_ZERO 0x00
#define AML_OPCODE_ONE 0x01
#define AML_OPCODE_ALIAS 0x06
#define AML_OPCODE_NAME 0x08
#define AML_OPCODE_SCOPE 0x10
#define AML_OPCODE_BUFFER 0x11
#define AML_OPCODE_PACKAGE 0x12
#define AML_OPCODE_VARIABLE_PACKAGE 0x13
#define AML_OPCODE_METHOD 0x14
#define AML_OPCODE_EXTERNAL 0x15
#define AML_OPCODE_LOCAL0 0x60
#define AML_OPCODE_LOCAL1 0x61
#define AML_OPCODE_LOCAL2 0x62
#define AML_OPCODE_LOCAL3 0x63
#define AML_OPCODE_LOCAL4 0x64
#define AML_OPCODE_LOCAL5 0x65
#define AML_OPCODE_LOCAL6 0x66
#define AML_OPCODE_LOCAL7 0x67
#define AML_OPCODE_ARG0 0x68
#define AML_OPCODE_ARG1 0x69
#define AML_OPCODE_ARG2 0x6A
#define AML_OPCODE_ARG3 0x6B
#define AML_OPCODE_ARG4 0x6C
#define AML_OPCODE_ARG5 0x6D
#define AML_OPCODE_ARG6 0x6E
#define AML_OPCODE_STORE 0x70
#define AML_OPCODE_REF_OF 0x71
#define AML_OPCODE_ADD 0x72
#define AML_OPCODE_CONCAT 0x73
#define AML_OPCODE_SUBTRACT 0x74
#define AML_OPCODE_INCREMENT 0x75
#define AML_OPCODE_DECREMENT 0x76
#define AML_OPCODE_MULTIPLY 0x77
#define AML_OPCODE_DIVIDE 0x78
#define AML_OPCODE_SHIFT_LEFT 0x79
#define AML_OPCODE_SHIFT_RIGHT 0x7A
#define AML_OPCODE_AND 0x7B
#define AML_OPCODE_NAND 0x7C
#define AML_OPCODE_OR 0x7D
#define AML_OPCODE_NOR 0x7E
#define AML_OPCODE_XOR 0x7F
#define AML_OPCODE_NOT 0x80
#define AML_OPCODE_FIND_SET_LEFT_BIT 0x81
#define AML_OPCODE_FIND_SET_RIGHT_BIT 0x82
#define AML_OPCODE_DEREF_OF 0x83
#define AML_OPCODE_CONCAT_RES 0x84
#define AML_OPCODE_MOD 0x85
#define AML_OPCODE_NOTIFY 0x86
#define AML_OPCODE_SIZEOF 0x87
#define AML_OPCODE_INDEX 0x88
#define AML_OPCODE_MATCH 0x89
#define AML_OPCODE_CREATE_DWORD_FEILD 0x8A
#define AML_OPCODE_CREATE_WORD_FEILD 0x8B
#define AML_OPCODE_CREATE_BYTE_FEILD 0x8C
#define AML_OPCODE_CREATE_BIT_FEILD 0x8D
#define AML_OPCODE_OBJECT_TYPE 0x8E
#define AML_OPCODE_CREATE_QWORD_FEILD 0x8F
#define AML_OPCODE_LAND 0x90
#define AML_OPCODE_LOR 0x91
#define AML_OPCODE_LNOT 0x92
#define AML_OPCODE_LEQUAL 0x93
#define AML_OPCODE_LGREATOR 0x94
#define AML_OPCODE_LLESS 0x95
#define AML_OPCODE_TO_BUFFER 0x96
#define AML_OPCODE_TO_DECIMAL_STRING 0x97
#define AML_OPCODE_TO_HEX_STRING 0x98
#define AML_OPCODE_TO_INTEGER 0x99
#define AML_OPCODE_TO_STRING 0x9C
#define AML_OPCODE_COPY_OBJECT 0x9D
#define AML_OPCODE_MID 0x9E
#define AML_OPCODE_CONTINUE 0x9F
#define AML_OPCODE_IF 0xA0
#define AML_OPCODE_ELSE 0xA1
#define AML_OPCODE_WHILE 0xA2
#define AML_OPCODE_NOOP 0xA3
#define AML_OPCODE_RETURN 0xA4
#define AML_OPCODE_BREAK 0xA5
#define AML_OPCODE_BREAK_POINT 0xA6
#define AML_OPCODE_ONES 0xFF

bool LouKeAcpiIsByteOpcode(uint8_t Byte);

//Extended Codes
#define AML_EXTENDED_OPCODE_MUTEX  0x01
#define AML_EXTENDED_OPCODE_EVENT  0x02
#define AML_EXTENDED_OPCODE_COND_REF_OF  0x12
#define AML_EXTENDED_OPCODE_CREATE_FEILD  0x13
#define AML_EXTENDED_OPCODE_LOAD_TABLE  0x1F
#define AML_EXTENDED_OPCODE_LOAD  0x20
#define AML_EXTENDED_OPCODE_STALL  0x21
#define AML_EXTENDED_OPCODE_SLEEP  0x22
#define AML_EXTENDED_OPCODE_AQUIRE  0x23
#define AML_EXTENDED_OPCODE_SIGNAL  0x24
#define AML_EXTENDED_OPCODE_WAIT  0x25
#define AML_EXTENDED_OPCODE_RESET  0x26
#define AML_EXTENDED_OPCODE_RELEASE  0x27
#define AML_EXTENDED_OPCODE_FROM_BCD  0x28
#define AML_EXTENDED_OPCODE_TO_BCD  0x29
#define AML_EXTENDED_OPCODE_REVISION  0x30
#define AML_EXTENDED_OPCODE_DEBUG  0x31
#define AML_EXTENDED_OPCODE_FATAL  0x32
#define AML_EXTENDED_OPCODE_TIMER  0x33
#define AML_EXTENDED_OPCODE_OP_REGION  0x80
#define AML_EXTENDED_OPCODE_FEILD  0x81
#define AML_EXTENDED_OPCODE_DEVICE  0x82
#define AML_EXTENDED_OPCODE_POWER_RES  0x84
#define AML_EXTENDED_OPCODE_THERMAL_XONE  0x85
#define AML_EXTENDED_OPCODE_INDEX_FEILD  0x86
#define AML_EXTENDED_OPCODE_BANK_FEILD  0x87
#define AML_EXTENDED_OPCODE_DATA_REGION  0x88

//LNOT Codes
#define AML_OPCODE_LNOT_EQUAL 0x93
#define AML_OPCODE_LLES_EQUAL 0x94
#define AML_OPCODE_LGREATOR_EQUAL 0x95

//AML PREFIXES
#define AML_PREFIX_BYTE 0x0A
#define AML_PREFIX_WORD 0x0B
#define AML_PREFIX_DWORD 0x0C
#define AML_PREFIX_STRING 0x0D
#define AML_PREFIX_QWORD 0x0E
#define AML_PREFIX_DUAL_NAME 0x2E
#define AML_PREFIX_MULTI_NAME 0x2F
#define AML_PREFIX_PARENT_CAHR 0x5E
#define AML_PREFIX_ROOT_CAHR 0x5C

#define AML_HANDLE_OP_ANY   0xFFFF
#define AML_HANDLE_OP_ZERO  AML_OPCODE_ZERO
#define AML_HANDLE_OP_ONE   AML_OPCODE_ONE
#define AML_HANDLE_OP_ALIAS AML_OPCODE_ALIAS
#define AML_HANDLE_OP_NAME AML_OPCODE_NAME 
#define AML_HANDLE_OP_SCOPE AML_OPCODE_SCOPE 
#define AML_HANDLE_OP_BUFFER AML_OPCODE_BUFFER 
#define AML_HANDLE_OP_PACKAGE AML_OPCODE_PACKAGE 
#define AML_HANDLE_OP_VARIABLE_PACKAGE AML_OPCODE_VARIABLE_PACKAGE
#define AML_HANDLE_OP_METHOD AML_OPCODE_METHOD 
#define AML_HANDLE_OP_EXTERNAL AML_OPCODE_EXTERNAL
#define AML_HANDLE_OP_LOCAL0 AML_OPCODE_LOCAL0 
#define AML_HANDLE_OP_LOCAL1 AML_OPCODE_LOCAL1 
#define AML_HANDLE_OP_LOCAL2 AML_OPCODE_LOCAL2 
#define AML_HANDLE_OP_LOCAL3 AML_OPCODE_LOCAL3 
#define AML_HANDLE_OP_LOCAL4 AML_OPCODE_LOCAL4 
#define AML_HANDLE_OP_LOCAL5 AML_OPCODE_LOCAL5 
#define AML_HANDLE_OP_LOCAL6 AML_OPCODE_LOCAL6 
#define AML_HANDLE_OP_LOCAL7 AML_OPCODE_LOCAL7 
#define AML_HANDLE_OP_ARG0 AML_OPCODE_ARG0 
#define AML_HANDLE_OP_ARG1 AML_OPCODE_ARG1 
#define AML_HANDLE_OP_ARG2 AML_OPCODE_ARG2 
#define AML_HANDLE_OP_ARG3 AML_OPCODE_ARG3 
#define AML_HANDLE_OP_ARG4 AML_OPCODE_ARG4 
#define AML_HANDLE_OP_ARG5 AML_OPCODE_ARG5 
#define AML_HANDLE_OP_ARG6 AML_OPCODE_ARG6 
#define AML_HANDLE_OP_STORE AML_OPCODE_STORE
#define AML_HANDLE_OP_REF_OF AML_OPCODE_REF_OF 
#define AML_HANDLE_OP_ADD AML_OPCODE_ADD 
#define AML_HANDLE_OP_CONCAT AML_OPCODE_CONCAT 
#define AML_HANDLE_OP_SUBTRACT AML_OPCODE_SUBTRACT 
#define AML_HANDLE_OP_INCREMENT AML_OPCODE_INCREMENT 
#define AML_HANDLE_OP_DECREMENT AML_OPCODE_DECREMENT 
#define AML_HANDLE_OP_MULTIPLY AML_OPCODE_MULTIPLY 
#define AML_HANDLE_OP_DIVIDE AML_OPCODE_DIVIDE 
#define AML_HANDLE_OP_SHIFT_LEFT AML_OPCODE_SHIFT_LEFT 
#define AML_HANDLE_OP_SHIFT_RIGHT AML_OPCODE_SHIFT_RIGHT
#define AML_HANDLE_OP_AND AML_OPCODE_AND 
#define AML_HANDLE_OP_NAND AML_OPCODE_NAND 
#define AML_HANDLE_OP_OR AML_OPCODE_OR 
#define AML_HANDLE_OP_NOR AML_OPCODE_NOR 
#define AML_HANDLE_OP_XOR AML_OPCODE_XOR 
#define AML_HANDLE_OP_NOT AML_OPCODE_NOT 
#define AML_HANDLE_OP_FIND_SET_LEFT_BIT AML_OPCODE_FIND_SET_LEFT_BIT
#define AML_HANDLE_OP_FIND_SET_RIGHT_BIT AML_OPCODE_FIND_SET_RIGHT_BIT
#define AML_HANDLE_OP_DEREF_OF AML_OPCODE_DEREF_OF 
#define AML_HANDLE_OP_CONCAT_RES AML_OPCODE_CONCAT_RES
#define AML_HANDLE_OP_MOD AML_OPCODE_MOD 
#define AML_HANDLE_OP_NOTIFY AML_OPCODE_NOTIFY
#define AML_HANDLE_OP_SIZEOF AML_OPCODE_SIZEOF
#define AML_HANDLE_OP_INDEX AML_OPCODE_INDEX 
#define AML_HANDLE_OP_MATCH AML_OPCODE_MATCH 
#define AML_HANDLE_OP_CREATE_DWORD_FEILD AML_OPCODE_CREATE_DWORD_FEILD
#define AML_HANDLE_OP_CREATE_WORD_FEILD AML_OPCODE_CREATE_WORD_FEILD 
#define AML_HANDLE_OP_CREATE_BYTE_FEILD AML_OPCODE_CREATE_BYTE_FEILD
#define AML_HANDLE_OP_CREATE_BIT_FEILD AML_OPCODE_CREATE_BIT_FEILD 
#define AML_HANDLE_OP_OBJECT_TYPE AML_OPCODE_OBJECT_TYPE 
#define AML_HANDLE_OP_CREATE_QWORD_FEILD AML_OPCODE_CREATE_QWORD_FEILD
#define AML_HANDLE_OP_LAND AML_OPCODE_LAND 
#define AML_HANDLE_OP_LOR AML_OPCODE_LOR  
#define AML_HANDLE_OP_LEQUAL AML_OPCODE_LEQUAL
#define AML_HANDLE_OP_LGREATOR AML_OPCODE_LGREATOR
#define AML_HANDLE_OP_LLES AML_OPCODE_LLESS 
#define AML_HANDLE_OP_TO_BUFFER AML_OPCODE_TO_BUFFER
#define AML_HANDLE_OP_TO_DECIMAL_STRING AML_OPCODE_TO_DECIMAL_STRING
#define AML_HANDLE_OP_TO_HEX_STRING AML_OPCODE_TO_HEX_STRING 
#define AML_HANDLE_OP_TO_INTEGER AML_OPCODE_TO_INTEGER 
#define AML_HANDLE_OP_TO_STRING AML_OPCODE_TO_STRING 
#define AML_HANDLE_OP_COPY_OBJECT AML_OPCODE_COPY_OBJECT
#define AML_HANDLE_OP_MID AML_OPCODE_MID 
#define AML_HANDLE_OP_CONTINUE AML_OPCODE_CONTINUE
#define AML_HANDLE_OP_IF AML_OPCODE_IF 
#define AML_HANDLE_OP_ELSE AML_OPCODE_ELSE
#define AML_HANDLE_OP_WHILE AML_OPCODE_WHILE
#define AML_HANDLE_OP_NOOP AML_OPCODE_NOOP 
#define AML_HANDLE_OP_RETURN AML_OPCODE_RETURN
#define AML_HANDLE_OP_BREAK AML_OPCODE_BREAK 
#define AML_HANDLE_OP_BREAK_POINT AML_OPCODE_BREAK_POINT
#define AML_HANDLE_OP_ONES AML_OPCODE_ONES

#define AML_HANDLE_EXTENDED_OP_MUTEX (AML_EXTENDED_OPCODE_MUTEX << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_EVENT (AML_EXTENDED_OPCODE_EVENT << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_REF_OF (AML_EXTENDED_OPCODE_COND_REF_OF << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_CREATE_FEILD (AML_EXTENDED_OPCODE_CREATE_FEILD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_LOAD_TABLE (AML_EXTENDED_OPCODE_LOAD_TABLE << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_LOAD (AML_EXTENDED_OPCODE_LOAD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_STALL (AML_EXTENDED_OPCODE_STALL << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_SLEEP (AML_EXTENDED_OPCODE_SLEEP << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_ACQUIRE (AML_EXTENDED_OPCODE_AQUIRE << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_SIGNAL (AML_EXTENDED_OPCODE_SIGNAL << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_WAIT (AML_EXTENDED_OPCODE_WAIT << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_RESET (AML_EXTENDED_OPCODE_RESET << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_RELEASE (AML_EXTENDED_OPCODE_RELEASE << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_FROM_BCD (AML_EXTENDED_OPCODE_FROM_BCD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_TO_BCD (AML_EXTENDED_OPCODE_TO_BCD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_REVISION (AML_EXTENDED_OPCODE_REVISION << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_DEBUG (AML_EXTENDED_OPCODE_DEBUG << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_FATAL (AML_EXTENDED_OPCODE_FATAL << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_TIMER (AML_EXTENDED_OPCODE_TIMER << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_REGION (AML_EXTENDED_OPCODE_OP_REGION << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_FEILD (AML_EXTENDED_OPCODE_FEILD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_DEVICE (AML_EXTENDED_OPCODE_DEVICE << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_POWER_RES (AML_EXTENDED_OPCODE_POWER_RES << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_THERMAL_XONE (AML_EXTENDED_OPCODE_THERMAL_XONE << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_INDEX_FEILD (AML_EXTENDED_OPCODE_INDEX_FEILD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_BANK_FEILD (AML_EXTENDED_OPCODE_BANK_FEILD << 8) | AML_PREFIX_EXTENDED_OPCODE
#define AML_HANDLE_EXTENDED_OP_DATA_REGION (AML_EXTENDED_OPCODE_DATA_REGION << 8) | AML_PREFIX_EXTENDED_OPCODE

#define AML_HANDLE_LNOT_OP_LNOT_EQUAL (AML_OPCODE_LNOT_EQUAL << 8) | AML_OPCODE_LNOT
#define AML_HANDLE_LNOT_OP_LLESS_EQUAL (AML_OPCODE_LLES_EQUAL << 8) | AML_OPCODE_LNOT
#define AML_HANDLE_LNOT_OP_LGREATOR_EQUAL (AML_OPCODE_LGREATOR_EQUAL << 8) | AML_OPCODE_LNOT


#ifdef __cplusplus
}
#endif
#endif