#ifndef _TABLE_PARSING_H
#define _TABLE_PARSING_H

// FADT Table Parseing
#define LouKeAcpiGetPreferedPowerModeProfile(x) LouKeAcpiInformationQuery(PREFERED_POWER_MODE_PROFILE_INFO, x)
#define LouKeAcpiGetSci8259PicVector(x) LouKeAcpiInformationQuery(SCI_8259_PIC_INT_INFO, x)
#define LouKeAcpiGetSmiCommandPort(x) LouKeAcpiInformationQuery(SMI_COMMAND_PORT, x)
#define LouKeAcpiGetAcpiEnable(x) LouKeAcpiInformationQuery(ACPI_ENABLE, x)
#define LouKeAcpiGetAcpiDisable(x) LouKeAcpiInformationQuery(ACPI_DISABLE, x)
#define LouKeAcpiGetS4BiosRequestValue(x) LouKeAcpiInformationQuery(S4BIOS_REQUEST_VALUE, x)
#define LouKeAcpiGetProccesorStateControlValue(x) LouKeAcpiInformationQuery(PROCESSOR_STATE_CONTROL_VALUE, x)
#define LouKeAcpiGetPm1aEventRegisterBlockAddress(x) LouKeAcpiInformationQuery(PM1A_EVENT_REGISTER_BLOCK_ADDRESS, x)
#define LouKeAcpiGetPm1bEventRegisterBlockAddress(x) LouKeAcpiInformationQuery(PM1B_EVENT_REGISTER_BLOCK_ADDRESS, x)
#define LouKeAcpiGetPm1aControlRegisterBlockAddress(x) LouKeAcpiInformationQuery(PM1A_CONTROL_REGISTER_BLOCK_ADDRESS, x)
#define LouKeAcpiGetPm1bControlRegisterBlockAddress(x) LouKeAcpiInformationQuery(PM1B_CONTROL_REGISTER_BLOCK_ADDRESS, x)
#define LouKeAcpiGetPm2ControlRegisterBlockAddress(x) LouKeAcpiInformationQuery(PM2_CONTROL_REGISTER_BLOCK_ADDRESS, x)
#define LouKeAcpiGetPmTimerControlRegisterBlock(x) LouKeAcpiInformationQuery(PM_TIMER_CONTROL_REGISTER_BLOCK, x)
#define LouKeAcpiGetGeneralPurposeEventBlock0(x) LouKeAcpiInformationQuery(GENERAL_PURPOSE_EVENT_BLOCK0, x)
#define LouKeAcpiGetGeneralPurposeEventBlock1(x) LouKeAcpiInformationQuery(GENERAL_PURPOSE_EVENT_BLOCK1, x)
#define LouKeAcpiGetPm1EventLength(x) LouKeAcpiInformationQuery(PM1_EVENT_LENGTH, x)
#define LouKeAcpiGetPm2EventLength(x) LouKeAcpiInformationQuery(PM2_EVENT_LENGTH, x)
#define LouKeAcpiGetPmTimerLength(x) LouKeAcpiInformationQuery(PM_TIMER_LENGTH, x)
#define LouKeAcpiGetGeneralPurposeEventBlock0Length(x) LouKeAcpiInformationQuery(GENERAL_PURPOSE_EVENT_BLOCK0_LENGTH, x)
#define LouKeAcpiGetGeneralPurposeEventBlock1Length(x) LouKeAcpiInformationQuery(GENERAL_PURPOSE_EVENT_BLOCK1_LENGTH, x)
#define LouKeAcpiGetGeneralPurposeEventBase(x) LouKeAcpiInformationQuery(GENERAL_PURPOSE_EVENT_BASE, x)
#define LouKeAcpiGetCstCount(x) LouKeAcpiInformationQuery(CST_COUNT, x)
#define LouKeAcpiGetPmLevel2Latency(x) LouKeAcpiInformationQuery(PM_LEVEL_2_LATENCY, x)
#define LouKeAcpiGetPmLevel3Latency(x) LouKeAcpiInformationQuery(PM_LEVEL_3_LATENCY, x)
#define LouKeAcpiGetFadtFlushSize(x) LouKeAcpiInformationQuery(FADT_FLUSH_SIZE, x)
#define LouKeAcpiGetFadtFlushStride(x) LouKeAcpiInformationQuery(FADT_FLUSH_STRIDE, x)
#define LouKeAcpiGetFadtDutyOffset(x) LouKeAcpiInformationQuery(FADT_DUTY_OFFSET, x)
#define LouKeAcpiGetFadtDutyWidth(x) LouKeAcpiInformationQuery(FADT_DUTY_WIDTH, x)
#define LouKeAcpiGetFadtDayAlarm(x) LouKeAcpiInformationQuery(FADT_DAY_ALARM, x)
#define LouKeAcpiGetFadtMonthAlarm(x) LouKeAcpiInformationQuery(FADT_MONTH_ALARM, x)
#define LouKeAcpiGetFadtCentury(x) LouKeAcpiInformationQuery(FADT_CENTURY, x)
#define LouKeAcpiGetFadtIapcBootArch(x) LouKeAcpiInformationQuery(FADT_IAPC_BOOT_ARCH, x)
#define LouKeAcpiGetFadtFeatureFlags(x) LouKeAcpiInformationQuery(FADT_FEATURE_FLAGS, x)
#define LouKeAcpiGetFadtResetRegister(x) LouKeAcpiInformationQuery(FADT_RESET_REGISTER, x)
#define LouKeAcpiGetFadtResetValue(x) LouKeAcpiInformationQuery(FADT_RESET_VALUE, x)
#define LouKeAcpiGetFadtArmBootArch(x) LouKeAcpiInformationQuery(FADT_ARM_BOOT_ARCH, x)
#define LouKeAcpiGetFadtMinorVersion(x) LouKeAcpiInformationQuery(FADT_MINOR_VERSION, x)
#define LouKeAcpiGetFadtSleepStatusRegister(x) LouKeAcpiInformationQuery(FADT_SLEEP_STATUS_REGISTER, x)
#define LouKeAcpiGetFadtHypervisorVendorID(x) LouKeAcpiInformationQuery(FADT_HYPERVISOR_VENDOR_ID, x)


#endif