#ifndef _APIC_INTERNALS_H
#define _APIC_INTERNALS_H

#include <LouAPI.h>

typedef enum{
    APIC_TIMER_MODE_ONE_SHOT = 0,
    APIC_TIMER_MODE_PERIODIC,
    APIC_TIMER_MODE_TSC_DEADLINE,
}APIC_TIMER_MODE;

typedef enum{
    APIC_DELIVERY_MODE_FIXED    = 0b0000,
    APIC_DELIVERY_MODE_SMI      = 0b0010,
    APIC_DELIVERY_MODE_NMI      = 0b0100,
    APIC_DELIVERY_MODE_EXT_INT  = 0b0111,
    APIC_DELIVERY_MODE_INIT     = 0b1000,
}APIC_DELIVERY_MODE;

typedef enum{
    APIC_IN_PIN_POLARITY_ACTIVE_HIGH = 0,
    APIC_IN_PIN_POLARITY_ACTIVE_LOW ,
}APIC_IN_PIN_POLARITY;

typedef struct _APIC_DEVICE_OBJECT{
    mutex_t     WriteLock;
    PVOID       ApicBase;
}APIC_DEVICE_OBJECT, * PAPIC_DEVICE_OBJECT;

#endif