#ifndef _X1APIC_INTERNALS_H
#define _X1APIC_INTERNALS_H

#include <LouDDK.h>
#include "ApicInternals.h"

#define X1APIC_ID_REGISTER_OFFSET                                               0x20
#define X1APIC_VERSION_REGISTER_OFFSET                                          0x30
#define X1APIC_TASK_PRIORITY_REGISTER_OFFSET                                    0x80
#define X1APIC_ARBITRATION_PRIOIRITY_REGISTER_OFFSET                            0x90
#define X1APIC_PROCESSOR_PRIORITY_REGISTER_OFFSET                               0xA0
#define X1APIC_END_OF_INTERRUPT_REGISTER_OFFSET                                 0xB0
#define X1APIC_REMOTE_READ_REGISTER_OFFSET                                      0xC0
#define X1APIC_LOGICAL_DESTINATION_REGISTER_OFFSET                              0xD0
#define X1APIC_DESTINATION_FORMAT_REGISTER_OFFSET                               0xE0
#define X1APIC_SPURIOUS_INTERRUPT_VECTOR_REGISTER_OFFSET                        0xF0
#define X1APIC_IN_SERVICE_REGISTER_BITS_0_31_OFFSET                             0x100
#define X1APIC_IN_SERVICE_REGISTER_BITS_32_63_OFFSET                            0x110
#define X1APIC_IN_SERVICE_REGISTER_BITS_64_95_OFFSET                            0x120
#define X1APIC_IN_SERVICE_REGISTER_BITS_96_127_OFFSET                           0x130
#define X1APIC_IN_SERVICE_REGISTER_BITS_128_159_OFFSET                          0x140
#define X1APIC_IN_SERVICE_REGISTER_BITS_160_191_OFFSET                          0x150
#define X1APIC_IN_SERVICE_REGISTER_BITS_192_223_OFFSET                          0x160
#define X1APIC_IN_SERVICE_REGISTER_BITS_224_255_OFFSET                          0x170
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_0_31_OFFSET                           0x180
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_32_63_OFFSET                          0x190
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_64_95_OFFSET                          0x1A0
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_96_127_OFFSET                         0x1B0
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_128_159_OFFSET                        0x1C0
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_160_191_OFFSET                        0x1D0
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_192_223_OFFSET                        0x1E0
#define X1APIC_TRIGGER_MODE_REGISTER_BITS_224_255_OFFSET                        0x1F0
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_0_31_OFFSET                      0x200
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_32_63_OFFSET                     0x210
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_64_95_OFFSET                     0x220
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_96_127_OFFSET                    0x230
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_128_159_OFFSET                   0x240
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_160_191_OFFSET                   0x250
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_192_223_OFFSET                   0x260
#define X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_224_255_OFFSET                   0x270
#define X1APIC_ERROR_STATUS_REGISTER_OFFSET                                     0x280
#define X1APIC_LVT_CMCI_REGISTER_OFFSET                                         0x2F0
#define X1APIC_INTERRUPT_COMMAND_REGISTER_LOW_OFFSET                            0x300
#define X1APIC_INTERRUPT_COMMAND_REGISTER_HIGH_OFFSET                           0x310
#define X1APIC_LVT_TIMER_REGISTER_OFFSET                                        0x320
#define X1APIC_LVT_THERMAL_SENSOR_REGISTER_OFFSET                               0x330
#define X1APIC_LVT_PERFORMANCE_MONITORING_COUNTERS_REGISTER_OFFSET              0x340
#define X1APIC_LVT_LINT0_REGISTER_OFFSET                                        0x350
#define X1APIC_LVT_LINT1_REGISTER_OFFSET                                        0x360
#define X1APIC_ERROR_REGISTER_OFFSET                                            0x370
#define X1APIC_INITIAL_COUNT_REGISTER_OFFSET                                    0x380
#define X1APIC_CURRENT_COUNT_REGISTER_OFFSET                                    0x390
#define X1APIC_DIVIDE_CONFIGURATION_REGISTER                                    0x3E0

#define GET_X1APIC_ID_REGISTER(ApicBase)                                        ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ID_REGISTER_OFFSET)))
#define GET_X1APIC_VERSION_REGISTER(ApicBase)                                   ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_VERSION_REGISTER_OFFSET)))
#define GET_X1APIC_TASK_PRIORITY_REGISTER(ApicBase)                             ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_TASK_PRIORITY_REGISTER_OFFSET)))
#define GET_X1APIC_ARBITRATION_PRIOIRTY_REGISTER(ApicBase)                      ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ARBITRATION_PRIOIRITY_REGISTER_OFFSET)))
#define GET_X1APIC_PROCESSOR_PRIORITY_REGISTER(ApicBase)                        ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_PROCESSOR_PRIORITY_REGISTER_OFFSET)))
#define GET_X1APIC_REMOTE_READ_REGISTER(ApicBase)                               ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_REMOTE_READ_REGISTER_OFFSET)))
#define GET_X1APIC_LOGICAL_DESTINATION_REGISTER(ApicBase)                       ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LOGICAL_DESTINATION_REGISTER_OFFSET)))
#define GET_X1APIC_DESTINATION_FORMAT_REGISTER(ApicBase)                        ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_DESTINATION_FORMAT_REGISTER_OFFSET)))
#define GET_X1APIC_SPURIOUS_INTERRUPT_VECTOR_REGISTER(ApicBase)                 ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_SPURIOUS_INTERRUPT_VECTOR_REGISTER_OFFSET)))
#define GET_X1APIC_IN_SERVICE_REGISTER_X32(ApicBase, x)                         ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_IN_SERVICE_REGISTER_BITS_0_31_OFFSET + (x * 0x10))))
#define GET_X1APIC_TRIGGER_MODE_REGISTER_X32(ApicBase, x)                       ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_TRIGGER_MODE_REGISTER_BITS_0_31_OFFSET + (x * 0x10))))
#define GET_X1APIC_INTERRUPT_REQUEST_REGISTER_X32(ApicBase, x)                  ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INTERRUPT_REQUEST_REGISTER_BITS_0_31_OFFSET + (x * 0x10))))
#define GET_X1APIC_ERROR_STATUS_REGISTER(ApicBase)                              ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ERROR_STATUS_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_CMCI_REGISTER(ApicBase)                                  ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_CMCI_REGISTER_OFFSET)))
#define GET_X1APIC_INTERRUPT_CONTROL_REGISTER_LOW(ApicBase)                     ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INTERRUPT_COMMAND_REGISTER_LOW_OFFSET)))
#define GET_X1APIC_INTERRUPT_CONTROL_REGISTER_HIGH(ApicBase)                    ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INTERRUPT_COMMAND_REGISTER_HIGH_OFFSET)))
#define GET_X1APIC_LVT_TIMER_REGISTER(ApicBase)                                 ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_TIMER_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_THERMAL_SENSOR_REGISTER(ApicBase)                        ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_THERMAL_SENSOR_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_PERFORMANCE_MONITORING_COUNTERS_REGISTER(ApicBase)       ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_PERFORMANCE_MONITORING_COUNTERS_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_LINT0_REGISTER(ApicBase)                                 ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_LINT0_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_LINT1_REGISTER(ApicBase)                                 ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_LINT1_REGISTER_OFFSET)))
#define GET_X1APIC_LVT_ERROR_REGISTER(ApicBase)                                 ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ERROR_REGISTER_OFFSET)))
#define GET_X1APIC_INITIAL_COUNT_REGISTER(ApicBase)                             ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INITIAL_COUNT_REGISTER_OFFSET)))
#define GET_X1APIC_CURRENT_COUNT_REGISTER(ApicBase)                             ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_CURRENT_COUNT_REGISTER_OFFSET)))
#define GET_X1APIC_DIVIDE_CONFIGURATION_REGISTER(ApicBase)                      ((UINT32)READ_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_DIVIDE_CONFIGURATION_REGISTER)))



#define SET_X1APIC_ID_REGISTER(ApicBase, x)                                     WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ID_REGISTER_OFFSET), x)
#define SET_X1APIC_TASK_PRIORITY_REGISTER(ApicBase, x)                          WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_TASK_PRIORITY_REGISTER_OFFSET), x)
#define SET_X1APIC_END_OF_INTERRUPT_REGISTER(ApicBase, x)                       WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_END_OF_INTERRUPT_REGISTER_OFFSET), x)
#define SET_X1APIC_LOGICAL_DESTINATION_REGISTER(ApicBase, x)                    WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LOGICAL_DESTINATION_REGISTER_OFFSET), x)
#define SET_X1APIC_DESTINATION_FORMAT_REGISTER(ApicBase, x)                     WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_DESTINATION_FORMAT_REGISTER_OFFSET), x)
#define SET_X1APIC_SPURIOUS_INTERRUPT_VECTOR_REGISTER(ApicBase, x)              WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_SPURIOUS_INTERRUPT_VECTOR_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_CMCI_REGISTER(ApicBase, x)                               WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_CMCI_REGISTER_OFFSET), x)
#define SET_X1APIC_INTERRUPT_CONTROL_REGISTER_LOW(ApicBase, x)                  WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INTERRUPT_COMMAND_REGISTER_LOW_OFFSET), x)
#define SET_X1APIC_INTERRUPT_CONTROL_REGISTER_HIGH(ApicBase, x)                 WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INTERRUPT_COMMAND_REGISTER_HIGH_OFFSET), x)
#define SET_X1APIC_LVT_TIMER_REGISTER(ApicBase, x)                              WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_TIMER_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_THERMAL_SENSOR_REGISTER(ApicBase, x)                     WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_THERMAL_SENSOR_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_PERFORMANCE_MONITORING_COUNTERS_REGISTER(ApicBase, x)    WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_PERFORMANCE_MONITORING_COUNTERS_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_LINT0_REGISTER(ApicBase, x)                              WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_LINT0_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_LINT1_REGISTER(ApicBase, x)                              WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_LVT_LINT1_REGISTER_OFFSET), x)
#define SET_X1APIC_LVT_ERROR_REGISTER(ApicBase, x)                              WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_ERROR_REGISTER_OFFSET), x)
#define SET_X1APIC_INITIAL_COUNT_REGISTER(ApicBase, x)                          WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_INITIAL_COUNT_REGISTER_OFFSET), x)
#define SET_X1APIC_DIVIDE_CONFIGURATION_REGISTER(ApicBase, x)                   WRITE_REGISTER_ULONG((PULONG)(PVOID)((UINTPTR)ApicBase + X1APIC_DIVIDE_CONFIGURATION_REGISTER), x)



#define X1APIC_ID_SHIFT                                         24
#define X1APIC_ID_MASK                                          0xFF
#define GET_X1APIC_ID_VALUE(IdRegister)                         ((IdRegister >> X1APIC_ID_SHIFT) & X1APIC_ID_MASK)



#define X1APIC_VERSION_SHIFT                                    0
#define X1APIC_VERSION_MASK                                     0xFF
#define GET_X1APIC_VERSION_VALUE(VersionRegister)               ((VersionRegister >> X1APIC_VERSION_SHIFT) & X1APIC_VERSION_MASK)
#define X1APIC_MAX_LVT_ENTRY_SHIFT                              16
#define X1APIC_MAX_LVT_ENTRY_MASK                               0xFF
#define GET_X1APIC_MAX_LVT_ENTRY_VALUE(VersionRegister)         ((VersionRegister >> X1APIC_MAX_LVT_ENTRY_SHIFT) & X1APIC_MAX_LVT_ENTRY_MASK)
#define X1APIC_SUPPORT_EOI_SUPRESS_SHIFT                        24
#define X1APIC_SUPPORT_EOI_SUPRESS_MASK                         0x01
#define X1APIC_SUPPORT_EOI_SUPRESS_VALUE(VersionRegister)       ((VersionRegister >> X1APIC_SUPPORT_EOI_SUPRESS_SHIFT) & X1APIC_SUPPORT_EOI_SUPRESS_MASK)



#endif