#include "Drsd.h"

typedef enum{
	DDS_OK  = 0,
	DDS_ERROR_ALREADY_INITIALIZED,
	DDS_ERROR_BLT_FAST_CANT_CLIP,
	DDS_ERROR_CANNOT_ATTATCH_SURFACE,
	DDS_ERROR_CANNOT_DETATCH_SURFACE,
	DDS_ERROR_CANNOT_CREATE_DEVICE_CONTEXT,
	DDS_ERROR_CANNOT_DUPLICATE,
	DDS_ERROR_CANNOT_LOCK_SURFACE,
	DDS_ERROR_CANNOT_PAGE_LOCK,
	DDS_ERROR_CANNOT_PAGE_UNLOCK,
	DDS_ERROR_CLIPPER_USING_WINDOW_HANDLE,
	DDS_ERROR_COLOR_KEY_NOT_SET,
	DDS_ERROR_CURRENTLY_NOT_AVAILABLE,
	DDS_ERROR_DDSCAPS_COMPLEX_REQUIRED,
	DDS_ERROR_DEVICE_CONTEXT_ALREADY_CREATED,
	DDS_ERROR_DEVICE_DOES_NOT_OWN_SURFACE,
	DDS_ERROR_DRSD_DRAW_ALREADY_CREATED,
	DDS_ERROR_EXCEPTION,
	DDS_ERROR_EXCLUSIVE_MODE_ALREADY_SET,
	DDS_ERROR_EXPIRED,
	DDS_ERROR_GENERIC,
	DDS_ERROR_HEIGHT_ALIGN,
	DDS_ERROR_WINDOW_HANDLE_ALREADY_SET,
	DDS_ERROR_WINDOW_HANDLE_SUB_CLASSED,
	DDS_ERROR_IMPLICITLY_CREATED,
	DDS_ERROR_INCOMPATIBLE_PRIMARY,
	DDS_ERROR_INVALID_CAPS,
	DDS_ERROR_INVALID_CLIP_LIST,
	DDS_ERROR_INVALID_DRSD_DRAW_GUID,
	DDS_ERROR_INVALID_MODE,
	DDS_ERROR_INVALID_OBJECT,
	DDS_ERROR_INVALID_PARAMS,
	DDS_ERROR_INVALID_PIXEL_FORMAT,
	DDS_ERROR_INVALID_POSITION,
	DDS_ERROR_INVALID_RECTANGLE,
	DDS_ERROR_INVALID_STREAM,
	DDS_ERROR_INVALID_SURFACE_TYPE,
	DDS_ERROR_LOCKED_SURFACES,
	DDS_ERROR_MORE_DATA,
	DDS_ERROR_NEW_MODE,
	DDS_ERROR_NO_3D,
	DDS_ERROR_NO_ALPHA_HARDWARE,
	DDS_ERROR_NO_BLIT_HARDWARE,
	DDS_ERROR_NO_CLIP_LIST,
	DDS_ERROR_NO_CLIPPER_ATTATCHED,
	DDS_ERROR_NO_COLOR_CONVERSION_HARDWARE,
	DDS_ERROR_NO_COLOR_KEY,
	DDS_ERROR_NO_COLOR_KEY_HARDWARE,
	DDS_ERROR_NO_COOPERATIVE_LEVEL_SET,
	DDS_ERROR_NO_DEVICE_CONTEXT,
	DDS_ERROR_NO_DRSD_RASTERIZATION_OPERATION_HARDWARE,
	DDS_ERROR_NO_DRSD_DRAW_HARDWARE,
	DDS_ERROR_NO_DRSD_SUPPORT,
	DDS_ERROR_NO_DRIVER,
	DDS_ERROR_NO_EMULATION,
	DDS_ERROR_NO_EXCLUSIVE_MODE,
	DDS_ERROR_NO_FLIP_HARDWARE,
	DDS_ERROR_NO_FOCUS_WINDOW,
	DDS_ERROR_NO_GDI,
	DDS_ERROR_NO_WINDOW_HANDLE,
	DDS_ERROR_NO_MIPMAP_HARDWARE,
	DDS_ERROR_NO_MIRROR_HARDWARE,
	DDS_ERROR_NO_MONITOR_INFORMATION,
	DDS_ERROR_NO_NONLOCAL_VIDEO_MEMORY,
	DDS_ERROR_NO_OPTIMIZE_HARDWARE,
	DDS_ERROR_NO_OVERLAY_DESTINATION,
	DDS_ERROR_NO_OVERLAY_HARDWARE,
	DDS_ERROR_NO_PALETTE_ATTATCHED,
	DDS_ERROR_NO_PALETTE_HARDWARE,
	DDS_ERROR_NO_RASTER_OPERATION_HARDWARE,
	DDS_ERROR_NO_ROTATION_HARDWARE,
	DDS_ERROR_NO_STERO_HARDWARE,
	DDS_ERROR_NO_STRETCH_HARDWARE,
	DDS_ERROR_NO_SURFACE_LEFT,
	DDS_ERROR_NOT_4BIT_COLOR,
	DDS_ERROR_NOT_4BIT_COLOR_INDEX,
	DDS_ERROR_NOT_8BIT_COLOR,
	DDS_ERROR_NOT_OVERLAY_SURFACE,
	DDS_ERROR_NO_TEXTURE_HARDWARE,
	DDS_ERROR_NOT_FLIPPABLE,
	DDS_ERROR_NOT_FOUND,
	DDS_ERROR_NOT_INITIALIZED,
	DDS_ERROR_NOT_LOADED,
	DDS_ERROR_NOT_LOCKED,
	DDS_ERROR_NOT_PAGE_LOCKED,
	DDS_ERROR_NOT_PALETTETIZED,
	DDS_ERROR_NO_VSYNC_HARDWARE,
	DDS_ERROR_NO_ZBUFFER_HARDWARE,
	DDS_ERROR_NO_ZOVERLAY_HARDWARE,
	DDS_ERROR_OUT_OF_CAPS,
	DDS_ERROR_OUT_OF_MEMORY,
	DDS_ERROR_OUT_OF_VIDEO_MEMORY,
	DDS_ERROR_OVERLAPPING_RECTS,
	DDS_ERROR_OVERLAY_CANT_CLIP,
	DDS_ERROR_OVERLAY_COLOR_KEY_ONLY_ONE_ACTIVE,
	DDS_ERROR_OVERLAY_NOT_VISABLE,
	DDS_ERROR_PALETTE_BUST,
	DDS_ERROR_PRIMARY_SURFACE_ALREADY_EXISTS,
	DDS_ERROR_REGION_TOO_SMALL,
	DDS_ERROR_SURFACE_ALREADY_ATTATCHED,
	DDS_ERROR_SURFACE_ALREADY_DEPENDENT,
	DDS_ERROR_SURFACE_BUSY,
	DDS_ERROR_SURFACE_IS_OBSCURE,
	DDS_ERROR_SURFACE_LOST,
	DDS_ERROR_SURFACE_NOT_ATTATCHED,
	DDS_ERROR_TEST_FINISHED,
	DDS_ERROR_TO_BIG_HEIGHT,
	DDS_ERROR_TO_BIG_SIZE,
	DDS_ERROR_TO_BIG_WIDTH,
	DDS_ERROR_UNSUPPORTED,
	DDS_ERROR_UNSUPPORTED_FORMAT,
	DDS_ERROR_UNSUPPORTED_MASK,
	DDS_ERROR_UNSUPPORTED_MODE,
	DDS_ERROR_VERTICAL_BLANK_IN_PROGRESS,
	DDS_ERROR_VIDEO_NOT_ACTIVE,
	DDS_ERROR_WAS_STILL_DRAWING,
	DDS_ERROR_WRONG_MODE,
	DDS_ERROR_XALIGN,
}DRSD_DRAW_STATUS;

typedef struct _DRSD_DRAW_COLOR_CONTROL{
	DWORD	Size;
	DWORD	Flags;
	LONG	Brightness;
	LONG 	Contrast;
	LONG 	Hue;
	LONG 	Saturation;
	LONG	Sharpness;
	LONG 	Gamma;
	LONG 	ColorEnable;
	LONG 	Reserved1;
}DRSD_DRAW_COLOR_CONTROL, * PDRSD_DRAW_COLOR_CONTROL;

typedef struct _DRSD_DRAW_CAPS{
	DWORD 	Caps;
}DRSD_DRAP_CAPS, * PDRSD_DRAW_CAPS;

typedef struct _DRSD_DRAW_CAPS_EX{
	DWORD 		Caps;
	DWORD		Caps2;
	DWORD		Caps3;
	union{
		DWORD	Caps4;
		DWWORD	VolumeDepth;
	};
}DRSD_DRAW_CAPS_EX, * PDRSD_DRAW_CAPS_EX;
