
clean:
	$(MAKE) -C SCSI clean
	$(MAKE) -C Ata  clean
	$(MAKE) -C Ahci clean
	$(MAKE) -C AtaAcceleration clean

all:
	$(MAKE) -C SCSI all
	$(MAKE) -C Ata  all
	$(MAKE) -C Ahci all
	$(MAKE) -C AtaAcceleration all