#include <Modulation.h>
#include <cstdint.h>

#ifndef _APIC_EXTERN_INTERN_H
#define _APIC_EXTERN_INTERN_H
KERNEL_EXPORT UINT32 LouKeGetCurrentCpuPhysicalId();
KERNEL_EXPORT uint32_t GetNPROC();
KERNEL_EXPORT void UpgradeNPROC();
KERNEL_EXPORT void DowngradeNPROC();
#endif

#ifndef _APIC_INTERNALS_H
#ifndef _APIC_EXTERNAL_H
#define _APIC_EXTERNAL_H

typedef enum{
    APIC_TIMER_MODE_ONE_SHOT = 0,
    APIC_TIMER_MODE_PERIODIC,
    APIC_TIMER_MODE_TSC_DEADLINE,
}APIC_TIMER_MODE;

typedef enum{
    APIC_LVT_DELIVERY_MODE_FIXED    = 0b0000,
    APIC_LVT_DELIVERY_MODE_SMI      = 0b0010,
    APIC_LVT_DELIVERY_MODE_NMI      = 0b0100,
    APIC_LVT_DELIVERY_MODE_EXT_INT  = 0b0111,
    APIC_LVT_DELIVERY_MODE_INIT     = 0b1000,
}APIC_LVT_DELIVERY_MODE;

typedef enum {
    APIC_TRIGGER_MODE_EDGE = 0,
    APIC_TRIGGER_MODE_LEVEL,
}APIC_TRIGGER_MODE;

typedef enum{
    APIC_IN_PIN_POLARITY_ACTIVE_HIGH = 0,
    APIC_IN_PIN_POLARITY_ACTIVE_LOW,
}APIC_IN_PIN_POLARITY;

typedef enum{
    APIC_ERROR_STATUS_SEND_CHECKSUM_ERROR =     (1),
    APIC_ERROR_STATUS_RECEIVE_CHECKSUM_ERROR =  (1 << 1),
    APIC_ERROR_STATUS_SEND_ACCEPT_ERROR =       (1 << 2),
    APIC_ERROR_STATUS_RECEIVE_ACCEPT_ERROR =    (1 << 3),
    APIC_ERROR_STATUS_REDIRECT_IPI =            (1 << 4),
    APIC_ERROR_STATUS_SEND_ILLEGAL_VECTOR =     (1 << 5),
    APIC_ERROR_STATUS_RECEIVE_ILLEGAL_VECTOR =  (1 << 6),
    APIC_ERROR_STATUS_ILLEGAL_VECTOR_ADDRESS =  (1 << 7),
}APIC_ERROR_STATUS;

typedef enum{
    APIC_TIMER_DIVIDE_BY2   = 0b0000,
    APIC_TIMER_DIVIDE_BY4   = 0b0001,
    APIC_TIMER_DIVIDE_BY8   = 0b0010,
    APIC_TIMER_DIVIDE_BY16  = 0b0011,
    APIC_TIMER_DIVIDE_BY32  = 0b1000,
    APIC_TIMER_DIVIDE_BY64  = 0b1001,
    APIC_TIMER_DIVIDE_BY128 = 0b1010,
    APIC_TIMER_DIVIDE_BY1   = 0b1011, 
}APIC_TIMER_DIVIDE_CONFIG;

typedef enum {
    APIC_ICR_DELIVERY_MODE_FIXED = 0,
    APIC_ICR_DELIVERY_MODE_LOWEST_PRIORITY,
    APIC_ICR_DELIVERY_MODE_SMI,
    APIC_ICR_DELIVERY_MODE_RSVD0,
    APIC_ICR_DELIVERY_MODE_NMI,
    APIC_ICR_DELIVERY_MODE_INIT,
    APIC_ICR_DELIVERY_MODE_STARTUP,
}APIC_ICR_DELIVERY_MODE;

typedef enum{
    APIC_DESTINATION_MODE_PHYSICAL = 0,
    APIC_DESTINATION_MODE_LOGICAL,
}APIC_DESTINATION_MODE;

typedef enum{
    APIC_LEVEL_DE_ASSERT = 0,
    APIC_LEVEL_ASSERT,
}APIC_LEVEL;

typedef enum{
    APIC_DESTINATION_SHORTHAND_NONE,
    APIC_DESTINATION_SHORTHAND_SELF,
    APIC_DESTINATION_SHORTHAND_ALL,
    APIC_DESTINATION_SHORTHAND_ALL_ES, //excluding self
}APIC_DESTINATION_SHORTHAND;

typedef enum {
    X1_LOCAL_APIC_OBJECT_TYPE = 0,
    X2_LOCAL_APIC_OBJECT_TYPE,
    IO_APIC_OBJECT_TYPE,
    TOTAL_APIC_OBJECT_TYPES,
}APIC_OBJECT_TYPE;

typedef enum{
    IO_APIC_DELIVERY_MODE_FIXED = 0,
    IO_APIC_DELIVERY_MODE_LOWEST,
    IO_APIC_DELIVERY_MODE_SMI,
    IO_APIC_DELIVERY_MODE_NMI,
    IO_APIC_DELIVERY_MODE_INIT,
    IO_APIC_DELIVERY_MODE_EXT_INT,
}IO_APIC_DELIVERY_MODE;

typedef enum{
    IO_APIC_DELIVERY_MODE_PHYSICAL = 0,
    IO_APIC_DELIVERY_MODE_LOGICAL = 1,
}IO_APIC_DESTINATION_MODE;

typedef enum{
    IO_APIC_PIN_POLARITY_ACTIVE_HIGH = 0,
    IO_APIC_PIN_POLARITY_ISA_DEFAULT = 0,
    IO_APIC_PIN_POLARITY_ACTIVE_LOW,
}IO_APIC_PIN_POLARITY;

typedef enum{
    IO_APIC_TRIGGER_MODE_EDGE = 0,
    IO_APIC_TRIGGER_MODE_ISA_DEFAULT = 0,
    IO_APIC_TRIGGER_MODE_LEVEL,
}IO_APIC_TRIGGER_MODE;

typedef PVOID PAPIC_DEVICE_OBJECT;

DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicIdRegister(UINT32* IdOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicVersionRegister(UINT32* VersionOut, UINT32* MaxLvtOut, BOOLEAN* SupportsEoiSuppresionOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtTimerRegister(APIC_TIMER_MODE* TimerModeOut, BOOLEAN* MaskedOut, BOOLEAN* InterruptPendingOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtCmciRegister(BOOLEAN* MaskedOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtLint0Register(BOOLEAN* MaskedOut, APIC_TRIGGER_MODE* TriggerModeOut, BOOLEAN* IrrSetOut, APIC_IN_PIN_POLARITY* InPinPolarityOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtLint1Register(BOOLEAN* MaskedOut, APIC_TRIGGER_MODE* TriggerModeOut, BOOLEAN* IrrSetOut, APIC_IN_PIN_POLARITY* InPinPolarityOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtErrorRegister(BOOLEAN* MaskedOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtPerformanceMonitoringCountersRegister(BOOLEAN* MaskedOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLvtThermalSensorRegister(BOOLEAN* MaskedOut, BOOLEAN* InterruptPendingOut, APIC_LVT_DELIVERY_MODE* DeliveryModeOut, UINT8* VectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicLogicalDestinationRegister(UINT32* IdOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicDestinationFormatRegister(UINT32* DfrModelOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicArbitrationPriorityRegister(UINT32* ClassOut, UINT32* SubClassOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicTaskPriorityRegister(UINT32* ClassOut, UINT32* SubClassOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicProcessorPriorityRegister(UINT32* ClassOut, UINT32* SubClassOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicSpuriousInterruptVectorRegister(BOOLEAN* EoiBroadcastSuppresedOut, BOOLEAN* FocusProcessorCheckingEnabledOut, BOOLEAN* ApicSoftwareEnabledOut, UINT8* SpuriousInterruptVectorOut);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicIdRegister(UINT32* IdIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtTimerRegister(APIC_TIMER_MODE* TimerModeIn, BOOLEAN* MaskedIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtCmciRegister(BOOLEAN* MaskedIn, APIC_LVT_DELIVERY_MODE* DeliveryModeIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtLint0Register(BOOLEAN* MaskedIn, APIC_TRIGGER_MODE* TriggerModeIn, APIC_IN_PIN_POLARITY* InPinPolarityIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtLint1Register(BOOLEAN* MaskedIn, APIC_TRIGGER_MODE* TriggerModeIn,  APIC_IN_PIN_POLARITY* InPinPolarityIn,  UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtErrorRegister(BOOLEAN* MaskedIn,  APIC_LVT_DELIVERY_MODE* DeliveryModeIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtPerformanceMonitoringCountersRegister(BOOLEAN* MaskedIn, APIC_LVT_DELIVERY_MODE* DeliveryModeIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLvtThermalSensorRegister(BOOLEAN* MaskedIn, APIC_LVT_DELIVERY_MODE* DeliveryModeIn, UINT8* VectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicInterruptCommandRegister(UINT32 DestinationField, APIC_DESTINATION_SHORTHAND  Shorthand, APIC_TRIGGER_MODE TriggerMode, APIC_LEVEL Level, APIC_DESTINATION_MODE DestinationMode, APIC_ICR_DELIVERY_MODE DeliveryMode, UINT8 Vector);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicLogicalDestinationRegister(UINT32* IdIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicDestinationFormatRegister(UINT32* DfrModelIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicTaskPriorityRegister(UINT32* ClassIn, UINT32* SubClassIn);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicSpuriousInterruptVectorRegister(BOOLEAN* EoiBroadcastSuppresedIn, BOOLEAN* FocusProcessorCheckingEnabledIn, BOOLEAN* ApicSoftwareEnabledIn, UINT8* SpuriousInterruptVectorIn);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicDivideConfigurationRegister(APIC_TIMER_DIVIDE_CONFIG* DivideConfigOut);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicDivideConfigurationRegister(APIC_TIMER_DIVIDE_CONFIG DivideConfig);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicTimerInitialCount(UINT32* InitialCountOut);
DRIVER_IMPORT LOUSTATUS ApicHalSetLocalApicTimerInitialCount(UINT32 InitialCount);
DRIVER_IMPORT LOUSTATUS ApicHalGetLocalApicTimerCurrentCount(UINT32* CurrentCountOut);

DRIVER_IMPORT LOUSTATUS ApicHalGetIoApicIdRegisterFromObject(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT32* VersionOut);
DRIVER_IMPORT LOUSTATUS ApicHalGetIoApicVersionRegisterFromObject(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT32* Version, UINT32* MaxRedirections);
DRIVER_IMPORT LOUSTATUS ApicHalGetIoApicArbitrationIdRegisterFromObject(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT32* Id);
DRIVER_IMPORT LOUSTATUS ApicHalGetIoApicRedirectionEntryFromObjectEx(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT64 Entry, UINT64* Out);
DRIVER_IMPORT LOUSTATUS ApicHalGetIoApicRedirectionEntryFromObject(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT64 Entry, UINT32* Destination, BOOLEAN* Masked, IO_APIC_TRIGGER_MODE* TriggerMode, BOOLEAN* IrrSet, IO_APIC_PIN_POLARITY* PinPolarity, BOOLEAN* InterruptPending, IO_APIC_DESTINATION_MODE* DestinationMode, IO_APIC_DELIVERY_MODE* DeliveryMode, UINT8* Vector);
DRIVER_IMPORT LOUSTATUS ApicHalSetIoApicRedirectionEntryFromObjectEx(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT64 Entry, UINT64 In);
DRIVER_IMPORT LOUSTATUS ApicHalSetIoApicRedirectionEntryFromObject(PAPIC_DEVICE_OBJECT ApicDeviceObject, UINT64 Entry, UINT32* Destination, BOOLEAN* Masked, IO_APIC_TRIGGER_MODE* TriggerMode, IO_APIC_PIN_POLARITY* PinPolarity, IO_APIC_DESTINATION_MODE* DestinationMode, IO_APIC_DELIVERY_MODE* DeliveryMode, UINT8* Vector);

DRIVER_IMPORT LOUSTATUS ApicInitializeAdvancedProgramableInterruptController(SIZE Cpu);

#endif
#endif