#ifndef _NOTIFICATIONS_H
#define _NOTIFICATIONS_H

typedef struct _LOUSINE_KERNEL_NOTIFICATION_BLOCK{
    struct _LOUSINE_KERNEL_NOTIFICATION_BLOCK*  NextNotification;
    LOUSTATUS                                   (*NotificationCall)(struct _LOUSINE_KERNEL_NOTIFICATION_BLOCK Block, void* Data);
    int                                         PriorityOfNotification;
}LOUSINE_KERNEL_NOTIFICATION_BLOCK, * PLOUSINE_KERNEL_NOTIFICATION_BLOCK;

typedef struct _LOUSINE_KERNEL_ATOMIC_NOTIFICATION_HEAD{
    spinlock_t                          NotificationLock;
    PLOUSINE_KERNEL_NOTIFICATION_BLOCK  Head;
}LOUSINE_KERNEL_ATOMIC_NOTIFICATION_HEAD, * PLOUSINE_KERNEL_ATOMIC_NOTIFICATION_HEAD;

typedef struct _LOUSINE_KERNEL_BLOCKING_NOTIFICATION_HEAD{
    mutex_t                             Semaphore;
    PLOUSINE_KERNEL_NOTIFICATION_BLOCK  Head;
}LOUSINE_KERNEL_BLOCKING_NOTIFICATION_HEAD, * PLOUSINE_KERNEL_BLOCKING_NOTIFICATION_HEAD;

typedef struct _LOUSINE_KERNEL_RAW_NOTIFICATION_HEAD{
    PLOUSINE_KERNEL_NOTIFICATION_BLOCK  Head;
}LOUSINE_KERNEL_RAW_NOTIFICATION_HEAD, * PLOUSINE_KERNEL_RAW_NOTIFICATION_HEAD;


#endif