#ifndef _NOTIFICATIONS_H
#define _NOTIFICATIONS_H

typedef struct _LOUSINE_KERNEL_NOTIFICATION_BLOCK{
    void* Foo;
}LOUSINE_KERNEL_NOTIFICATION_BLOCK, * PLOUSINE_KERNEL_NOTIFICATION_BLOCK;

typedef struct _LOUSINE_KERNEL_NOTIFICATION_HEAD{
    void* Foo;
}LOUSINE_KERNEL_NOTIFICATION_HEAD, * PLOUSINE_KERNEL_NOTIFICATION_HEAD;

#endif