#ifndef _SCSI_CORE_H
#define _SCSI_CORE_H

#include <LouDDK.h>

//Command data types are in Big Endian (32 : 24 : 16 : 8 : 0)

typedef struct PACKED _SCSI_CDB6_COMMAND{
    UINT8   OpCode;
    UINT8   MsbMci;
    UINT16  Lba;
    UINT8   TpaLength;
    UINT8   Control;
}SCSI_CDB6_COMMAND, * PSCSI_CDB6_COMMAND;

typedef struct PACKED _SCSI_CDB10_COMMAND{
    UINT8   OpCode;
    UINT8   ServiceActionMci;
    UINT32  Lba;
    UINT8   Mci;
    UINT16  TpaLength;
    UINT8   Control;
}SCSI_CDB10_COMMAND, * PSCSI_CDB10_COMMAND;

typedef struct PACKED _SCSI_CDB12_COMMAND{
    UINT8   OpCode;
    UINT8   ServiceActionMci;
    UINT32  Lba;
    UINT32  TpaLength;
    UINT8   Mci;
    UINT8   Control;
}SCSI_CDB12_COMMAND, * PSCSI_CDB12_COMMAND;

typedef struct PACKED _SCSI_CDB16_COMMAND{
    UINT8   OpCode;
    UINT64  Lba;
    UINT32  TpaLength;
    UINT8   Mci;
    UINT8   Control;
}SCSI_CDB16_COMMAND, * PSCSI_CDB16_COMMAND;


typedef struct PACKED _SCSI_CDBVAR_COMMAND_HEADER{
    UINT8   OpCode;
    UINT8   Control;
    UINT8   Mci[5];
    UINT8   CdbAdditionalLength;
    UINT16  ServiceAction;
}SCSI_CDBVAR_COMMAND_HEADER, * PSCSI_CDBVAR_COMMAND_HEADER;

typedef struct PACKED _SCSI_CDBVAR_COMMAND{
    SCSI_CDBVAR_COMMAND_HEADER  CommandHeader;
    UINT8                       ServiceActionData[];
}SCSI_CDBVAR_COMMAND, * PSCSI_CDBVAR_COMMAND;

typedef struct PACKED _SCSI_LONG_LBA_CDBVAR_COMMAND{
    UINT8   OpCode;
    UINT8   Control;
    UINT8   Mci[5];
    UINT8   CdbAdditionalLength;
    UINT16  ServiceAction;
    UINT8   MciFuaDpoMci;
    UINT8   Mci2;
    UINT64  Lba;
    UINT64  Mci3;
    UINT32  TpaLength;
}SCSI_LONG_LBA_CDBVAR_COMMAND, * PSCSI_LONG_LBA_CDBVAR_COMMAND;

typedef struct PACKED _SCSI_DESCRIPTOR_FORMAT_SENCE_DATA{
    UINT8   ResponceCode;
    UINT8   SenseKey;
    UINT8   Asc;
    UINT8   AscQualifier;
    UINT8   Reserved[3];
    UINT8   AditionalSenceLength;
    UINT8   SenceDataDescriptorBuffer[];
}SCSI_DESCRIPTOR_FORMAT_SENCE_DATA, * PSCSI_DESCRIPTOR_FORMAT_SENCE_DATA;

typedef struct PACKED _SCSI_SENSE_DATA_DESCRIPTOR_FORMAT{
    UINT8   DescriptorType;
    UINT8   AdditionalLength;
    UINT8   SenceDataSpecific[];
}SCSI_SENSE_DATA_DESCRIPTOR_FORMAT, * PSCSI_SENSE_DATA_DESCRIPTOR_FORMAT;

//scsi sence data descriptor
typedef struct PACKED _SSDD_INFO_STRUCTURE{
    UINT8   DescriptorType;     //SSDD_TYPE_INFO        0x00
    UINT8   AdditionalLength;   //SSDD_TYPE_INFO_SIZE   0x0A
    UINT8   ReservedValid;      //(1 << 7)
    UINT8   Reserved;
    UINT64  Information;
}SSDD_INFO_STRUCTURE, * PSSDD_INFO_STRUCTURE;

typedef struct PACKED _SSDD_COMMAND_SPECIFIC_INFO_STRUCTURE{
    UINT8   DescriptorType;     //SSDD_TYPE_COMMAND_SPECIFIC_INFO       0x01
    UINT8   AdditionalLength;   //SSDD_TYPE_COMMAND_SPECIFIC_INFO_SIZE  0x0A
    UINT8   Reserved[2];
    UINT64  Information;
}SSDD_COMMAND_SPECIFIC_INFO_STRUCTURE, * PSSDD_COMMAND_SPECIFIC_INFO_STRUCTURE;

typedef struct PACKED _SSDD_SENCE_KEY_SPECIFIC_STRUCTURE{
    UINT8   DescriptorType;     //SSDD_SENCE_KEY_SPECIFIC       0x02
    UINT8   AdditionalLength;   //SSDD_TYPE_KEY_SPECIFIC_SIZE   0x06
    UINT8   Reserved[2];
    UINT8   SenceKeySpecific[3];//[0](1 << 7)
    UINT8   Reserved2;
}SSDD_SENCE_KEY_SPECIFIC_STRUCTURE, * PSSDD_SENCE_KEY_SPECIFIC_STRUCTURE;

typedef struct PACKED _SCSI_BACKGROUND_CONTROL_COMMAND_STRUCTURE{
    UINT8   OpCode;         //SCSI_COMMAND_BACKGROUND_CONTROL           0x9E
    UINT8   ServiceAction;  //SCSI_SERVICE_ACTION_BACKGROUND_CONTROL    0x15
    UINT8   BoControl;
    UINT8   BoTime;
    UINT8   Reserved[11];
    UINT8   Control;
}SCSI_BACKGROUND_CONTROL_COMMAND_STRUCTURE, * PSCSI_BACKGROUND_CONTROL_COMMAND_STRUCTURE;

typedef struct PACKED _SCSI_CHANGE_DEFINITION_COMMAND_STRUCTURE{
    UINT8   OpCode;         //SCSI_COMMAND_CHANGE_DEFINITION 0x40
    UINT8   Reserved;       
    UINT8   Save;
    UINT8   DefParam;
    UINT8   Reserved2[4];
    UINT8   ParamLength;
    UINT8   Control;
}SCSI_CHANGE_DEFINITION_COMMAND_STRUCTURE, * PSCSI_CHANGE_DEFINITION_COMMAND_STRUCTURE;

typedef struct PACKED _SCSI_FORMAT_UNIT_COMMAND_STRUCTURE{
    UINT8   OpCode;                 //SCSI_COMMAND_FORMAT_UNIT 0x04
    UINT8   FmtInfoLlFmtDataClDfl;
    UINT8   VendorSpecific;
    UINT8   Reserved;
    UINT8   Ffmt;
    UINT8   Control;
}SCSI_FORMAT_UNIT_COMMAND_STRUCTURE, * PSCSI_FORMAT_UNIT_COMMAND_STRUCTURE;

typedef struct PACKED _SCSI_GET_LBA_STATUS_COMMAND_STRUCTURE{
    UINT8   OpCode;         //SCSI_COMMAND_GET_LBA_STATUS           0x9E
    UINT8   ServiceAction;  //SCSI_SERVICE_ACTION_GET_LBA_STATUS    0x12
    UINT64  StartingLba;
    UINT32  AllocationLength;
    UINT8   Reserved;
    UINT8   Control;
}SCSI_GET_LBA_STATUS_COMMAND_STRUCTURE, * PSCSI_GET_LBA_STATUS_COMMAND_STRUCTURE;

#define SCSI_CDBVAR_COMMAND_OPCODE                  0x7F

#define SCSI_OPCODE_GROUP_CODE_6BYTE_COMMAND        0b000
#define SCSI_OPCODE_GROUP_CODE_10_1BYTE_COMMAND     0b001
#define SCSI_OPCODE_GROUP_CODE_10_2BYTE_COMMAND     0b010
#define SCSI_OPCODE_GROUP_CODE_16_BYTE_COMMAND      0b100
#define SCSI_OPCODE_GROUP_CODE_12_BYTE_COMMAND      0b101

#define SCSI_SENSE_DATA_CURRENT_FIXED_ERROR         0x70
#define SCSI_SENSE_DATA_DEFERED_FIXED_ERROR         0x71
#define SCSI_SENSE_DATA_CURRENT_DESCRIPTOR_ERROR    0x72
#define SCSI_SENSE_DATA_DEFERED_DESCRIPTOR_ERROR    0x73

//Scsi Sence Data Descriptor 
#define SSDD_TYPE_INFO                              0x00
#define SSDD_TYPE_COMMAND_SPECIFIC_INFO             0x01
#define SSDD_SENCE_KEY_SPECIFIC                     0x02
#define SSDD_FIELD_REPLACEABLE_UNIT                 0x03
#define SSDD_STREAM_COMMANDS                        0x04
#define SSDD_BLOCK_COMMANDS                         0x05
#define SSDD_OSD_OBJECT_IDENTIFICATION              0x06
#define SSDD_OSD_RESPONSE_INTEGRITY_CHECK_VALUE     0x07
#define SSDD_OSD_ATTRIBUTE_IDENTIFICATION           0x08
#define SSDD_ATA_RETURN                             0x09
#define SSDD_ANOTHER_PROGRESS_INDICATION            0x0A

#define SSDD_TYPE_INFO_SIZE                         0x0A
#define SSDD_TYPE_COMMAND_SPECIFIC_INFO_SIZE        0x0A
#define SSDD_TYPE_KEY_SPECIFIC_SIZE                 0x06

//Page 51

#define SCSI_LONG_LBA_COMMAND_SIZE 0x18

#define SCSI_COMMAND_BACKGROUND_CONTROL         0x9E
#define SCSI_COMMAND_CHANGE_DEFINITION          0x40
#define SCSI_COMMAND_FORMAT_UNIT                0x04
#define SCSI_COMMAND_GET_LBA_STATUS             0x9E     
#define SCSI_COMMAND_GET_STREAM_STATUS          0x9E
#define SCSI_COMMAND_INQUIRY                    0x12
#define SCSI_COMMAND_LOG_SELECT                 0x4C
#define SCSI_COMMAND_LOG_SENCE                  0x4D
#define SCSI_COMMAND_MODE_SELECT_CDB6           0x15
#define SCSI_COMMAND_MODE_SELECT_CDB10          0x55
#define SCSI_COMMAND_MODE_SENCE_CDB6            0x1A
#define SCSI_COMMAND_MODE_SENCE_CDB10           0x5A
#define SCSI_COMMAND_PERSISTENT_RESERVE_IN      0x5E
#define SCSI_COMMAND_PERSISTENT_RESERVE_OUT     0x5F
#define SCSI_COMMAND_READ_CDB6                  0x08
#define SCSI_COMMAND_READ_CDB10                 0x28
#define SCSI_COMMAND_READ_CDB12                 0xA8
#define SCSI_COMMAND_READ_CDB16                 0x88
#define SCSI_COMMAND_READ_CDB32                 0x7F //0x0009
#define SCSI_COMMAND_READ_BUFFER_CDB10          0x3C
#define SCSI_COMMAND_READ_BUFFER_CDB16          0x9B
#define SCSI_COMMAND_READ_CAPACITY_CDB10        0x25
#define SCSI_COMMAND_READ_CAPACITY_CDB16        0x9E
#define SCSI_COMMAND_READ_DEFECT_DATA_CDB10     0x37
#define SCSI_COMMAND_READ_DEFECT_DATA_CDB12     0xB7
#define SCSI_COMMAND_READ_LONG_CDB10            0x3E
#define SCSI_COMMAND_READ_LONG_CDB16            0x9E
#define SCSI_COMMAND_REASIGN_BLOCKS             0x07
#define SCSI_COMMAND_RECIEVE_DIAGNOSTIC_RESULTS 0x1C
#define SCSI_COMMAND_RELEASE_CDB6               0x17
#define SCSI_COMMAND_RELEASE_CDB10              0x57
#define SCSI_COMMAND_REPORT_IDENTIFYING_INFO    0xA3
#define SCSI_COMMAND_REPORT_LUNS                0xA0
#define SCSI_COMMAND_REPORT_SUPPORTED_OPCODES   0xA3   
#define SCSI_COMMAND_REPORT_SUPPORTED_TASKMNG   0xA3      
#define SCSI_COMMAND_REPORT_TIMESTAMP           0xA3
#define SCSI_COMMAND_REQUEST_SENSE              0x03
#define SCSI_COMMAND_RESERVE_CDB6               0x16
#define SCSI_COMMAND_RESERVE_CDB10              0x56
#define SCSI_COMMAND_REZERO_UNIT                0x01
#define SCSI_COMMAND_SANITIZE                   0x48
#define SCSI_COMMAND_SECURITY_PROTOCOL_IN       0xA2
#define SCSI_COMMAND_SECURITY_PROTOCOL_OUT      0xB5
#define SCSI_COMMAND_SEEK_CDB6                  0x0B
#define SCSI_COMMAND_SEEK_EXTENDED_CDB10        0x2B
#define SCSI_COMMAND_SEND_DIAGNOSTIC            0x1D
#define SCSI_COMMAND_SET_IDENTIFYING_INFO       0xA4
#define SCSI_COMMAND_SET_TIMESTAMP              0xA4
#define SCSI_COMMAND_START_STOP_UNIT            0x1B
#define SCSI_COMMAND_STREAM_CONTROL             0x9E
#define SCSI_COMMAND_SYNCHRONIZE_CACHE_CDB10    0x35
#define SCSI_COMMAND_SYNCHRONIZE_CACHE_CDB16    0x91
#define SCSI_COMMAND_TEST_UNIT_READY            0x00
#define SCSI_COMMAND_UNMAP                      0x42
#define SCSI_COMMAND_VERIFY_CDB10               0x2F
#define SCSI_COMMAND_VERIFY_CDB12               0xAF
#define SCSI_COMMAND_VERIFY_CDB16               0x8F
#define SCSI_COMMAND_VERIFY_CDB32               0x7F
#define SCSI_COMMAND_WRITE_CDB6                 0x0A
#define SCSI_COMMAND_WRITE_CDB10                0x2A
#define SCSI_COMMAND_WRITE_CDB12                0xAA
#define SCSI_COMMAND_WRITE_CDB16                0x8A
#define SCSI_COMMAND_WRITE_CDB32                0x7F               
#define SCSI_COMMAND_WRITE_AND_VERIFY_CDB10     0x2E
#define SCSI_COMMAND_WRITE_AND_VERIFY_CDB12     0xAE
#define SCSI_COMMAND_WRITE_AND_VERIFY_CDB16     0x8E
#define SCSI_COMMAND_WRITE_AND_VERIFY_CDB32     0x7F
#define SCSI_COMMAND_WRITE_ATOMIC_CDB16         0x9C
#define SCSI_COMMAND_WRITE_ATOMIC_CDB32         0x7F
#define SCSI_COMMAND_WRITE_BUFFER               0x3B
#define SCSI_COMMAND_WRITE_LONG                 0x3F
#define SCSI_COMMAND_WRITE_LONG_CDB16           0x9F
#define SCSI_COMMAND_WRITE_SAME_CDB10           0x41
#define SCSI_COMMAND_WRITE_SAME_CDB16           0x93
#define SCSI_COMMAND_WRITE_SAME_CDB32           0x7F
#define SCSI_COMMAND_WRITE_STREAM_CDB16         0x9A
#define SCSI_COMMAND_WRITE_STREAM_CDB32         0x7F

#define SCSI_SERVICE_ACTION_BACKGROUND_CONTROL          0x0015
#define SCSI_SERVICE_ACTION_GET_LBA_STATUS              0x0012
#define SCSI_SERVICE_ACTION_GET_STREAM_STATUS           0x0016
#define SCSI_SERVICE_ACTION_READ_CDB32                  0x0009
#define SCSI_SERVICE_ACTION_READ_CAPACITY_CDB16         0x0010
#define SCSI_SERVICE_ACTION_READ_LONG16                 0x0011
#define SCSI_SERVICE_ACTION_IDENTIFYING_INFORMATION     0x0005
#define SCSI_SERVICE_ACTION_REPORT_SUPPORTED_OPCODES    0x000C
#define SCSI_SERVICE_ACTION_REPORT_SUPPORTED_TASKMNG    0x000D
#define SCSI_SERVICE_ACTION_REPORT_TIMESTAMP            0x000F
#define SCSI_SERVICE_ACTION_SET_IDENTIFYING_INFORMATION 0x0006
#define SCSI_SERVICE_ACTION_SET_TIMESTAMP               0x000F
#define SCSI_SERVICE_ACTION_STREAM_CONTROL              0x0014
#define SCSI_SERVICE_ACTION_VERIFY_CDB32                0x000A
#define SCSI_SERVICE_ACTION_WRITE_CDB32                 0x000B
#define SCSI_SERVICE_ACTION_WRITE_AND_VERIFY_CDB32      0x000C
#define SCSI_SERVICE_ACTION_WRITE_ATOMIC_CDB32          0x0018
#define SCSI_SERVICE_ACTION_WRITE_LONG_CDB15            0x0011
#define SCSI_SERVICE_ACTION_WRITE_SAME_CDB32            0x000D

#define SCSI_BO_CONTROL_NO_CHANGE   0
#define SCSI_BO_CONTROL_START_OP    1
#define SCSI_BO_CONTROL_STOP_OP     2

#define SCSI_BO_TIME_NO_LIMIT       0

#define SCSI_CHGDEF_SAVE            1

#define SCSI_CHGDEF_DEFPARAM_CURRENT_OPDEF              0x00
#define SCSI_CHGDEF_DEFPARAM_SCSI2_OPDEF                0x03
#define SCSI_CHGDEF_DEFPARAM_SCSI3_OPDEF                0x04
#define SCSI_CHGDEF_DEFPARAM_MANUFACTURE_OPDEF          0x3F



LOUSTATUS ScsiCoreGetInfoSenceDataInformation(PSSDD_INFO_STRUCTURE SenceData, UINT64* Out);
LOUSTATUS ScsiCoreGetCommandSpecificInfoSenceDataInformation(PSSDD_COMMAND_SPECIFIC_INFO_STRUCTURE SenceData, UINT64* Out);
LOUSTATUS ScsiCoreEncodeOpCode(UINT8* Out, UINT8 CommandCode, UINT8 GroupCode);
LOUSTATUS ScsiCoreEncodeControl(UINT8* Out, UINT8 VendorSpecific, UINT8 Reserved, UINT8 Naca, UINT8 Obsolete1, UINT8 Obsolete0);
void ScsiCoreEncodeCdb6Command(PSCSI_CDB6_COMMAND Cdb, UINT8 OpCode, UINT8 MsbMci, UINT16 Lba, UINT8 TpaLength, UINT8 Control);
void ScsiCoreEncodeCdb10Command(PSCSI_CDB10_COMMAND Cdb, UINT8 OpCode, UINT8 ServiceActionMci, UINT32 Lba, UINT8 Mci, UINT16 TpaLength, UINT8 Control);
void ScsiCoreEncodeCdb12Command(PSCSI_CDB12_COMMAND Cdb, UINT8 OpCode, UINT8 ServiceActionMci, UINT32 Lba, UINT32 TpaLength, UINT8 Mci, UINT8 Control);
void ScsiCoreEncodeCdb16Command(PSCSI_CDB16_COMMAND Cdb, UINT8 OpCode, UINT64 Lba, UINT32 TpaLength, UINT8 Mci, UINT8 Control);
void ScsiCoreEncodeLongLbaCdbVar(PSCSI_LONG_LBA_CDBVAR_COMMAND Cdb, UINT8 Control, UINT8 Mci[5], UINT8 CdbAdditionalLength, UINT16 ServiceAction, UINT8 MciFuaDpoMci, UINT8 Mci2, UINT64 Lba, UINT64 Mci3, UINT32 TpaLength);
void ScsiCoreEncodeBackgroundControlCommand(PSCSI_BACKGROUND_CONTROL_COMMAND_STRUCTURE Cdb, UINT8 BoControl, UINT8 BoTime, UINT8 Control);
void ScsiCoreEncodeChangeDefinitionCommand(PSCSI_CHANGE_DEFINITION_COMMAND_STRUCTURE Cdb, UINT8 Save, UINT8 DefParam, UINT8 ParamLength, UINT8 Control);
void ScsiCoreEncodeGetLbaStatusCommand(PSCSI_GET_LBA_STATUS_COMMAND_STRUCTURE Cdb, UINT64 StartingLba, UINT32 AllocationLength, UINT8 Reserved, UINT8 Control);


#endif