#ifndef _SVGA_REGISTERS_H
#define _SVGA_REGISTERS_H

#include "VmBasicTypes.h"

typedef enum {
    SVGA_REGISTER_ENABLE_DISABLE = 0
    SVGA_REGISTER_ENABLE_ENABLE = (1 << 0)
    SVGA_REGISTER_ENABLE_HIDE = (1 << 1)
}SVGA_REGISTER_ENABLE;

typedef uint32_t SVGA_MOB_ID;

#define SVGA_MAX_X_RESOLUTION   2560
#define SVGA_MAX_Y_RESOLUTION   1600
#define SVGA_MAX_BPP            32
#define SVGA_MAX_DEPTH          24
#define SVGA_MAX_DISPLAYS       10
#define SVGA_MAX_SCREEN_AREA    8192 //8192 * 4 = 32MB Per Screens
#define SVGA_SCREEN_ROOT_LIMIT  (SVGA_MAX_SCREEN_AREA * SVGA_MAX_DISPLAYS)


#endif