

all:
	$(MAKE) -C louoskrnl all
	$(MAKE) -C LouDDK all
	$(MAKE) -C LCC all
	$(MAKE) -C wprecorder all
	$(MAKE) -C Ps2IO all
	$(MAKE) -C Dma16 all


clean:
	$(MAKE) -C louoskrnl clean
	$(MAKE) -C LouDDK clean
	$(MAKE) -C LCC clean
	$(MAKE) -C wprecorder clean
	$(MAKE) -C Ps2IO clean
	$(MAKE) -C Dma16 clean
