#ifndef _SMBIOS_H
#define _SMBIOS_H
#ifndef __cplusplus
#include <LouAPI.h>
#else
#include <LouDDK.h>
extern "C" {
#endif

#ifndef _GUID_TYPE
#define _GUID_TYPE
typedef struct _GUID {
	unsigned char DataByte[16];
} GUID,* LPGUID, UUID, * PGUID, * PUUID;
#endif

//For Anyone Intrested https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.8.0.pdf 

typedef struct PACKED _SMBIOS_ENTRY_2_32{
    #define     SMBIOS32_ANCHOR_STRING "_SM_"
    UINT8       AnchorString[4];
    UINT8       Checksum;
    UINT8       Length;
    UINT8       MajorVersion;
    UINT8       MinorVersion;
    UINT16      MaxStructureSize;
    UINT8       EntryRevision;
    UINT8       FormatedArea[5];
    UINT8       IntermidAchorString[5];
    UINT8       IntermedChecksum;
    UINT16      TableLength;
    UINT32      TableAddress;
    UINT16      StructureCount;
    UINT8       BcdRevision;
}SMBIOS_ENTRY_2_32, * PSMBIOS_ENTRY_2_32;

typedef struct PACKED _SMBIOS_ENTRY_3_64{
    #define     SMBIOS64_ANCHOR_STRING "_SM3_"
    UINT8       AnchorString[5];
    UINT8       Checksum;
    UINT8       Length;
    UINT8       MajorVersion;
    UINT8       MinorVersion;
    UINT8       Docrev;
    UINT8       EntryRevision;
    UINT8       Reserved;
    UINT32      MaxSize;
    UINT64      TableAddress;
}SMBIOS_ENTRY_3_64, * PSMBIOS_ENTRY_3_64;

typedef struct PACKED _SMBIOS_HEADER{
    UINT8       Type;
    UINT8       Length;
    UINT16      Handle;
}SMBIOS_HEADER, * PSMBIOS_HEADER;

#define SMBIOS_TYPE_FIRMWAE_INFORMATION             0
#define SMBIOS_TYPE_SYSTEM_INFORMATION              1
#define SMBIOS_TYPE_SYSTEM_ENCLOSURE                3
#define SMBIOS_TYPE_PROCESSOR_INFORMATION           4
#define SMBIOS_TYPE_CACHE_INFORMATION               7
#define SMBIOS_TYPE_SYSTEM_SLOT                     9
#define SMBIOS_TYPE_PHYSICAL_MEMORY_ARRAY           16
#define SMBIOS_TYPE_MEMORY_DEVICE                   17
#define SMBIOS_TYPE_MEMORY_ARRAY_MAPPED_ADDRESS     19
#define SMBIOS_TYPE_SYSTEM_BOOT_INFORMATION         32


typedef struct PACKED _SMBIOS_FIRMWARE_INFORMATION{
    //2.0+ Structure Data
    SMBIOS_HEADER   Header;
    UINT8           Vendor;
    UINT8           FirmwareVersion;
    UINT16          BIOSStartingAddress;
    UINT8           FirmwareReleaseData;
    UINT8           FirmwareROMSize;
    UINT64          FirmwareCharecteristics;
    //2.4+ Structure Data
    UINT8           ExtendedCharecterisics[0x14 - 0x12]; //charecteristics extnetion exist from 0x12 to 0x14
    UINT8           FirmwareMajorRelease;
    UINT8           FirmwareMinorRelease;
    UINT8           EcFirmwareMajorRelease;
    UINT8           EcFirmwareMinorRelease;
    //3.1+ Structure Data
    UINT16          ExtendedFirmwareRomSize;           
}SMBIOS_FIRMWARE_INFORMATION, * PSMBIOS_FIRMWARE_INFORMATION; 

#define FW_INFO_CHARIST_UNKNOWN                         (1ULL << 2)
#define FW_INFO_CHARIST_NOT_SUPPORTED                   (1ULL << 3)
#define FW_INFO_CHARIST_ISA_SUPPORTED                   (1ULL << 4)
#define FW_INFO_CHARIST_MCA_SUPPORTED                   (1ULL << 5)
#define FW_INFO_CHARIST_EISA_SUPPORTED                  (1ULL << 6)
#define FW_INFO_CHARIST_PCI_SUPPORTED                   (1ULL << 7)
#define FW_INFO_CHARIST_PCMCIA_SUPPORTED                (1ULL << 8)           
#define FW_INFO_CHARIST_PLUGNPLAY_SUPPORTED             (1ULL << 9)
#define FW_INFO_CHARIST_APM_SUPPORTED                   (1ULL << 10)
#define FW_INFO_CHARIST_FLASH_SUPPORT                   (1ULL << 11)
#define FW_INFO_CHARIST_SHADOWING_SUPPORTED             (1ULL << 12)
#define FW_INFO_CHARIST_VL_VESA_SUPPORTED               (1ULL << 13)
#define FW_INFO_CHARIST_ESCD_SUPPORTED                  (1ULL << 14)
#define FW_INFO_CHARIST_CD_BOOT_SUPPORTED               (1ULL << 15)
#define FW_INFO_CHARIST_SELECT_BOOT_SUPPORTED           (1ULL << 16)
#define FW_INFO_CHARIST_PLCC_OR_SOP_SUPPORTED           (1ULL << 17)
#define FW_INFO_CHARIST_PCMCIA_BOOT_SUPPORTED           (1ULL << 18)
#define FW_INFO_CHARIST_EDD_SUPPORTED                   (1ULL << 19)
#define FW_INFO_CHARIST_INT13_JF1_SUPPORTED             (1ULL << 20)
#define FW_INFO_CHARIST_INT13_JF2_SUPPORTED             (1ULL << 21)
#define FW_INFO_CHARIST_INT13_525_360K_SUPPORTED        (1ULL << 22)
#define FW_INFO_CHARIST_INT13_525_12MB_SUPPORTED        (1ULL << 23)
#define FW_INFO_CHARIST_INT13_35_720KB_SUPPORTED        (1ULL << 24)
#define FW_INFO_CHARIST_INT13_35_288MB_SUPPORTED        (1ULL << 25)
#define FW_INFO_CHARIST_INT5_PRINT_SUPPORTED            (1ULL << 26)
#define FW_INFO_CHARIST_INT9_8042_KEYBOARD_SUPPORTED    (1ULL << 27)
#define FW_INFO_CHARIST_INT14_SERIAL_SERVICE_SUPPORTED  (1ULL << 28)
#define FW_INFO_CHARIST_INT17_PRINTER_SERVICE_SUPPORTED (1ULL << 29)
#define FW_INFO_CHARIST_INT10_CGA_SERVICES_SUPPORTED    (1ULL << 30)
#define FW_INFO_CHARIST_NEC_PC_98_SUPPORTED             (1ULL << 31)

//Byte 1
#define FW_EXT_CHARIST_ACPI_SUPPORTED                   (1)
#define FW_EXT_CHARIST_LEGACY_USB_SUPPORTED             (1 << 1)
#define FW_EXT_CHARIST_AGP_SUPPORTED                    (1 << 2)
#define FW_EXT_CHARIST_I2O_BOOT_SUPPORTED               (1 << 3)
#define FW_EXT_CHARIST_LS_120_SUPER_DISK_SUPPORTED      (1 << 4)
#define FW_EXT_CHARIST_ATAPI_ZIP_SUPPORTED              (1 << 5)
#define FW_EXT_CHARIST_1394_BOOT_SUPPORTED              (1 << 5)
#define FW_EXT_CHARIST_SMART_BATTERY_SUPPORTED          (1 << 6)

//Byte 2
#define FW_EXT_CHARIST_BIOS_BOOT_SUPPORTED              (1)
#define FW_EXT_CHARIST_NETWORK_BOOT_SUPPORTED           (1 << 1)
#define FW_EXT_CHARIST_ENABLE_TARGETED_CONTENT          (1 << 2)
#define FW_EXT_CHARIST_UEFI_SPECIFICATION_SUPPORTED     (1 << 3)
#define FW_EXT_CHARIST_SMBIOS_VIRTUAL_MACHINE           (1 << 4)
#define FW_EXT_CHARIST_MANUFACURING_MODE_SUPPORTED      (1 << 5)
#define FW_EXT_CHARIST_MANUFACURING_MODE_ENABLED        (1 << 6)

typedef struct PACKED _SMBIOS_SYSTEM_INFORMATION{
    //2.0+ Structure Data
    SMBIOS_HEADER           Header;
    UINT8                   Manufacturer;
    UINT8                   ProductName;
    UINT8                   Version;
    UINT8                   SerialNumber;
    //2.1+ Structure Data
    GUID                    Uuid;
    UINT8                   WakeUpType;
    //2.4+ Structure Data
    UINT8                   SkuNumber;
    UINT8                   Family;
}SMBIOS_SYSTEM_INFORMATION, * PSMBIOS_SYSTEM_INFORMATION;

#define SYSTEM_INFO_WAKEUP_TYPE_OTHER           0x01
#define SYSTEM_INFO_WAKEUP_TYPE_UNKOWN          0x02
#define SYSTEM_INFO_WAKEUP_TYPE_APM_TIMER       0x03
#define SYSTEM_INFO_WAKEUP_TYPE_MODEM_RING      0x04
#define SYSTEM_INFO_WAKEUP_TYPE_LAN_REMOTE      0x05
#define SYSTEM_INFO_WAKEUP_TYPE_POWER_SWITCH    0x06
#define SYSTEM_INFO_WAKEUP_TYPE_PCI_PME         0x07
#define SYSTEM_INFO_WAKEUP_TYPE_AC_POWER_REST   0x08

typedef struct PACKED _SMBIOS_BASEBOARD_INFORMATION{
    SMBIOS_HEADER           Header;
    UINT8                   Manufacturer;
    UINT8                   Product;
    UINT8                   Version;
    UINT8                   SerialNumber;
    UINT8                   AssetTag;
    UINT8                   FeatureFlags;
    UINT8                   LocationInChassis;
    UINT16                  ChasisHandle;
    UINT8                   BoardType;
    UINT8                   ContainedObjectCount;
    UINT16                  ContainedObjectHandles[];
}SMBIOS_BASEBOARD_INFORMATION, * PSMBIOS_BASEBOARD_INFORMATION;

typedef struct _SMBIOS_BASEBOARD_FEATURE_FLAGS{
    UINT8                   HoastingBoard   : 1;
    UINT8                   HasDaughter     : 1;
    UINT8                   BoardRemoveable : 1;
    UINT8                   BoardReplaceable: 1;
    UINT8                   BoardHotswapable: 1;
    UINT8                   Reserved        : 3;
}SMBIOS_BASEBOARD_FEATURE_FLAGS, * PSMBIOS_BASEBOARD_FEATURE_FLAGS;

#define SMBIOS_BASEBOARD_TYPE_UNKOWN                    0x01
#define SMBIOS_BASEBOARD_TYPE_OTHER                     0x02
#define SMBIOS_BASEBOARD_TYPE_SERVER_BLADE              0x03
#define SMBIOS_BASEBOARD_TYPE_CONNECTIVITY_SWITCH       0x04
#define SMBIOS_BASEBOARD_TYPE_SYSTEM_MANAGERMENT_MODULE 0x05
#define SMBIOS_BASEBOARD_TYPE_PROCESSOR_MODULE          0x06
#define SMBIOS_BASEBOARD_TYPE_IO_MODULE                 0x07
#define SMBIOS_BASEBOARD_TYPE_MEMORY_MODULE             0x08
#define SMBIOS_BASEBOARD_TYPE_DAUGHTER_BOARD            0x09
#define SMBIOS_BASEBOARD_TYPE_MOTHERBOARD               0x0A
#define SMBIOS_BASEBOARD_TYPE_PROCESSOR_MEMORY_MODULE   0x0B
#define SMBIOS_BASEBOARD_TYPE_PROCESSOR_IO_MODULE       0x0C
#define SMBIOS_BASEBOARD_TYPE_INTERCONNECT_BOARD        0x0D

typedef struct PACKED _SMBIOS_SYSTEM_ENCLOSURE{
    SMBIOS_HEADER           Header;
    //2.0+ Structure Data
    UINT8                   Manufacturer;
    UINT8                   Type;
    UINT8                   Version;
    UINT8                   SerialNumber;
    UINT8                   AssetTagNumber;
    //2.1+ Structure Data
    UINT8                   BootupState;
    UINT8                   PowerSupplyState;
    UINT8                   ThermalState;
    UINT8                   SecurityState;
    //2.3+ Structure Data
    UINT32                  OemSpecific;
    UINT8                   Height;
    UINT8                   PowerChordCount;
    UINT8                   ContainedElementCount;
    UINT8                   ContainedRecordLength;
    #define                 SYSTEM_ENCLOSURE_SKU_NUMBER(Count, Length) (0x15 + ((Count) * (Length)))
    UINT8                   ContainedData[];
}SMBIOS_SYSTEM_ENCLOSURE, * PSMBIOS_SYSTEM_ENCLOSURE;

#define SYSTEM_ENCLOSURE_TYPE_OTHER                     0x01
#define SYSTEM_ENCLOSURE_TYPE_UNKOWN                    0x02
#define SYSTEM_ENCLOSURE_TYPE_DESKTOP                   0x03
#define SYSTEM_ENCLOSURE_TYPE_LOW_PROFILE_DESKTOP       0x04
#define SYSTEM_ENCLOSURE_TYPE_PIZZA_BOX                 0x05
#define SYSTEM_ENCLOSURE_TYPE_MINI_TOWER                0x06
#define SYSTEM_ENCLOSURE_TYPE_TOWER                     0x07
#define SYSTEM_ENCLOSURE_TYPE_PORTABLE                  0x08
#define SYSTEM_ENCLOSURE_TYPE_LAPTOP                    0x09
#define SYSTEM_ENCLOSURE_TYPE_NOTEBOOK                  0x0A
#define SYSTEM_ENCLOSURE_TYPE_HANDHELD                  0x0B
#define SYSTEM_ENCLOSURE_TYPE_DOCKING_STATION           0x0C
#define SYSTEM_ENCLOSURE_TYPE_ALL_IN_ONE                0x0D
#define SYSTEM_ENCLOSURE_TYPE_SUB_NOTEBOOK              0x0E
#define SYSTEM_ENCLOSURE_TYPE_SPACE_SAVING              0x0F
#define SYSTEM_ENCLOSURE_TYPE_LUNCH_BOX                 0x10
#define SYSTEM_ENCLOSURE_TYPE_MAIN_SERVER_CHASSIS       0x11
#define SYSTEM_ENCLOSURE_TYPE_EXPANSION_CHASSIS         0x12
#define SYSTEM_ENCLOSURE_TYPE_SUB_CHASSIS               0x13
#define SYSTEM_ENCLOSURE_TYPE_BUS_EXSPANSION_CHASSIS    0x14
#define SYSTEM_ENCLOSURE_TYPE_PERIPHERAL_CHASSIS        0x15
#define SYSTEM_ENCLOSURE_TYPE_RAID_CHASSIS              0x16
#define SYSTEM_ENCLOSURE_TYPE_RACK_MOUNT_CHASSIS        0x17
#define SYSTEM_ENCLOSURE_TYPE_SEALED_PC_CASE            0x18
#define SYSTEM_ENCLOSURE_TYPE_MULTI_SYSTEM_CHASSIS      0x19
#define SYSTEM_ENCLOSURE_TYPE_COMPACT_PCI               0x1A
#define SYSTEM_ENCLOSURE_TYPE_ADVANCED_TCA              0x1B
#define SYSTEM_ENCLOSURE_TYPE_BLADE                     0x1C
#define SYSTEM_ENCLOSURE_TYPE_BLADE_ENCLOSURE           0x1D
#define SYSTEM_ENCLOSURE_TYPE_TABLET                    0x1E
#define SYSTEM_ENCLOSURE_TYPE_CONVERTIBLE               0x1F
#define SYSTEM_ENCLOSURE_TYPE_DETACHEABLE               0x20
#define SYSTEM_ENCLOSURE_TYPE_IOT_GATEWAY               0x21
#define SYSTEM_ENCLOSURE_TYPE_EMBEDDED_PC               0x22
#define SYSTEM_ENCLOSURE_TYPE_MINI_PC                   0x23
#define SYSTEM_ENCLOSURE_TYPE_STICK_PC                  0x24

#define SYSTEM_ENCLOSURE_STATE_OTHER                    0x01
#define SYSTEM_ENCLOSURE_STATE_UNKOWN                   0x02
#define SYSTEM_ENCLOSURE_STATE_SAFE                     0x03
#define SYSTEM_ENCLOSURE_STATE_WARNING                  0x04
#define SYSTEM_ENCLOSURE_STATE_CRITICAL                 0x05
#define SYSTEM_ENCLOSURE_STATE_NON_RECOVERABLE          0x06

//System Enclosure Security Status/SESS
#define SESS_OTHER                                      0x01     
#define SESS_UNKOWN                                     0x02
#define SESS_NONE                                       0x03
#define SESS_EXTERNAL_INTEFACE_LOCKOUT                  0x04
#define SESS_EXTERNAL_INTERFACE_ENABLED                 0x05

typedef struct PACKED _SMBIOS_SYSTEM_ENCLOSURE_CONTAINED_ELEMENTS{
    UINT8   ContainedElementType;
    UINT8   ContainedElementMinimum;
    UINT8   ContainedElementMaximum;
}SMBIOS_SYSTEM_ENCLOSURE_CONTAINED_ELEMENTS, * PSMBIOS_SYSTEM_ENCLOSURE_CONTAINED_ELEMENTS;

typedef struct PACKED _SMBIOS_PROCESSOR_INFORMATION{
    SMBIOS_HEADER       Header;
    UINT8               SocketDesignation;
    UINT8               ProcessorType;
    UINT8               ProcessorFamily;
    UINT8               ProcessorManufacturer;
    UINT64              ProcessorID;
    UINT8               ProcessorVersion;
    UINT8               Voltage;
    UINT16              ExternalClock;
    UINT16              MaxSpeed;
    UINT16              CurrentSpeed;
    UINT8               Status;
    UINT8               ProcessorUpgrade;
    UINT16              L1CacheHandle;
    UINT16              L2CacheHandle;
    UINT16              L3CacheHandle;
    UINT8               SerialNumber;
    UINT8               AssetTag;
    UINT8               PartNumber;
    UINT8               CoreCount;
    UINT8               CoreEnabled;
    UINT8               ThreadCount;
    UINT16              ProcessorCharecteristics;
    UINT16              ProcessorFamily2;
    UINT16              CoreCount2;
    UINT16              CoreEnabled2;
    UINT16              ThreadCount2;
    UINT16              ThreadEnabled2;
    UINT8               SocketType;
}SMBIOS_PROCESSOR_INFORMATION, * PSMBIOS_PROCESSOR_INFORMATION;

#define PROCESSOR_INFO_PROCESSOR_TYPE_OTHER         0x01
#define PROCESSOR_INFO_PROCESSOR_TYPE_UKNOWN        0x02
#define PROCESSOR_INFO_PROCESSOR_TYPE_CENTERAL      0x03
#define PROCESSOR_INFO_PROCESSOR_TYPE_MATH          0x04
#define PROCESSOR_INFO_PROCESSOR_TYPE_DSP           0x05
#define PROCESSOR_INFO_PROCESSOR_TYPE_VIDEO         0x06

#define PROCESSOR_INFO_PROCESSOR_FAMILY_OTHER                       0x01
#define PROCESSOR_INFO_PROCESSOR_FAMILY_UNKOWN                      0x02
#define PROCESSOR_INFO_PROCESSOR_FAMILY_8086                        0x03
#define PROCESSOR_INFO_PROCESSOR_FAMILY_80286                       0x04
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_386                   0x05
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_486                   0x06
#define PROCESSOR_INFO_PROCESSOR_FAMILY_8087                        0x07
#define PROCESSOR_INFO_PROCESSOR_FAMILY_80287                       0x08
#define PROCESSOR_INFO_PROCESSOR_FAMILY_80387                       0x09
#define PROCESSOR_INFO_PROCESSOR_FAMILY_80487                       0x0A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM                     0x0B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_PRO                 0x0C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_II                  0x0D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_MMX                 0x0E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_CELERON                     0x0F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_XEON                0x10
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_III                 0x11
#define PROCESSOR_INFO_PROCESSOR_FAMILY_M1_FAMILY                   0x12
#define PROCESSOR_INFO_PROCESSOR_FAMILY_M2_FAMILY                   0x13
#define PROCESSOR_INFO_PROCESSOR_FAMILY_CELERON_M                   0x14
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_4_HT                0x15
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL                       0x16
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_DURON                   0x18
#define PROCESSOR_INFO_PROCESSOR_FAMILY_K5                          0x19
#define PROCESSOR_INFO_PROCESSOR_FAMILY_K6                          0x1A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_K6_2                        0x1B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_K6_3                        0x1C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON                 0x1D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD29000                    0x1E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_K6_2_P                      0x1F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC                    0x20
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_601                0x21
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_603                0x22
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_603_P              0x23
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_604                0x24
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_620                0x25
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_X704               0x26
#define PROCESSOR_INFO_PROCESSOR_FAMILY_POWER_PC_750                0x27
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_DUO              0x28  
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_DUO_MOBILE       0x29
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_SOLO_MOBILE      0x2A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_ATOM             0x2B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_M                0x2C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_M3               0x2D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_M5               0x2E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_M7               0x2F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA                       0x30
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21064                 0x31
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21066                 0x32
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21164                 0x33
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21164PC               0x34
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21164A                0x35
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21264                 0x36
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ALPHA_21364                 0x37
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_II_UDC_MOBILE_M  0x38
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_II_DC_MOBILE_M   0x39
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_II_DC_M          0x3A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_6100_SERIES             0x3B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_4100_SERIES             0x3C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_6200_SERIES             0x3D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_4200_SERIES             0x3E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_FX_SERIES               0x3F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS                        0x40 //LONG LIVE THE SONY PLAYSTATION
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS_R4000                  0x41
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS_R4200                  0x42
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS_R4400                  0x43
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS_R4600                  0x44
//RIP SONY PLAYSTATION 2
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MIPS_R10000                 0x45                 
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_C_SERIES                0x46
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_E_SERIES                0x47
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_A_SERIES                0x48
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_G_SERIES                0x49
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_Z_SERIES                0x4A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_R_SERIES                0x4B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_4300_SERIES             0x4C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_6300_SERIES             0x4D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_3300_SERIES             0x4E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_FIREPRO_SERIES          0x4F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_SPARC                       0x50
#define PROCESSOR_INFO_PROCESSOR_FAMILY_SUPER_SPARC                 0x51
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MICRP_SPARC_II              0x52
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MICRP_SPARC_II_EP           0x53
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ULTRA_SPARC                 0x54
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ULTRA_SPARC_II              0x55
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ULTRA_SPARC_III             0x56
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ULTRA_SPARC_III_2           0x57
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ULTRA_SPARC_IIII            0x58
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68040                       0x60
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68XXX                       0x61
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68000                       0x62
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68010                       0x63
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68020                       0x64
#define PROCESSOR_INFO_PROCESSOR_FAMILY_68030                       0x65
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_X4_QC           0x66
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_X1000_SERIES            0x67
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_X2000_SERIES            0x68
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_OPTERON_A_SERIES        0x69
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_X3000_SERIES            0x6A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ZEN_SERIES              0x6B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_HOBBIT                      0x70 //hope this processor is better than the movie was
#define PROCESSOR_INFO_PROCESSOR_FAMILY_CRUSOE_TM5000               0x78
#define PROCESSOR_INFO_PROCESSOR_FAMILY_CRUSOE_TM3000               0x79
#define PROCESSOR_INFO_PROCESSOR_FAMILY_EFFICEON_TM8000             0x7A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_WEITEK                      0x7B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ITANIUM                     0x82
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_X64             0x83
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_OPTERON                 0x84
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_SEMPRON                 0x85
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION                  0x86
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DUAL_CORE_AMD               0x87
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHLON_64_X2_DC         0x88
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_64_X2_MOBILE     0x89
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QUAD_CORE_AMD               0x8A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_OPTERON_3RD_GEN         0x8B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_PHENOM_FX_QC            0x8C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_PHENOM_X4_QC            0x8D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_PHENOM_X2_DC            0x8E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHLON_X2_DC            0x8F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC                     0x90
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_8500                0x91
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_8000                0x92
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_7300LC              0x93
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_7200                0x94
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_7100LC              0x95
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PA_RISC_7100                0x96
#define PROCESSOR_INFO_PROCESSOR_FAMILY_V30                         0xA0
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_3200_QC          0xA1
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_3000_DC          0xA2
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_5300_QC          0xA3
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_5100_DC          0xA4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_5000_DC          0xA5
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_LV               0xA6
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_ULV              0xA7
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_7100_SERIES      0xA8
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_5400_SERIES      0xA9
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QUAD_CORE_INTEL_XEON        0xAA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_5200_SERIES      0xAB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_7200_SERIES      0xAC
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_7300_SERIES      0xAD
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_7400_SERIES      0xAE
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MULTI_XEON_7400_SERIES      0xAF
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_III_XEON            0xB0
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_III_SPEED_STEP      0xB1
//#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_4_HT                0xB2
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON                  0xB3
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AS400                       0xB4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_MP               0xB5
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_XP              0xB6
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_MP              0xB7
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ITANIUM_2               0xB8
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_M                   0xB9
#define PROCESSOR_INFO_PROCESSOR_FAMILY_CELERON_D                   0xBA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_D                   0xBB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_PENTIUM_EXTREME             0xBC
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_SOLO             0xBD
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_DUO            0xBF
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_SOLO           0xC0
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME        0xC1
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_QUAD           0xC2
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_EXTREME_MOBILE 0xC3
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_DUO_MOBILE     0xC4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_2_SOLO_MOBILE    0xC5
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_I7               0xC6
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_DUAL_CORE             0xC7
#define PROCESSOR_INFO_PROCESSOR_FAMILY_IBM390                      0xC8
#define PROCESSOR_INFO_PROCESSOR_FAMILY_G4                          0xC9
#define PROCESSOR_INFO_PROCESSOR_FAMILY_G5                          0xCA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ESA390_G6                   0xCB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_Z_BASE                      0xCC
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_I5               0xCD
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_I3               0xCE
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_I9               0xCF
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_XEON_D                0xD0
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIA_C7_M                    0xD2
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIA_C7_D                    0xD3
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIA_C7                      0xD4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIA_EDEN                    0xD5
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MULTI_CORE_XEON             0xD6
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DUAL_CORE_XEON_3XXX         0xD7
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QUAD_CORE_XEON_3XXX         0xD8
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIA_NANO                    0xD9
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DUAL_CORE_XEON_5XXX         0xDA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QUAD_CORE_XEON_5XXX         0xDB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DUAL_CORE_XEON_7XXX         0xDC
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QUAD_CORE_XEON_7XXX         0xDE
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MULTI_CORE_XEON_7XXX        0xDF
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MUTLI_CORE_XEON_3400        0xE0
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_OPTERON_3000_SERIES     0xE4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_SEMPRON_II_PROCESSOR    0xE5
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_EMB_OPTERON_QUAD_CORE   0xE6
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_PHENOM_TRIPLE_CORE      0xE7
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_UDC_MOBILE       0xE8
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_TURION_DC_MOBILE        0xE9
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_DUAL_CORE       0xEA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_SEMPRON_SI              0xEB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_PHENOM_II               0xEC
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_ATHOLON_II              0xED
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_SIX_CORE                0xEE
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMD_SEMPRON_M               0xEF
#define PROCESSOR_INFO_PROCESSOR_FAMILY_I860                        0xFA
#define PROCESSOR_INFO_PROCESSOR_FAMILY_I960                        0xFB
#define PROCESSOR_INFO_PROCESSOR_FAMILY_EXTENDED_FAMILY             0xFE
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ARM_V7                      0x100
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ARM_V8                      0x101
#define PROCESSOR_INFO_PROCESSOR_FAMILY_AMR_V9                      0x102
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ARM_RESERVED                0x103
#define PROCESSOR_INFO_PROCESSOR_FAMILY_SH3                         0x104
#define PROCESSOR_INFO_PROCESSOR_FAMILY_SH4                         0x105
#define PROCESSOR_INFO_PROCESSOR_FAMILY_ARM                         0x118
#define PROCESSOR_INFO_PROCESSOR_FAMILY_STRONG_ARM                  0x119
#define PROCESSOR_INFO_PROCESSOR_FAMILY_6X86                        0x12C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MEDIA_GX                    0x12D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MII                         0x12E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_WIN_CHIP                    0x140
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DSP                         0x15E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_VIDEO_PROCESSOR             0x1F4
#define PROCESSOR_INFO_PROCESSOR_FAMILY_RISCV_RV32                  0x200
#define PROCESSOR_INFO_PROCESSOR_FAMILY_RISCV_RV64                  0x201
#define PROCESSOR_INFO_PROCESSOR_FAMILY_RISCV_RV128                 0x202
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONG_ARCH                  0x258
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_1                 0x259
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_2                 0x25A
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3                 0x25B
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_2K                0x25C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3A                0x25D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3B                0x25E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3C                0x25F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3D                0x260
#define PROCESSOR_INFO_PROCESSOR_FAMILY_LOONGSOON_3E                0x261
#define PROCESSOR_INFO_PROCESSOR_FAMILY_DUAL_CORE_LOONGSOON_2K      0x262
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QC_LOONGSON_3A_5XXX         0x26C
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MC_LOONGSON_3A_5XXX         0x26D
#define PROCESSOR_INFO_PROCESSOR_FAMILY_QC_LOONGSON_3B_5XXX         0x26E
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MC_LOONGSON_3B_5XXX         0x26F
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MC_LOONGSON_3C_5XXX         0x270
#define PROCESSOR_INFO_PROCESSOR_FAMILY_MC_LOONGSON_3D_5XXX         0x271
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_3                0x300
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_5                0x301
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_7                0x302
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_9                0x303
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_ULTRA_3          0x304
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_ULTRA_5          0x305
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_ULTRA_7          0x306
#define PROCESSOR_INFO_PROCESSOR_FAMILY_INTEL_CORE_ULTRA_9          0x307

//skipping CPU_ID for its implemented by specification of manufacutrer in chip

typedef struct PACKED _SMBIOS_PROCESSOR_INFO_VOLTAGE{
    #define         VOLTAGE_CAP_5V      (1)
    #define         VOLTAGE_CAP_3_3V    (1 << 1)
    #define         VOLTAGE_CAP_2_9V    (1 << 2)
    UINT8           VoltageCapabilities : 4;
    UINT8           ReservedMBZ         : 3;
    UINT8           VendorVoltageBit    : 1;
}SMBIOS_PROCESSOR_INFO_VOLTAGE, * PSMBIOS_PROCESSOR_INFO_VOLTAGE;

#define PROCESSOR_INFO_PROCESSOR_UPGRADE_OTHER                          0x01
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_UNKOWN                         0x02
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_DAUGHTER_BOARD                 0x03
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_ZIF_SOCKET                     0x04
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_REPLACEABLE_PIGGY_BACK         0x05
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_NONE                           0x06
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_LIF_SOCKET                     0x07
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SLOT_1                         0x08
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SLOT_2                         0x09
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_370_PIN_SOCKET                 0x0A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SLOT_A                         0x0B
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SLOT_M                         0x0C
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_423                     0x0D
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_462                     0x0E //Socket A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_478                     0x0F
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_754                     0x10
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_940                     0x11
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_939                     0x12
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_MPGA604                 0x13
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA771                  0x14
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA775                  0x15
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_S1                      0x16
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_AM2                     0x17
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_1207                    0x18 //Socket F         
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1366                 0x19
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_G34                     0x1A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_AM3                     0x1B
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_C32                     0x1C
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1156                 0x1D
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1167                 0x1E
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_PGA988A                 0x1F
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1288                 0x20
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_RPGA988B                0x21                
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1023                 0x22            
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1224                 0x23
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1155                 0x24
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1356                 0x25
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA2011                 0x26
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_FS1                     0x27
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_FS2                     0x28
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_FM1                     0x29
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_FM2                     0x2A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA2011_3               0x2B
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1356_3               0x2C
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1150                 0x2D
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1168                 0x2E
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1234                 0x2F
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1364                 0x30
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_AM4                     0x31
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1151                 0x32
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1356                 0x33
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1440                 0x34
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1515                 0x35
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA3647_1               0x36
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_SP3                     0x37
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SCOKET_SP3R2                   0x38
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA2066                 0x39
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1392                 0x3A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1510                 0x3B
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1528                 0x3C
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA4189                 0x3D
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1200                 0x3E
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA4677                 0x3F
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1700                 0x40
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1744                 0x41
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1781                 0x42
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1211                 0x43
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA2422                 0x44
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1211                 0x45
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA2422                 0x46
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA5773                 0x47
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA5773                 0x48
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_AM7                     0x49
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_SP5                     0x4A
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_SP6                     0x4B
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA883                  0x4C
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1190                 0x4D
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA4129                 0x4E
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA4710                 0x4F
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA7529                 0x50
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1964                 0x51
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA1792                 0x52
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA2049                 0x53
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA2551                 0x54
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_LGA1851                 0x55
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA2114                 0x56
#define PROCESSOR_INFO_PROCESSOR_UPGRADE_SOCKET_BGA2833                 0x57

#define PROCESSOR_CHARIST_UNKOWN                (1 << 1)
#define PROCESSOR_CHARIST_64BIT_CAPABLE         (1 << 2)
#define PROCESSOR_CHARIST_MULTI_CORE            (1 << 3)
#define PROCESSOR_CHARIST_HW_THREAD             (1 << 4)
#define PROCESSOR_CHARIST_EXE_PRTECTION         (1 << 5)
#define PROCESSOR_CHARIST_ENHANCED_VIRTUAL      (1 << 6)
#define PROCESSOR_CHARIST_POWER_CONTROL         (1 << 7)
#define PROCESSOR_CHARIST_128BIT_CAPABLE        (1 << 8)
#define PROCESSOR_CHARIST_ARM64_SOC_ID          (1 << 9)

//Type 5 obsolete but here for good mesure
typedef struct PACKED _SMBIOS_MEMORY_CONTROLLER_INFORMATION{
    SMBIOS_HEADER       Header;
    UINT8               ErrorDetectionMethod;
    UINT8               ErrorCorrectingCapabilities;
    UINT8               SupportedInterleave;
    UINT8               CurrentInterleave;
    UINT8               MaxModuleSize;
    UINT16              SupportedSpeeds;
    UINT16              SupportedMemoryTypes;
    //#define           VOLTAGE_CAP_5V      (1)
    //#define           VOLTAGE_CAP_3_3V    (1 << 1)
    //#define           VOLTAGE_CAP_2_9V    (1 << 2)
    UINT8               ModuleVoltage;
    UINT8               AssociatedMemorySlots;
    UINT16              ConfigurationHandles[];
    //ErrorEnabling starts 0Fh + (2*x) 
}SMBIOS_MEMORY_CONTROLLER_INFORMATION, * PSMBIOS_MEMORY_CONTROLLER_INFORMATION;

#define MC_ERROR_CORRECTING_OTHER           (1)
#define MC_ERROR_CORRECTING_UNKOWN          (1 << 1)
#define MC_ERROR_CORRECTING_NONE            (1 << 2)
#define MC_ERROR_CORRECTING_SINGLE_BIT      (1 << 3)
#define MC_ERROR_CORRECTING_DOUBLE_BIT      (1 << 4)
#define MC_ERROR_CORRECTING_ERROR_SCRUB     (1 << 5)

#define MC_INTERLEAVE_SUPPORT_OTHER         0x01
#define MC_INTERLEAVE_SUPPORT_UNKOWN        0x02
#define MC_INTERLEAVE_SUPPORT_ONE_WAY       0x03
#define MC_INTERLEAVE_SUPPORT_TWO_WAY       0x04
#define MC_INTERLEAVE_SUPPORT_FOUR_WAY      0x05
#define MC_INTERLEAVE_SUPPORT_EIGHT_WAY     0x06
#define MC_INTERLEAVE_SUPPORT_SIXTEEN_WAY   0x07

#define MC_MEMORY_SPEEDS_OTHER      (1)
#define MC_MEMORY_SPEEDS_UNKOWN     (1 << 1)
#define MC_MEMORY_SPEEDS_70NS       (1 << 2)
#define MC_MEMORY_SPEEDS_60NS       (1 << 3)
#define MC_MEMORY_SPEEDS_50NS       (1 << 4)

//Type 6 obsolete but here for good mesure
typedef struct PACKED _SMBIOS_MEMORY_MODULE_INFORMATION{
    SMBIOS_HEADER       Header;
    UINT8               SocketDesignation;
    UINT8               BankConnection;
    UINT8               CurrentSpeed;
    UINT16              CurrentMemoryType;
    UINT8               InstalledSize;
    UINT8               EnabledSize;
    UINT8               ErrorStatus;
}SMBIOS_MEMORY_MODULE_INFORMATION, * PSMBIOS_MEMORY_MODULE_INFORMATION;

#define MM_MEMORY_TYPE_OTHER        (1)
#define MM_MEMORY_TYPE_UNKOWN       (1 << 1)
#define MM_MEMORY_TYPE_STANDARD     (1 << 2)
#define MM_MEMORY_TYPE_FAST_PAGE    (1 << 3)
#define MM_MEMORY_TYPE_EDO          (1 << 4)
#define MM_MEMORY_TYPE_PARITY       (1 << 5)
#define MM_MEMORY_TYPE_ECC          (1 << 6)
#define MM_MEMORY_TYPE_SIMM         (1 << 7)
#define MM_MEMORY_TYPE_DIMM         (1 << 8)
#define MM_MEMORY_TYPE_BURST_EDO    (1 << 9)
#define MM_MEMORY_TYPE_SDRAM        (1 << 10)

typedef struct PACKED _SMBIOS_CACHE_INFORMATION{
    SMBIOS_HEADER       Header;
    UINT8               SocketDesignation;
    UINT16              CacheConfiguration;
    UINT16              MaxCacheSize;
    UINT16              InstalledSize;
    UINT16              SramSupported;
    UINT16              CurrentSram;
    UINT8               CacheSpeed;
    UINT8               ErrorCorrectionType;
    UINT8               SystemCacheType;
    UINT8               Associativity;
    UINT32              MaxCacheSize2;
    UINT32              InstalledSize2;
}SMBIOS_CACHE_INFORMATION, * PSMBIOS_CACHE_INFORMATION;


#define CACHE_INFO_SRAM_TYPE_OTHER          (1)
#define CACHE_INFO_SRAM_TYPE_UNKOWN         (1 << 1)
#define CACHE_INFO_SRAM_TYPE_NON_BURST      (1 << 2)
#define CACHE_INFO_SRAM_TYPE_BURST          (1 << 3)
#define CACHE_INFO_SRAM_TYPE_PIPE_BURST     (1 << 4)
#define CACHE_INFO_SRAM_TYPE_SYNCH          (1 << 5)
#define CACHE_INFO_SRAM_TYPE_ASYNCH         (1 << 6)

#define CACHE_INFO_ERROR_CORRECTION_TYPE_OTHER      0x01
#define CACHE_INFO_ERROR_CORRECTION_TYPE_UNKOWN     0x02
#define CACHE_INFO_ERROR_CORRECTION_TYPE_NONE       0x03
#define CACHE_INFO_ERROR_CORRECTION_TYPE_PARITY     0x04
#define CACHE_INFO_ERROR_CORRECTION_TYPE_SINGLE_ECC 0x05
#define CACHE_INFO_ERROR_CORRECTION_TYPE_MULTI_ECC  0x06

#define CACHE_INFO_SYSTEM_CACHE_TYPE_OTHER          0x01
#define CACHE_INFO_SYSTEM_CACHE_TYPE_UNKOWN         0x02
#define CACHE_INFO_SYSTEM_CACHE_TYPE_INSTRUCTION    0x03
#define CACHE_INFO_SYSTEM_CACHE_TYPE_DATA           0x04
#define CACHE_INFO_SYSTEM_CACHE_TYPE_UNIFIED        0x05

#define CACHE_INFO_ASSOCIATIVITY_OTHER          0x01
#define CACHE_INFO_ASSOCIATIVITY_UNKOWN         0x02
#define CACHE_INFO_ASSOCIATIVITY_DIRECT_MAP     0x03
#define CACHE_INFO_ASSOCIATIVITY_2_WAY_SET      0x04
#define CACHE_INFO_ASSOCIATIVITY_4_WAY_SET      0x05
#define CACHE_INFO_ASSOCIATIVITY_FULL           0x06
#define CACHE_INFO_ASSOCIATIVITY_8_WAY_SET      0x07
#define CACHE_INFO_ASSOCIATIVITY_16_WAY_SET     0x08
#define CACHE_INFO_ASSOCIATIVITY_12_WAY_SET     0x09
#define CACHE_INFO_ASSOCIATIVITY_24_WAY_SET     0x0A
#define CACHE_INFO_ASSOCIATIVITY_32_WAY_SET     0x0B
#define CACHE_INFO_ASSOCIATIVITY_48_WAY_SET     0x0C
#define CACHE_INFO_ASSOCIATIVITY_64_WAY_SET     0x0D
#define CACHE_INFO_ASSOCIATIVITY_20_WAY_SET     0x0E

typedef struct PACKED _SMBIOS_PORT_CONNECTOR_INFO{
    SMBIOS_HEADER       Header;
    UINT8               InternalReference;
    UINT8               InternalConnectorType;
    UINT8               ExternalReference;
    UINT8               ExternalConnectorType;
    UINT8               PortType;
}SMBIOS_PORT_CONNECTOR_INFO, * PSMBIOS_PORT_CONNECTOR_INFO;

#define PORT_INFO_CONECTOR_TYPE_NONE                            0x00
#define PORT_INFO_CONECTOR_TYPE_CENTRONICS                      0x01
#define PORT_INFO_CONECTOR_TYPE_MINI_CENRONICS                  0x02
#define PORT_INFO_CONECTOR_TYPE_PROPRIETARY                     0x03
#define PORT_INFO_CONECTOR_TYPE_DB_25_PIN_MALE                  0x04
#define PORT_INFO_CONECTOR_TYPE_DB_25_PIN_FEMALE                0x05
#define PORT_INFO_CONECTOR_TYPE_DB_15_PIN_MALE                  0x06
#define PORT_INFO_CONECTOR_TYPE_DB_15_PIN_FEMALE                0x07
#define PORT_INFO_CONECTOR_TYPE_DB_9_PIN_MALE                   0x08
#define PORT_INFO_CONECTOR_TYPE_DB_9_PIN_FEMALE                 0x09
#define PORT_INFO_CONECTOR_TYPE_RJ_11                           0x0A
#define PORT_INFO_CONECTOR_TYPE_RJ_45                           0x0B
#define PORT_INFO_CONECTOR_TYPE_MINI_SCSI_50                    0x0C
#define PORT_INFO_CONECTOR_TYPE_MINI_DIN                        0x0D
#define PORT_INFO_CONECTOR_TYPE_MICRO_DIN                       0x0E
#define PORT_INFO_CONECTOR_TYPE_PS2                             0x0F
#define PORT_INFO_CONECTOR_TYPE_INFRARED                        0x10
#define PORT_INFO_CONECTOR_TYPE_HP_HIL                          0x11
#define PORT_INFO_CONECTOR_TYPE_ACCESS_BUS                      0x12
#define PORT_INFO_CONECTOR_TYPE_SSA_SCSI                        0x13
#define PORT_INFO_CONECTOR_TYPE_CIRCULAR_DIN_8_PIN_MALE         0x14
#define PORT_INFO_CONECTOR_TYPE_CIRCULAR_DIN_8_PIN_FEMALE       0x15
#define PORT_INFO_CONECTOR_TYPE_ON_BORD_IDE                     0x16
#define PORT_INFO_CONECTOR_TYPE_ON_BOARD_FLOPY                  0x17
#define PORT_INFO_CONECTOR_TYPE_9_PIN_DUAL_INLINE               0x18
#define PORT_INFO_CONECTOR_TYPE_25_PIN_DUAL_INLINE              0x19
#define PORT_INFO_CONECTOR_TYPE_50_PIN_DUAL_INLINE              0x1A
#define PORT_INFO_CONECTOR_TYPE_68_PIN_DUAL_INLINE              0x1B
#define PORT_INFO_CONECTOR_TYPE_ONBOARD_CDROM_SOUND             0x1C
#define PORT_INFO_CONECTOR_TYPE_MINI_CENRONICS_TYPE14           0x1D
#define PORT_INFO_CONECTOR_TYPE_MINI_CENRONICS_TYPE26           0x1E
#define PORT_INFO_CONECTOR_TYPE_MINI_JACK_HEADPHONES            0x1F
#define PORT_INFO_CONECTOR_TYPE_BNC                             0x20
#define PORT_INFO_CONECTOR_TYPE_1394                            0x21
#define PORT_INFO_CONECTOR_TYPE_SATA_SAS_PLUG                   0x22
#define PORT_INFO_CONECTOR_TYPE_USB_TYPE_C                      0x23
#define PORT_INFO_CONECTOR_TYPE_PC98                            0xA0
#define PORT_INFO_CONECTOR_TYPE_PC98_HIRESO                     0xA1
#define PORT_INFO_CONECTOR_TYPE_PCH98                           0xA2
#define PORT_INFO_CONECTOR_TYPE_PC98_NOTE                       0xA3
#define PORT_INFO_CONECTOR_TYPE_PC98_FULL                       0xA4

#define PORT_INFO_PORT_TYPES_NONE               0x00
#define PORT_INFO_PORT_TYPES_PARALLEL_XTAT      0x01
#define PORT_INFO_PORT_TYPES_PARALLEL_PS2       0x02
#define PORT_INFO_PORT_TYPES_PARALLEL_ECP       0x03
#define PORT_INFO_PORT_TYPES_PARALLEL_EPP       0x04
#define PORT_INFO_PORT_TYPES_PARALLEL_ECP_EPP   0x05
#define PORT_INFO_PORT_TYPES_SERIAL_XTAT        0x06
#define PORT_INFO_PORT_TYPES_SERIAL_16450       0x07
#define PORT_INFO_PORT_TYPES_SERIAL_16550       0x08
#define PORT_INFO_PORT_TYPES_SERIAL_16550A      0x09
#define PORT_INFO_PORT_TYPES_SCSI               0x0A
#define PORT_INFO_PORT_TYPES_MIDI               0x0B
#define PORT_INFO_PORT_TYPES_JOY_STICK          0x0C
#define PORT_INFO_PORT_TYPES_KEYBOARD           0x0D
#define PORT_INFO_PORT_TYPES_MOUSE_PORT         0x0E
#define PORT_INFO_PORT_TYPES_SSA_SCSI           0x0F
#define PORT_INFO_PORT_TYPES_USB                0x10
#define PORT_INFO_PORT_TYPES_FIREWIRE           0x11
#define PORT_INFO_PORT_TYPES_PCMCIA_I           0x12
#define PORT_INFO_PORT_TYPES_PCMCIA_II          0x13
#define PORT_INFO_PORT_TYPES_PCMCIA_III         0x14
#define PORT_INFO_PORT_TYPES_CARD_BUS           0x15
#define PORT_INFO_PORT_TYPES_ACCESS_BUS_PORT    0x16
#define PORT_INFO_PORT_TYPES_SCSI_II            0x17
#define PORT_INFO_PORT_TYPES_SCSI_WIDE          0x18
#define PORT_INFO_PORT_TYPES_PC98               0x19
#define PORT_INFO_PORT_TYPES_PC98_HIRESO        0x1A
#define PORT_INFO_PORT_TYPES_PCH98              0x1B
#define PORT_INFO_PORT_TYPES_VIDEO              0x1C
#define PORT_INFO_PORT_TYPES_AUDIO              0x1D
#define PORT_INFO_PORT_TYPES_MODEM              0x1E
#define PORT_INFO_PORT_TYPES_NETWORK            0x1F
#define PORT_INFO_PORT_TYPES_SATA               0x20
#define PORT_INFO_PORT_TYPES_SAS                0x21
#define PORT_INFO_PORT_TYPES_MFDP               0x22
#define PORT_INFO_PORT_TYPES_THUNDERBOLT        0x23
#define PORT_INFO_PORT_TYPES_8251               0xA0
#define PORT_INFO_PORT_TYPES_8251_FIFO          0xA1

typedef struct PACKED _SMBIOS_SYSTEM_SLOTS{
    SMBIOS_HEADER       Header;
    UINT8               SlotDesignation;
    UINT8               SlotType;
    UINT8               SlotDataBusWidth;
    UINT8               CurrentUsage;
    UINT8               SlotLength;
    UINT16              SlotID;
    UINT8               SlotCharecteristic1;
    UINT8               SlotCharecteristic2;
    UINT16              SegmentGroup;
    UINT8               BusNumber;
    UINT8               DeviceNFunction;
    UINT8               DataBusWidth;
    UINT8               PeerGroupCount;
    UINT8               ExtraData[];
    //TODO
}SMBIOS_SYSTEM_SLOTS, * PSMBIOS_SYSTEM_SLOTS;

#define SYSTEM_SLOT_SLOT_TYPE_OTHER                             0x01
#define SYSTEM_SLOT_SLOT_TYPE_UNKNOWN                           0x02
#define SYSTEM_SLOT_SLOT_TYPE_ISA                               0x03
#define SYSTEM_SLOT_SLOT_TYPE_MCA                               0x04
#define SYSTEM_SLOT_SLOT_TYPE_EISA                              0x05
#define SYSTEM_SLOT_SLOT_TYPE_PCI                               0x06
#define SYSTEM_SLOT_SLOT_TYPE_PCMCIA                            0x07
#define SYSTEM_SLOT_SLOT_TYPE_VL_VESA                           0x08
#define SYSTEM_SLOT_SLOT_TYPE_PROPRIETARY                       0x09
#define SYSTEM_SLOT_SLOT_TYPE_PROCESSOR_CARD                    0x0A
#define SYSTEM_SLOT_SLOT_TYPE_PROPRIETART_MEM_CARD              0x0B
#define SYSTEM_SLOT_SLOT_TYPE_IO_RISER_CARD                     0x0C
#define SYSTEM_SLOT_SLOT_TYPE_NU_BUS                            0x0D
#define SYSTEM_SLOT_SLOT_TYPE_PCI66                             0x0E
#define SYSTEM_SLOT_SLOT_TYPE_AGP                               0x0F
#define SYSTEM_SLOT_SLOT_TYPE_AGP_2X                            0x10
#define SYSTEM_SLOT_SLOT_TYPE_AGP_4X                            0x11
#define SYSTEM_SLOT_SLOT_TYPE_PCIX                              0x12
#define SYSTEM_SLOT_SLOT_TYPE_AGP_8X                            0x13
#define SYSTEM_SLOT_SLOT_TYPE_M2_SOCKET_1_DP                    0x14
#define SYSTEM_SLOT_SLOT_TYPE_M2_SOCKET_1_SD                    0x15
#define SYSTEM_SLOT_SLOT_TYPE_M2_SOCKET_2                       0x16
#define SYSTEM_SLOT_SLOT_TYPE_M2_SOCKET_3                       0x17
#define SYSTEM_SLOT_SLOT_TYPE_MXM_TYPE_I                        0x18
#define SYSTEM_SLOT_SLOT_TYPE_MXM_TYPE_II                       0x19
#define SYSTEM_SLOT_SLOT_TYPE_MXM_TYPE_III_STANDARD             0x1A
#define SYSTEM_SLOT_SLOT_TYPE_MXM_TYPE_III_HE                   0x1B
#define SYSTEM_SLOT_SLOT_TYPE_MXM_TYPE_IV                       0x1C
#define SYSTEM_SLOT_SLOT_TYPE_MXM_3A                            0x1D
#define SYSTEM_SLOT_SLOT_TYPE_MXM_3B                            0x1E
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_SFF_8639                0x1F
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_SFF_8639                0x20
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_MINI_52_BOTTOMSIDE           0x21
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_MINI_53_NO_BOTTOMSIZE        0x22
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_MINI_76_DSIPLAY              0x23
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_SFF_8639                0x24
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_SFF_8639                0x25
#define SYSTEM_SLOT_SLOT_TYPE_OCP_NIC_3_SFF                     0x26
#define SYSTEM_SLOT_SLOT_TYPE_OCP_NIC_3_LFF                     0x27
#define SYSTEM_SLOT_SLOT_TYPE_OCP_NIC_PRIOR_3                   0x28                     
#define SYSTEM_SLOT_SLOT_TYPE_CXL_FLEXBUS_1                     0x30
#define SYSTEM_SLOT_SLOT_TYPE_PC98_C20                          0xA0
#define SYSTEM_SLOT_SLOT_TYPE_PC98_C24                          0xA1
#define SYSTEM_SLOT_SLOT_TYPE_PC98_E                            0xA2
#define SYSTEM_SLOT_SLOT_TYPE_PC98_LOCAL_BUS                    0xA3
#define SYSTEM_SLOT_SLOT_TYPE_PC98_CARD                         0xA4
#define SYSTEM_SLOT_SLOT_TYPE_PCIE                              0xA5
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_X1                           0xA6
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_X2                           0xA7
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_X4                           0xA8
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_X8                           0xA9
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_X16                          0xAA
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2                         0xAB
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_X1                      0xAC  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_X2                      0xAD  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_X4                      0xAE    
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_X8                      0xAF    
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN2_X16                     0xB0    
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3                         0xB1
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_X1                      0xB2
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_X2                      0xB3  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_X4                      0xB4  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_X8                      0xB5  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN3_X16                     0xB6  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4                         0xB8
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_X1                      0xB9  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_X2                      0xBA  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_X4                      0xBB  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_X8                      0xBC  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN4_X16                     0xBD  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5                         0xBE
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_X1                      0xBF  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_X2                      0xC0  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_X4                      0xC1  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_X8                      0xC2  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN5_X16                     0xC3  
#define SYSTEM_SLOT_SLOT_TYPE_PCIE_GEN6                         0xC4
#define SYSTEM_SLOT_SLOT_TYPE_EDSFF_E1_S_E1_L                   0xC5     
#define SYSTEM_SLOT_SLOT_TYPE_EDSFF_E3_S_E3_L                   0xC6      

//1138


#include "Dmi.h"

void* GetSmBiosAddress();

#ifdef __cplusplus
}
#endif
#endif
