
all:
	$(MAKE) -C Networking all
	$(MAKE) -C DMA all
	$(MAKE) -C Audio all
	$(MAKE) -C Input all
	$(MAKE) -C gpu all
	$(MAKE) -C storage all
	$(MAKE) -C Serial all
	$(MAKE) -C USB all

clean:
	$(MAKE) -C Networking clean
	$(MAKE) -C DMA clean
	$(MAKE) -C Audio clean
	$(MAKE) -C Input clean
	$(MAKE) -C gpu clean
	$(MAKE) -C storage clean
	$(MAKE) -C Serial clean
	$(MAKE) -C USB clean