#ifndef _LOUINTSAFE_H
#define _LOUINTSAFE_H

#include <Ldm.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _USER_MODE_CODE_

KERNEL_EXPORT LOUSTATUS LouKeRtlByteToChar(BYTE bOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlByteToInt8(BYTE bOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlDWordPtrAdd(DWORD_PTR dwAugend, DWORD_PTR dwAddend, DWORD_PTR* pdwResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlDWordPtrMult(DWORD_PTR dwMultiplicand, DWORD_PTR dwMultiplier, DWORD_PTR* pdwResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlDWordPtrSub(DWORD_PTR dwMinuend, DWORD_PTR dwSubtrahend, DWORD_PTR* pdwResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8Add(INT8 i8Augend, INT8 i8Addend, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8Mult(INT8 i8Multiplicand, INT8 i8Multiplier, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8Sub(INT8 i8Minuend, INT8 i8Subtrahend, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToUChar(INT8 i8Operand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToUInt(INT8 i8Operand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToUInt8(INT8 i8Operand, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToUIntPtr(INT8 i8Operand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToULong(INT8 i8Operand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToULongLong(INT8 i8Operand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToULongPtr(INT8 i8Operand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlInt8ToUShort(INT8 i8Operand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntAdd(INT iAugend, INT iAddend, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntMult(INT iMultiplicand, INT iMultiplier, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrAdd(INT_PTR iAugend, INT_PTR iAddend, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrMult(INT_PTR iMultiplicand, INT_PTR iMultiplier, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrSub(INT_PTR iMinuend, INT_PTR iSubtrahend, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToChar(INT_PTR iOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToInt8(INT_PTR iOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToLong(INT_PTR iOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToLongPtr(INT_PTR iOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToShort(INT_PTR iOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToUChar(INT_PTR iOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToUInt(INT_PTR iOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToUInt8(INT_PTR iOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToUIntPtr(INT_PTR iOperand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToULong(INT_PTR iOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToULongLong(INT_PTR iOperand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToULongPtr(INT_PTR iOperand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntPtrToUShort(INT_PTR iOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntSub(INT iMinuend, INT iSubtrahend, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToChar(INT iOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToInt8(INT iOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToShort(INT iOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToUChar(INT iOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToUInt(INT iOperand,UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToUInt8(INT iOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToULong(INT iOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToULongLong(INT iOperand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlIntToUShort(INT iOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongAdd(LONG lAugend, LONG lAddend, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongAdd(LONGLONG llAugend, LONGLONG llAddend, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongMult(LONGLONG llMultiplicand, LONGLONG llMultiplier, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongSub(LONGLONG llMinuend, LONGLONG llSubtrahend, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToChar(LONGLONG llOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToInt(LONGLONG llOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToInt8(LONGLONG llOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToIntPtr(LONGLONG llOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToLong(LONGLONG llOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToLongPtr(LONGLONG llOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToShort(LONGLONG llOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToUChar(LONGLONG llOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToUInt(LONGLONG llOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToUInt8(LONGLONG llOperand, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToULong(LONGLONG llOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToULongLong(LONGLONG llOperand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongLongToUShort(LONGLONG llOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongMult(LONG lMultiplicand, LONG lMultiplier, LONG *plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrAdd(LONG_PTR lAugend, LONG_PTR lAddend, LONG_PTR *plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrMult(LONG_PTR lMultiplicand, LONG_PTR lMultiplier, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrSub(LONG_PTR lMinuend, LONG_PTR lSubtrahend, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToChar(LONG_PTR lOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToInt(LONG_PTR lOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToInt8(LONG_PTR lOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToIntPtr(LONG_PTR lOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToLong(LONG_PTR lOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToShort(LONG_PTR lOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToUChar(LONG_PTR lOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToUInt(LONG_PTR lOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToUInt8(LONG_PTR lOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToUIntPtr(LONG_PTR lOperand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToULong(LONG_PTR lOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToULongLong(LONG_PTR  lOperand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToULongPtr(LONG_PTR lOperand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongPtrToUShort(LONG_PTR lOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongSub(LONG lMinuend, LONG lSubtrahend, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToChar(LONG lOperand, CHAR *pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToInt(LONG lOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToInt8(LONG lOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToIntPtr(LONG lOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToShort(LONG lOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToUChar(LONG lOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToUInt(LONG lOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToUInt8(LONG  lOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToUIntPtr(LONG lOperand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToULong(LONG lOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToULongLong(LONG lOperand, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToULongPtr(LONG lOperand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlLongToUShort(LONG lOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlPtrdiffTAdd(ptrdiff_t Augend, ptrdiff_t Addend, ptrdiff_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlPtrdiffTMult(ptrdiff_t Multiplicand, ptrdiff_t Multiplier, ptrdiff_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlPtrdiffTSub(ptrdiff_t Minuend, ptrdiff_t Subtrahend, ptrdiff_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortAdd(SHORT sAugend, SHORT sAddend, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortMult(SHORT sMultiplicand, SHORT sMultiplier, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortSub(SHORT sMinuend, SHORT sSubtrahend, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToChar(SHORT sOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToDWordPtr(SHORT sOperand, DWORD_PTR* pdwResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToInt8(SHORT sOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToUChar(SHORT sOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToUInt(SHORT sOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToUInt8(SHORT sOperand, UINT8 *pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToUIntPtr(SHORT sOperand, UINT_PTR *puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToULong(SHORT sOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToULongLong(SHORT sOperand, ULONGLONG *pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToULongPtr(SHORT sOperand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlShortToUShort(SHORT sOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSizeTAdd(size_t Augend, size_t Addend, size_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSizeTMult(size_t Multiplicand, size_t Multiplier, size_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSizeTSub(size_t Minuend, size_t Subtrahend, size_t* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSSIZETAdd(SSIZE_T Augend, SSIZE_T Addend, SSIZE_T* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSSIZETMult(SSIZE_T Multiplicand, SSIZE_T Multiplier, SSIZE_T* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlSSIZETSub(SSIZE_T Minuend, SSIZE_T Subtrahend, SSIZE_T* pResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUInt8Add(UINT8 u8Augend, UINT8 u8Addend, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUInt8Mult(UINT8 u8Multiplicand, UINT8 u8Multiplier, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUInt8Sub(UINT8 u8Minuend, UINT8 u8Subtrahend, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUInt8ToChar(UINT8 u8Operand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUInt8ToInt8(UINT8 u8Operand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntAdd(UINT uAugend, UINT uAddend, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntMult(UINT uMultiplicand, UINT uMultiplier, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrAdd(UINT_PTR uAugend, UINT_PTR uAddend, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrMult(UINT_PTR uMultiplicand, UINT_PTR uMultiplier, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrSub(UINT_PTR uMinuend, UINT_PTR uSubtrahend, UINT_PTR *puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToChar(UINT_PTR uOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToInt(UINT_PTR uOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToInt16(UINT_PTR uOperand, INT16* pi16Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToInt8(UINT_PTR uOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToIntPtr(UINT_PTR uOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToLong(UINT_PTR uOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToLongLong(UINT_PTR uOperand, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToLongPtr(UINT_PTR uOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToShort(UINT_PTR uOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToUChar(UINT_PTR uOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToUInt(UINT_PTR uOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToUInt16(UINT_PTR uOperand, UINT16* pu16Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToUInt8(UINT_PTR uOperand, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToULong(UINT_PTR uOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntPtrToUShort(UINT_PTR uOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntSub(UINT uMinuend, UINT uSubtrahend, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToChar(UINT uOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToInt(UINT uOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToInt8(UINT uOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToIntPtr(UINT uOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToLong(UINT uOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToLongPtr(UINT uOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToShort(UINT uOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToUChar(UINT uOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToUInt8(UINT uOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUIntToUShort(UINT uOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongAdd(ULONG ulAugend, ULONG ulAddend, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongAdd(ULONGLONG ullAugend, ULONGLONG ullAddend, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongMult(ULONGLONG ullMultiplicand, ULONGLONG ullMultiplier, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongSub(ULONGLONG ullMinuend, ULONGLONG ullSubtrahend, ULONGLONG* pullResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToChar(ULONGLONG ullOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToInt(ULONGLONG ullOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToInt8(ULONGLONG ullOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToLong(ULONGLONG ullOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToLongLong(ULONGLONG ullOperand, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToLongPtr(ULONGLONG ullOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToShort(ULONGLONG ullOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToUChar(ULONGLONG ullOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToUInt(ULONGLONG ullOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToUInt8(ULONGLONG ullOperand, UINT8* pu8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToUIntPtr(ULONGLONG ullOperand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToULong(ULONGLONG ullOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToULongPtr(ULONGLONG ullOperand, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongLongToUShort(ULONGLONG ullOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongMult(ULONG ulMultiplicand, ULONG ulMultiplier, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrAdd(ULONG_PTR ulAugend, ULONG_PTR ulAddend, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrMult(ULONG_PTR ulMultiplicand, ULONG_PTR ulMultiplier, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrSub(ULONG_PTR ulMinuend, ULONG_PTR ulSubtrahend, ULONG_PTR* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToChar(ULONG_PTR ulOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToInt(ULONG_PTR ulOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToInt8(ULONG_PTR ulOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToIntPtr(ULONG_PTR ulOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToLong(ULONG_PTR ulOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToLongLong(ULONG_PTR ulOperand, LONGLONG* pllResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToLongPtr(ULONG_PTR ulOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToShort(ULONG_PTR ulOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToUInt(ULONG_PTR ulOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToUInt8(ULONG_PTR ulOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToUIntPtr(ULONG_PTR ulOperand, UINT_PTR* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToULong(ULONG_PTR ulOperand, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongPtrToUShort(ULONG_PTR ulOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongSub(ULONG ulMinuend, ULONG ulSubtrahend, ULONG* pulResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToChar(ULONG ulOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToInt(ULONG ulOperand, INT* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToInt8(ULONG ulOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToIntPtr(ULONG ulOperand, INT_PTR* piResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToLong(ULONG ulOperand, LONG* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToLongPtr(ULONG ulOperand, LONG_PTR* plResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToShort(ULONG ulOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToUChar(ULONG ulOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToUInt(ULONG ulOperand, UINT* puResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToUInt8(ULONG ulOperand, UINT8* pui8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToUIntPtr(ULONG ulOperand, UINT_PTR* puiResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlULongToUShort(ULONG ulOperand, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortAdd(USHORT usAugend, USHORT usAddend, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortMult(USHORT usMultiplicand, USHORT usMultiplier, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortSub(USHORT usMinuend, USHORT usSubtrahend, USHORT* pusResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortToChar(USHORT usOperand, CHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortToInt8(USHORT usOperand, INT8* pi8Result);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortToShort(USHORT usOperand, SHORT* psResult);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortToUChar(USHORT usOperand, UCHAR* pch);
KERNEL_EXPORT LOUSTATUS LouKeRtlUShortToUInt8(USHORT usOperand, UINT8* pui8Result);

#else

#endif
#ifdef __cplusplus
}
#endif
#endif