#ifndef _PEP_FRAMEWORK_H
#define _PEP_FRAMEWORK_H

#include <Ldm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef 
LOUSTATUS 
PEPCALLBACKNOTIFYDPM(
    PEPHANDLE   DeviceHandle,
    ULONG       Notification,
    PVOID       Data
);

typedef PEPCALLBACKNOTIFYDPM* PPEPCALLBACKNOTIFYDPM;

typedef 
BOOLEAN
PEPCALLBACKNOTIFYPPM(
    ULONG   Notification,
    PVOID   Data
);

typedef PEPCALLBACKNOTIFYPPM* PPEPCALLBACKNOTIFYPPM;

typedef 
BOOLEAN
PEPCALLBACKNOTIFYACPI(
    ULONG   Notification,
    PVOID   Data
);

typedef PEPCALLBACKNOTIFYACPI* PPEPCALLBACKNOTIFYACPI;

typedef 
LOUSTATUS 
POFXCALLBACKREQUESTWORKER(
    POHANDLE    DeviceHandle,
    ULONG       Flags
);

typedef POFXCALLBACKREQUESTWORKER* PPOFXCALLBACKREQUESTWORKER;

typedef 
LOUSTATUS
POFXCALLBACKENUMERATEUNMASKEDINTERRUPTS(
    PVOID   PluginHandle,
    ULONG   Flags
);

typedef POFXCALLBACKENUMERATEUNMASKEDINTERRUPTS* PPOFXCALLBACKENUMERATEUNMASKEDINTERRUPTS;

typedef 
LOUSTATUS 
PROCESSOR_HALT_ROUTINE(
    PVOID   Context
);

typedef PROCESSOR_HALT_ROUTINE * PPROCESSOR_HALT_ROUTINE;

typedef 
LOUSTATUS
POFXCALLBACKPROCESSORHALT(
    ULONG                       Flags,
    PVOID                       Context,
    PPROCESSOR_HALT_ROUTINE     HaltRoutine
);

typedef POFXCALLBACKPROCESSORHALT* PPOFXCALLBACKPROCESSORHALT;


typedef 
LOUSTATUS
POFXCALLBACKREQUESTINTERRUPT(
    ULONG   Gsiv
);

typedef POFXCALLBACKREQUESTINTERRUPT* PPOFXCALLBACKREQUESTINTERRUPT;

typedef 
void
POFXCALLBACKCRITICALRESOURCE(
    POHANDLE    DeviceHandle,
    ULONG       Component,
    BOOLEAN     Active
);

typedef POFXCALLBACKCRITICALRESOURCE* PPOFXCALLBACKCRITICALRESOURCE;


typedef 
LOUSTATUS
POFXCALLBACKPROCESSORIDLEVETO(
    POHANDLE    ProcessorHandle,
    ULONG       ProcessorState,
    ULONG       VetoReason,
    BOOLEAN     Increment
);

typedef POFXCALLBACKPROCESSORIDLEVETO* PPOFXCALLBACKPROCESSORIDLEVETO;

typedef 
LOUSTATUS 
POFXCALLBACKPLATFORMIDLEVETO(
    POHANDLE    ProcessorHandle,
    ULONG       PlatformState,
    ULONG       VetoReason,
    BOOLEAN     Increment
);

typedef POFXCALLBACKPLATFORMIDLEVETO* PPOFXCALLBACKPLATFORMIDLEVETO;

typedef struct _PEP_IDLE_STATE_UPDATE {
  ULONG Version;
  ULONG Latency;
  ULONG BreakEvenDuration;
} PEP_PROCESSOR_IDLE_STATE_UPDATE, * PPEP_PROCESSOR_IDLE_STATE_UPDATE, 
    PEP_PLATFORM_IDLE_STATE_UPDATE, * PPEP_PLATFORM_IDLE_STATE_UPDATE;

typedef 
LOUSTATUS
POFXCALLBACKUPDATEPROCESSORIDLESTATE(
    POHANDLE                            ProcessorHandle,
    ULONG                               ProcessorState,
    PPEP_PROCESSOR_IDLE_STATE_UPDATE    IdleStateUpdate
);

typedef POFXCALLBACKUPDATEPROCESSORIDLESTATE* PPOFXCALLBACKUPDATEPROCESSORIDLESTATE;

typedef 
LOUSTATUS
POFXCALLBACKUPDATEPLATFORMIDLESTATE(
    POHANDLE                            ProcessorHandle,
    ULONG                               PlatformState,
    PPEP_PLATFORM_IDLE_STATE_UPDATE     IdleUpdateState 
);

typedef POFXCALLBACKUPDATEPLATFORMIDLESTATE* PPOFXCALLBACKUPDATEPLATFORMIDLESTATE;

typedef 
LOUSTATUS 
POFXCALLBACKREQUESTCOMMON(
    ULONG   RequestId,
    PVOID   Data
);

typedef POFXCALLBACKREQUESTCOMMON* PPOFXCALLBACKREQUESTCOMMON;

typedef struct _PEP_CRASHDUMP_INFORMATION{
   PEPHANDLE DeviceHandle;
   PVOID     DeviceContext;
}PEP_CRASHDUMP_INFORMATION, * PPEP_CRASHDUMP_INFORMATION;

typedef 
BOOLEAN
PEPCALLBACKPOWERONCRASHDUMPDEVICE(
    PPEP_CRASHDUMP_INFORMATION  Information
);  

typedef PEPCALLBACKPOWERONCRASHDUMPDEVICE* PPEPCALLBACKPOWERONCRASHDUMPDEVICE;

typedef struct _PEP_KERNEL_INFORMATION_STRUCT_V1{
  USHORT                                   Version;
  USHORT                                   Size;
  POHANDLE                                 Plugin;
  PPOFXCALLBACKREQUESTWORKER               RequestWorker;
  PPOFXCALLBACKENUMERATEUNMASKEDINTERRUPTS EnumerateUnmaskedInterrupts;
  PPOFXCALLBACKPROCESSORHALT               ProcessorHalt;
  PPOFXCALLBACKREQUESTINTERRUPT            RequestInterrupt;
  PPOFXCALLBACKCRITICALRESOURCE            TransitionCriticalResource;
}PEP_KERNEL_INFORMATION_STRUCT_V1, * PPEP_KERNEL_INFORMATION_STRUCT_V1;

typedef struct _PEP_KERNEL_INFORMATION_STRUCT_V2{
  USHORT                                   Version;
  USHORT                                   Size;
  POHANDLE                                 Plugin;
  PPOFXCALLBACKREQUESTWORKER               RequestWorker;
  PPOFXCALLBACKENUMERATEUNMASKEDINTERRUPTS EnumerateUnmaskedInterrupts;
  PPOFXCALLBACKPROCESSORHALT               ProcessorHalt;
  PPOFXCALLBACKREQUESTINTERRUPT            RequestInterrupt;
  PPOFXCALLBACKCRITICALRESOURCE            TransitionCriticalResource;
  PPOFXCALLBACKPROCESSORIDLEVETO           ProcessorIdleVeto;
  PPOFXCALLBACKPLATFORMIDLEVETO            PlatformIdleVeto;
  PPOFXCALLBACKUPDATEPROCESSORIDLESTATE    UpdateProcessorIdleState;
  PPOFXCALLBACKUPDATEPLATFORMIDLESTATE     UpdatePlatformIdleState;
}PEP_KERNEL_INFORMATION_STRUCT_V2, *PPEP_KERNEL_INFORMATION_STRUCT_V2;

typedef struct _PEP_KERNEL_INFORMATION_STRUCT_V3{
  USHORT                                   Version;
  USHORT                                   Size;
  POHANDLE                                 Plugin;
  PPOFXCALLBACKREQUESTWORKER               RequestWorker;
  PPOFXCALLBACKENUMERATEUNMASKEDINTERRUPTS EnumerateUnmaskedInterrupts;
  PPOFXCALLBACKPROCESSORHALT               ProcessorHalt;
  PPOFXCALLBACKREQUESTINTERRUPT            RequestInterrupt;
  PPOFXCALLBACKCRITICALRESOURCE            TransitionCriticalResource;
  PPOFXCALLBACKPROCESSORIDLEVETO           ProcessorIdleVeto;
  PPOFXCALLBACKPLATFORMIDLEVETO            PlatformIdleVeto;
  PPOFXCALLBACKUPDATEPROCESSORIDLESTATE    UpdateProcessorIdleState;
  PPOFXCALLBACKUPDATEPLATFORMIDLESTATE     UpdatePlatformIdleState;
  PPOFXCALLBACKREQUESTCOMMON               RequestCommon;
}PEP_KERNEL_INFORMATION_STRUCT_V3, * PPEP_KERNEL_INFORMATION_STRUCT_V3;

typedef union _PEP_KERNEL_INFORMATION{
    PEP_KERNEL_INFORMATION_STRUCT_V1    V1;
    PEP_KERNEL_INFORMATION_STRUCT_V2    V2;
    PEP_KERNEL_INFORMATION_STRUCT_V3    V3;
}PEP_KERNEL_INFORMATION, * PPEP_KERNEL_INFORMATION;





#ifdef __cplusplus
}
#endif
#endif