#ifndef _MSI_FUSION_ARCHITECTURE_H
#define _MSI_FUSION_ARCHITECTURE_H

#include <cstdlib.h>

#include "Sat.h"

typedef UINT16  MPT_FUSION_DEVICE_HANDLE;       //devhandle
typedef UINT16  MPT_FUSION_ENCLOSURE_HANDLE;
typedef UINT64  MPT_FUSION_WWID;

#define LSI_ULTRA320_SYSTEM_DOORBELL_IO_OFFSET             0x0000
#define LSI_ULTRA320_WRITE_SEQUENCE_IO_OFFSET              0x0004
#define LSI_ULTRA320_HOST_DIAGNOSTIC_IO_OFFSET             0x0008
#define LSI_ULTRA320_TEST_BASE_ADDRESS_IO_OFFSET           0x000C
#define LSI_ULTRA320_DIAGNOSTIC_RW_DATA_IO_OFFSET          0x0010
#define LSI_ULTRA320_DIAGNOSTIC_RW_ADDRESS_IO_OFFSET       0x0014
#define LSI_ULTRA320_HOST_INTERRUPT_STATUS_IO_OFFSET       0x0030
#define LSI_ULTRA320_HOST_INTERRUPT_MASK_IO_OFFSET         0x0034
#define LSI_ULTRA320_REQUEST_FIFO_IO_OFFSET                0x0040
#define LSI_ULTRA320_REPLY_FIFO_IO_OFFSET                  0x0044

#define LSI_ULTRA320_IOC_STATE_MASK             0x0F
#define LSI_ULTRA320_IOC_STATE_SHIFT            28
#define LSI_ULTRA320_IOC_STATE_RESET            0x00
#define LSI_ULTRA320_IOC_STATE_READY            0x01
#define LSI_ULTRA320_IOC_STATE_OPERATIONAL      0x02
#define LSI_ULTRA320_IOC_STATE_FAULT            0x04

#define LSI_ULTRA320_DOORBELL_USED_BIT          (1 << 27)
#define LSI_ULTRA320_DOORBELL_NO_DOORBELL_USED  0
#define LSI_ULTRA320_DOORBELL_DOORBELL_USED     1

#define LSI_ULTRA320_WHO_INIT_MASK              0x07
#define LSI_ULTRA320_WHO_INIT_SHIFT             24
#define LSI_ULTRA320_WHO_INIT_NO_ONE            0x00
#define LSI_ULTRA320_WHO_INIT_SYSTEM_BIOS       0x01
#define LSI_ULTRA320_WHO_INIT_ROM_BIOS          0x02
#define LSI_ULTRA320_WHO_INIT_PCI_PEER          0x03
#define LSI_ULTRA320_WHO_INIT_HOST_DRIVER       0x04
#define LSI_ULTRA320_WHI_INIT_MANUFACTURER      0x05

#define LSI_DB_FUNCTION_IOC_MESSAGE_UNIT_RESET      0x40
#define LSI_DB_FUNCTION_IO_UNIT_RESET               0x41
#define LSI_DB_FUNCTION_HANDSHAKE                   0x42
#define LSI_DB_FUNCTION_REPLY_FRAME_REMOVAL         0x43
#define LSI_DB_FUNCTION_HOST_PAGEBUF_ACCESS_CONTROL 0x44

typedef struct PACKED FORCE_ALIGNMENT(sizeof(UINT32)) _LSI_ULTRA320_IOC_FACTS_REQUEST{
    UINT8   Function;
}LSI_ULTRA320_IOC_FACTS_REQUEST, * PLSI_ULTRA320_IOC_FACTS_REQUEST;

typedef struct PACKED FORCE_ALIGNMENT(sizeof(UINT32)) _LSI_ULTRA320_IOC_FACTS_REPLY{
    UINT16  MsgVersion; 
    UINT8   MsgLength; 
}LSI_ULTRA320_IOC_FACTS_REPLY, * PLSI_ULTRA320_IOC_FACTS_REPLY;


//5.3.1

#endif