#ifndef _DRSD_3D_H
#define _DRSD_3D_H
#include <DRSD.h>
#ifdef __cplusplus
extern "C"{
#endif

typedef enum {
    DRSD_3D_FEATURE_LEVEL_1_0_GENERIC = 0,
    DRSD_3D_FEATURE_LEVEL_1_0_CORE,
    DRSD_3D_FEATURE_LEVEL_9_1,
    DRSD_3D_FEATURE_LEVEL_9_2,
    DRSD_3D_FEATURE_LEVEL_9_3,
    DRSD_3D_FEATURE_LEVEL_10_0,
    DRSD_3D_FEATURE_LEVEL_10_1,
    DRSD_3D_FEATURE_LEVEL_11_0,
    DRSD_3D_FEATURE_LEVEL_11_1,
    DRSD_3D_FEATURE_LEVEL_12_0,
    DRSD_3D_FEATURE_LEVEL_12_1,
    DRSD_3D_FEATURE_LEVEL_12_2,
}DRSD_3D_FEATURE_LEVEL;

typedef DRSD_3D_FEATURE_LEVEL* PDRSD_3D_FEATURE_LEVEL;

typedef enum {
    DRSD_3D_ROOT_SIGNATURE_VERSION_1 = 0x01,
    DRSD_3D_ROOT_SIGNATURE_VERSION_1_0 = 0x01,
    DRSD_3D_ROOT_SIGNATURE_VERSION_1_1 = 0x02,
    DRSD_3D_ROOT_SIGNATURE_VERSION_1_2,
}DRSD_3D_ROOT_SIGNATURE_VERSION;

typedef enum {
    DRSD_3D_SHADER_MODEL_NONE = 0,
    DRSD_3D_SHADER_MODEL_5_1 = 0x51,
    DRSD_3D_SHADER_MODEL_6_0 = 0x60,
    DRSD_3D_SHADER_MODEL_6_1 = 0x61,
    DRSD_3D_SHADER_MODEL_6_2 = 0x62,
    DRSD_3D_SHADER_MODEL_6_3 = 0x63,
    DRSD_3D_SHADER_MODEL_6_4 = 0x64,
    DRSD_3D_SHADER_MODEL_6_5 = 0x65,
    DRSD_3D_SHADER_MODEL_6_6 = 0x66,
    DRSD_3D_SHADER_MODEL_6_7 = 0x67,
    DRSD_3D_SHADER_MODEL_6_8 = 0x68,
    DRSD_3D_SHADER_MODEL_6_9 = 0x69,
    DRSD_3D_HIGHEST_SHADER_MODEL,
}DRSD_3D_SHADER_MODEL;

typedef enum {
    DRSD_3D_AUTO_BREADCRUMB_OP_SETMARKER = 0,
    DRSD_3D_AUTO_BREADCRUMB_OP_BEGINEVENT,
    DRSD_3D_AUTO_BREADCRUMB_OP_ENDEVENT,
    DRSD_3D_AUTO_BREADCRUMB_OP_DRAWINSTANCED,
    DRSD_3D_AUTO_BREADCRUMB_OP_DRAWINDEXEDINSTANCED,
    DRSD_3D_AUTO_BREADCRUMB_OP_EXECUTEINDIRECT,
    DRSD_3D_AUTO_BREADCRUMB_OP_DISPATCH,
    DRSD_3D_AUTO_BREADCRUMB_OP_COPYBUFFERREGION,
    DRSD_3D_AUTO_BREADCRUMB_OP_COPYTEXTUREREGION,
    DRSD_3D_AUTO_BREADCRUMB_OP_COPYRESOURCE,
    DRSD_3D_AUTO_BREADCRUMB_OP_COPYTILES,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCE,
    DRSD_3D_AUTO_BREADCRUMB_OP_CLEARRENDERTARGETVIEW,
    DRSD_3D_AUTO_BREADCRUMB_OP_CLEARUNORDEREDACCESSVIEW,
    DRSD_3D_AUTO_BREADCRUMB_OP_CLEARDEPTHSTENCILVIEW,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOURCEBARRIER,
    DRSD_3D_AUTO_BREADCRUMB_OP_EXECUTEBUNDLE,
    DRSD_3D_AUTO_BREADCRUMB_OP_PRESENT,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOLVEQUERYDATA,
    DRSD_3D_AUTO_BREADCRUMB_OP_BEGINSUBMISSION,
    DRSD_3D_AUTO_BREADCRUMB_OP_ENDSUBMISSION,
    DRSD_3D_AUTO_BREADCRUMB_OP_DECODEFRAME,
    DRSD_3D_AUTO_BREADCRUMB_OP_PROCESSFRAMES,
    DRSD_3D_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT,
    DRSD_3D_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT64,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCEREGION,
    DRSD_3D_AUTO_BREADCRUMB_OP_WRITEBUFFERIMMEDIATE,
    DRSD_3D_AUTO_BREADCRUMB_OP_DECODEFRAME1,
    DRSD_3D_AUTO_BREADCRUMB_OP_SETPROTECTEDRESOURCESESSION,
    DRSD_3D_AUTO_BREADCRUMB_OP_DECODEFRAME2,
    DRSD_3D_AUTO_BREADCRUMB_OP_PROCESSFRAMES1,
    DRSD_3D_AUTO_BREADCRUMB_OP_BUILDRAYTRACINGACCELERATIONSTRUCTURE,
    DRSD_3D_AUTO_BREADCRUMB_OP_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO,
    DRSD_3D_AUTO_BREADCRUMB_OP_COPYRAYTRACINGACCELERATIONSTRUCTURE,
    DRSD_3D_AUTO_BREADCRUMB_OP_DISPATCHRAYS,
    DRSD_3D_AUTO_BREADCRUMB_OP_INITIALIZEMETACOMMAND,
    DRSD_3D_AUTO_BREADCRUMB_OP_EXECUTEMETACOMMAND,
    DRSD_3D_AUTO_BREADCRUMB_OP_ESTIMATEMOTION,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOLVEMOTIONVECTORHEAP,
    DRSD_3D_AUTO_BREADCRUMB_OP_SETPIPELINESTATE1,
    DRSD_3D_AUTO_BREADCRUMB_OP_INITIALIZEEXTENSIONCOMMAND,
    DRSD_3D_AUTO_BREADCRUMB_OP_EXECUTEEXTENSIONCOMMAND,
    DRSD_3D_AUTO_BREADCRUMB_OP_DISPATCHMESH,
    DRSD_3D_AUTO_BREADCRUMB_OP_ENCODEFRAME,
    DRSD_3D_AUTO_BREADCRUMB_OP_RESOLVEENCODEROUTPUTMETADATA,
    DRSD_3D_AUTO_BREADCRUMB_OP_BARRIER,
    DRSD_3D_AUTO_BREADCRUMB_OP_BEGIN_COMMAND_LIST,
    DRSD_3D_AUTO_BREADCRUMB_OP_DISPATCHGRAPH,
    DRSD_3D_AUTO_BREADCRUMB_OP_SETPROGRAM,
    DRSD_3D_AUTO_BREADCRUMB_OP_PROCESSFRAMES2
}DRSD_3D_AUTO_BREADCRUMB_OP;



#ifdef __cplusplus
}
#endif
#endif