#ifndef _DRSD_3D_H
#define _DRSD_3D_H
#include <DRSD.h>
#ifdef __cplusplus
extern "C"{
#endif

typedef enum {
    DRSD_3D_FEATURE_LEVEL_1_0_GENERIC = 0,
    DRSD_3D_FEATURE_LEVEL_1_0_CORE,
    DRSD_3D_FEATURE_LEVEL_9_1,
    DRSD_3D_FEATURE_LEVEL_9_2,
    DRSD_3D_FEATURE_LEVEL_9_3,
    DRSD_3D_FEATURE_LEVEL_10_0,
    DRSD_3D_FEATURE_LEVEL_10_1,
    DRSD_3D_FEATURE_LEVEL_11_0,
    DRSD_3D_FEATURE_LEVEL_11_1,
    DRSD_3D_FEATURE_LEVEL_12_0,
    DRSD_3D_FEATURE_LEVEL_12_1,
    DRSD_3D_FEATURE_LEVEL_12_2,
}DRSD_3D_FEATURE_LEVEL;

typedef DRSD_3D_FEATURE_LEVEL* PDRSD_3D_FEATURE_LEVEL;

#ifdef __cplusplus
}
#endif
#endif