#ifndef _KERNEL_SECURITY_H
#define _KERNEL_SECURITY_H

#include <cstdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef DWORD ACCESS_MASK, * PACCESS_MASK;
typedef PVOID PSECURITY_DESCRIPTOR;

#define ACCESS_MASK_OBJSPEC_MASK        0xFFFF
#define ACCESS_MASK_OBJSPEC_SHIFT       0x00
#define ACCESS_MASK_OBJSPEC             (ACCESS_MASK_OBJSPEC_MASK << ACCESS_MASK_OBJSPEC_SHIFT)

#define ACCESS_MASK_STD_RIGHTS_MASK     0xFF
#define ACCESS_MASK_STD_RIGHTS_SHIFT    16
#define ACCESS_MASK_STD_RIGHTS          (ACCESS_MASK_STD_RIGHTS_MASK << ACCESS_MASK_STD_RIGHTS_SHIFT)
#define     STD_ACCESS_DELETE           (1UL << 16)
#define     STD_ACCESS_READ_CONTROL     (1UL << 17)
#define     STD_ACCESS_WRITE_DAC        (1UL << 18)
#define     STD_ACCESS_WRITE_OWNER      (1UL << 19)
#define     STD_ACCESS_SYNCHRONIZE      (1UL << 20)
#define     STD_RIGHTS_REQUIRED         (0xFUL << 16)
#define     STD_RIGHTS_ALL              (0x1FUL << 16)
#define     STD_RIGHTS_READ             (STD_ACCESS_READ_CONTROL)
#define     STD_RIGHTS_WRITE            (STD_ACCESS_READ_CONTROL)
#define     STD_RIGHTS_EXECUTE          (STD_ACCESS_READ_CONTROL)
#define ACCESS_MASK_GENERIC_MASK        (0x0FULL << 28)
#define ACCESS_MASK_GENERIC_ALL         (1UL << 28)
#define ACCESS_MASK_GENERIC_EXECUTE     (1UL << 29)
#define ACCESS_MASK_GENERIC_WRITE       (1UL << 30)
#define ACCESS_MASK_GENERIC_READ        (1UL << 31)

//#define PROCESS_TERMINATE           0x00000001
//#define PROCESS_CREATE_THREAD       0x00000002
//#define PROCESS_VM_OPERATION        0x00000008
//#define PROCESS_VM_READ             0x00000010
//#define PROCESS_VM_WRITE            0x00000020
//#define PROCESS_DUP_HANDLE          0x00000040
//#define PROCESS_CREATE_PROCESS      0x00000080
//#define PRCOESS_SET_QUOTA           0x00000100
//#define PROCESS_SET_INFORMATION     0x00000200
//#define PRCOESS_QUERY_INFORMATION   0x00000400
//#define PROCESS_SUSPEND_RESUME      0x00000800
//#define SYNCHRONIZE                 0x00100000
//#define PROCESS_ALL_ACCESS          0x001FFFFF   


#ifdef __cplusplus
}
#endif
#endif