#ifndef _XHCI_H
#define _XHCI_H
#define _KERNEL_MODULE_
#include <LouDDK.h>

//ASYNC for controll and bulk
//ISOCH for Interrupt and periodic

//BAR points to Cap Register and following is the operational regs
//XHCI Extended Cap register as well as runtime and doorbell is pointed from Cap and 

typedef struct PACKED _XHCI_CAPABILITIES_REGISTER{
    UINT8       CapLength;
    UINT8       Reserved1;
    UINT16      HciVersion;
    UINT32      HcsParams1;
    UINT32      HcsParams2;
    UINT32      HcsParams3;
    UINT32      HccParams1;
    UINT32      DoorbellOffset;
    UINT32      RuntimeRegOfffset;
    UINT32      HccParams2;
}XHCI_CAPABILITIES_REGISTER, * PXHCI_CAPABILITIES_REGISTER;

//HCSPARAMS1
#define XHCI_MAX_PORTS_MASK                     0xFF
#define XHCI_MAX_PORTS_SHIFT                    24
#define XHCI_MAX_PORTS                          (XHCI_MAX_PORTS_MASK << XHCI_MAX_PORTS_SHIFT) 
#define GET_XHCI_MAX_PORTS(x)                   ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams1 & XHCI_MAX_PORTS) >> XHCI_MAX_PORTS_SHIFT)
#define XHCI_MAX_INTERRUPTS_MASK                0x07FF
#define XHCI_MAX_INTERRUPTS_SHIFT               8
#define XHCI_MAX_INTERRUPTS                     (XHCI_MAX_INTERRUPTS_MASK << XHCI_MAX_INTERRUPTS_SHIFT)
#define GET_XHCI_MAX_INTERRUPTS(x)              ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams1 & XHCI_MAX_INTERRUPTS) >> XHCI_MAX_INTERRUPTS_SHIFT)
#define XHCI_MAX_DEVICE_SLOTS_MASK              0xFF
#define XHCI_MAX_DEVICE_SLOTS_SHIFT             0
#define XHCI_MAX_DEVICE_SLOTS                   (XHCI_MAX_DEVICE_SLOTS_MASK << XHCI_MAX_DEVICE_SLOTS_SHIFT)
#define GET_XHCI_MAX_DEVICE_SLOTS(x)            ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams1 & XHCI_MAX_PORTS_MASK) >> XHCI_MAX_INTERRUPTS_SHIFT)

//HCSPARAMS2
#define XHCI_MAX_SCRATCHPAD_BUFFERSLO_MASK      0xF8
#define XHCI_MAX_SCRATCHPAD_BUFFERSLO_SHIFT     27
#define XHCI_MAX_SCRATCHPAD_BUFFERSLO           (XHCI_SCRATCHPAD_BUFFERS_MASK << XHCI_SCRATCHPAD_BUFFERS_SHIFT)
#define GET_XHCI_MAX_SCRATCHPAD_BUFFERSLO(x)    ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams2 & XHCI_SCRATCHPAD_BUFFERS) >> XHCI_SCRATCHPAD_BUFFERS_SHIFT)
#define XHCI_SCRATCHPAD_RESTORE_MASK            1
#define XHCI_SCRATCHPAD_RESTORE_SHIFT           26
#define XHCI_SCRATCHPAD_RESTORE                 (XHCI_SCRATCHPAD_RESTORE_MASK << XHCI_SCRATCHPAD_RESTORE_SHIFT)
#define GET_XHCI_SCRATCHPAD_RESTORE(x)          ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams2 & XHCI_SCRATCHPAD_RESTORE) >> XHCI_SCRATCHPAD_RESTORE_SHIFT)
#define XHCI_MAX_SCRATCHPAD_BUFFERSHI_MASK      0x3E
#define XHCI_MAX_SCRATCHPAD_BUFFERSHI_SHIFT     21
#define XHCI_MAX_SCRATCHPAD_BUFFERSHI           (XHCI_MAX_SCRATCHPAD_BUFFERSHI_MASK << XHCI_MAX_SCRATCHPAD_BUFFERSHI_SHIFT)
#define GET_XHCI_MAX_SCRATCHPAD_BUFFERSHI(x)    ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams2 & XHCI_MAX_SCRATCHPAD_BUFFERSHI) >> XHCI_MAX_SCRATCHPAD_BUFFERSHI_SHIFT)
#define XHCI_MAX_ERST_MASK                      0x0F
#define XHCI_MAX_ERST_SHIFT                     4
#define XHCI_MAX_ERST                           (XHCI_MAX_ERST_MASK << XHCI_MAX_ERST_SHIFT)
#define XHCI_IST_MASK                           4
#define XHCI_IST_SHIFT                          0x0F
#define XHCI_IST                                (XHCI_IST_MASK << XHCI_IST_SHIFT)

//HCSPARAMS3
#define XHCI_U2_DEV_EXIT_LATENCY_MASK           0xFF
#define XHCI_U2_DEV_EXIT_LATENCY_SHIFT          8
#define XHCI_U2_DEV_EXIT_LATENCY                (XHCI_U2_DEV_EXIT_LATENCY_MASK << XHCI_U2_DEV_EXIT_LATENCY_SHIFT)
#define GET_XHCI_U2_DEV_EXIT_LATENCY(x)         ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams3 & XHCI_U2_DEV_EXIT_LATENCY) >> XHCI_U2_DEV_EXIT_LATENCY_SHIFT)
#define XHCI_U1_DEV_EXIT_LATENCY_MASK           0xFF
#define XHCI_U1_DEV_EXIT_LATENCY_SHIFT          0
#define XHCI_U1_DEV_EXIT_LATENCY                (XHCI_U2_DEV_EXIT_LATENCY_MASK << XHCI_U1_DEV_EXIT_LATENCY_SHIFT)
#define GET_XHCI_U1_DEV_EXIT_LATENCY(x)         ((((PXHCI_CAPABILITIES_REGISTER)x)->HcsParams3 & XHCI_U1_DEV_EXIT_LATENCY) >> XHCI_U1_DEV_EXIT_LATENCY_SHIFT)



#endif