#ifndef _ATA_CORE_H
#define _ATA_CORE_H

#include <cstdlib.h>
#include <Modulation.h>
#include <kernel/threads.h>

#define STANDARD_ATA_COMMAND_PACKET \
    union{ \
        UINT8   Features; \
        UINT8   Error; \
    }; \
    UINT8       SectorCount; \
    UINT8       LbaLow; \
    UINT8       LbaMid; \
    UINT8       LbaHigh; \
    UINT8       Device; \
    union{ \
        UINT8   Command; \
        UINT8   Status; \
    }

#define STANDARD_ATA_COMMAND_PACKET_EX \
    union{ \
        UINT16   Features; \
        UINT8    Error; \
    }; \
    UINT16       SectorCount; \
    UINT16       LbaLow; \
    UINT16       LbaMid; \
    UINT16       LbaHigh; \
    UINT8        Device; \
    union{ \
        UINT8    Command; \
        UINT8    Status; \
    }

//Non Data Protocol

typedef struct PACKED _ATA_COMMAND_GENERIC{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_GENERIC, * PATA_COMMAND_GENERIC;

typedef struct PACKED _ATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE, * PATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE;

//Non Data Protocol
typedef struct PACKED _ATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE, * PATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE;

//Pio Data In Protocol
typedef struct PACKED _ATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE, * PATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE;

//Pio Data Out Protocol
typedef struct PACKED _ATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE, * PATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE;

//Pio Data Out Protocol
typedef struct PACKED _ATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE, * PATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE;

//Non Data Protocol
typedef struct PACKED _ATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE, * PATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_CHECK_POWER_MODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CHECK_POWER_MODE_STRUCTURE, * PATA_COMMAND_CHECK_POWER_MODE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_CONFIGURE_STREAM_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_CONFIGURE_STREAM_STRUCTURE, * PATA_COMMAND_CONFIGURE_STREAM_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE,
    ATA_COMMAND_DEVICE_CONFIGURATION_RESTORE_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_RESTORE_STRUCTURE, 
        ATA_COMMAND_DEVICE_CONFIGURATION_FREEZE_LOCK_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_FREEZE_LOCK_STRUCTURE, 
            ATA_COMMAND_DEVICE_CONFIGURATION_IDENTIFY_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_IDENTIFY_STRUCTURE,
                ATA_COMMAND_DEVICE_CONFIGURATION_SET_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_SET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DEVICE_RESET_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DEVICE_RESET_STRUCTURE, * PATA_COMMAND_DEVICE_RESET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE, * PATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC, * PATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC;

typedef struct PACKED _ATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE, * PATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_FLUSH_CACHE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_FLUSH_CACHE_STRUCTURE, * PATA_COMMAND_FLUSH_CACHE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE, * PATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE, * PATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE, * PATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDLE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDLE_STRUCTURE, * PATA_COMMAND_IDLE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE, * PATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_EJECT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_EJECT_STRUCTURE, * PATA_COMMAND_MEDIA_EJECT_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_LOCK_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_LOCK_STRUCTURE, * PATA_COMMAND_MEDIA_LOCK_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_UNLOCK_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_UNLOCK_STRUCTURE, * PATA_COMMAND_MEDIA_UNLOCK_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_NOP_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_NOP_STRUCTURE, * PATA_COMMAND_NOP_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_PACKET_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_PACKET_STRUCTURE, * PATA_COMMAND_PACKET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_BUFFER_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_BUFFER_STRUCTURE, * PATA_COMMAND_READ_BUFFER_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_DMA_STRUCTURE, * PATA_COMMAND_READ_DMA_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_EXT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_READ_DMA_EXT_STRUCTURE, * PATA_COMMAND_READ_DMA_EXT_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_QUEUED_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_DMA_QUEUED_STRUCTURE, * PATA_COMMAND_READ_DMA_QUEUED_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE, * PATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE;



#define ATA_COMMAND_CODE_NOP                                    0x00
#define ATA_COMMAND_CODE_CFA_REQUEST_EXTENDED_ERROR             0x03
#define ATA_COMMAND_CODE_DEVICE_RESET                           0x08
#define ATA_COMMAND_CODE_READ_SECTOR                            0x20
#define ATA_COMMAND_CODE_READ_SECOTRS_EX                        0x24
#define ATA_COMMAND_CODE_READ_DMA_EXT                           0x25
#define ATA_COMMAND_CODE_READ_DMA_QUEUED_EXT                    0x26
#define ATA_COMMAND_CODE_READ_NATIVE_MAX_ADDRESS_EXT            0x27
#define ATA_COMMAND_CODE_READ_MULTIPLE_EXT                      0x29
#define ATA_COMMAND_CODE_READ_STREAM_DMA                        0x2A
#define ATA_COMMAND_CODE_READ_STREAM_PIO                        0x2B
#define ATA_COMMAND_CODE_READ_LOG_EXT                           0x2F
#define ATA_COMMAND_CODE_WRITE_SECTOR                           0x30 
#define ATA_COMMAND_CODE_WRITE_SECTOR_EXT                       0x34
#define ATA_COMMAND_CODE_WRITE_DMA_EXT                          0x35
#define ATA_COMMAND_CODE_WRITE_DMA_QUEUED_EXT                   0x36
#define ATA_COMMAND_CODE_SET_MAX_ADDRESS_EXT                    0x37
#define ATA_COMMAND_CODE_CFA_WRITE_SECTORS_WOUT_ERASE           0x38
#define ATA_COMMAND_CODE_WRITE_MULTIPLE_EXT                     0x39
#define ATA_COMMAND_CODE_READ_VERIFY_SECTOR                     0x40
#define ATA_COMMAND_CODE_READ_VERIFY_SECTOR_EXT                 0x42
#define ATA_COMMAND_CODE_CONFIGURE_STREAM                       0x51
#define ATA_COMMAND_CODE_SEEK                                   0x70
#define ATA_COMMAND_CODE_CFA_TRANSLATE_SECTOR                   0x87
#define ATA_COMMAND_CODE_EXECUTE_DEVICE_DIAGNOSTICS             0x90
#define ATA_COMMAND_CODE_DOWNLOAD_MICROCODE                     0x92
#define ATA_COMMAND_CODE_PACKET                                 0xA0
#define ATA_COMMAND_CODE_IDENTIFY_PACKET_DEVICE                 0xA1
#define ATA_COMMAND_CODE_SERVICE                                0xA2
#define ATA_COMMAND_CODE_SMART_DISABLE_OPERATIONS               0xB0
#define ATA_COMMAND_CODE_SMART_TOGGLE_AUTOSAVE                  0xB0
#define ATA_COMMAND_CODE_SMART_ENABLE_OPERATIONS                0xB0
#define ATA_COMMAND_CODE_SMART_EXECUTE_OFF_LINE                 0xB0
#define ATA_COMMAND_CODE_SMART_READ_DATA                        0xB0
#define ATA_COMMAND_CODE_SMART_READ_LOG_SECTOR                  0xB0
#define ATA_COMMAND_CODE_SMART_RETURN_STATUS                    0xB0
#define ATA_COMMAND_CODE_SMART_WRITE_LOG_SECTOR                 0xB0
#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION                   0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_FREEZE_LOCK     0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_IDENTIFY        0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_RESTORE         0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_SET             0xB1
#define ATA_COMMAND_CODE_CFA_ERASE_SECTORS                      0xC0
#define ATA_COMMAND_CODE_READ_MULTIPLE                          0xC4
#define ATA_COMMAND_CODE_WRITE_MULTIPLE                         0xC5
#define ATA_COMMAND_CODE_SET_MULTIPLE_MODE                      0xC6
#define ATA_COMMAND_CODE_READ_DMA_QUEUED                        0xC7
#define ATA_COMMAND_CODE_READ_DMA                               0xC8
#define ATA_COMMAND_CODE_WRITE_DMA                              0xCA
#define ATA_COMMAND_CODE_WRITE_DMA_QUEUED                       0xCC
#define ATA_COMMAND_CODE_CFA_WRITE_MULTIPLE_WO_ERASE            0xCD
#define ATA_COMMAND_CODE_CHECK_MEDIA_CARD_TYPE                  0xD1
#define ATA_COMMAND_CODE_GET_MEDIA_STATUS                       0xDA
#define ATA_COMMAND_CODE_MEDIA_LOCK                             0xDE
#define ATA_COMMAND_CODE_MEDIA_UNLOCK                           0xDF
#define ATA_COMMAND_CODE_STANDBY_IMMEDIATE                      0xE0
#define ATA_COMMAND_CODE_IDLE_IMMEDIATE                         0xE1
#define ATA_COMMAND_CODE_STANDBY                                0xE2
#define ATA_COMMAND_CODE_IDLE                                   0xE3
#define ATA_COMMAND_CODE_READ_BUFFER                            0xE4
#define ATA_COMMAND_CODE_CHECK_POWER_MODE                       0xE5
#define ATA_COMMAND_CODE_SLEEP                                  0xE6
#define ATA_COMMAND_CODE_FLUSH_CACHE                            0xE7
#define ATA_COMMAND_CODE_WRITE_BUFFER                           0xE8
#define ATA_COMMAND_CODE_FLUSH_CACHE_EXT                        0xEA
#define ATA_COMMAND_CODE_IDENTIFY_DEVICE                        0xEC
#define ATA_COMMAND_CODE_MEDIA_EJECT                            0xED
#define ATA_COMMAND_CODE_SET_FEATURES                           0xEF
#define ATA_COMMAND_CODE_SECURITY_SET_PASWORD                   0xF1
#define ATA_COMMAND_CODE_SECURITY_UNLOCK                        0xF2
#define ATA_COMMAND_CODE_SECURITY_ERASE_PREPARE                 0xF3
#define ATA_COMMAND_CODE_SECURITY_ERASE_UNIT                    0xF4
#define ATA_COMMAND_CODE_SECURITY_FREEZE_LOCK                   0xF5
#define ATA_COMMAND_CODE_SECURITY_DISABLE_PASSWORD              0xF6
#define ATA_COMMAND_CODE_READ_NATIVE_MAX_ADDRESS                0xF8
#define ATA_COMMAND_CODE_SET_MAX_ADDRESS                        0xF9

typedef enum {
    ATA_DEVICE_COMMAND_STATUS_SUCCESS = 0,
    ATA_DEVICE_COMMAND_STATUS_TRY_AGAIN_LATER,
    ATA_DEVICE_COMMAND_STATUS_PANIC,
    ATA_DEVICE_COMMAND_STATUS_RESET,
    ATA_DEVICE_COMMAND_STATUS_NEEDS_RESET,
    ATA_DEVICE_COMMAND_STATUS_ABORTED,
    ATA_DEVICE_COMMAND_STATUS_NOT_SUPPORTED,
    ATA_DEVICE_COMMAND_STATUS_MEDIA_ERROR,
    ATA_DEVICE_COMMAND_STATUS_USER_ACCESSABLE_ADDRESS_NOT_FOUND,

}ATA_DEVICE_COMMAND_STATUS;

#define ATA_CMDBLK_PREV_ENCODE_SHIFT            8
#define ATA_CMDBLK_PREV_ENCODE_MASK             0xFF
#define ATA_CMDBLK_CURR_ENCODE_SHIFT            0
#define ATA_CMDBLK_CURR_ENCODE_MASK             0xFF

#define ATA_CMDBLK_ENCODE_PREV_VALUE(Value) ((UINT16)Value << ATA_CMDBLK_PREV_ENCODE_SHIFT)
#define ATA_CMDBLK_ENCODE_CURR_VALUE(Value) ((UINT16)Value << ATA_CMDBLK_CURR_ENCODE_SHIFT)
#define ATA_CMDBLK_DECODE_PREV_VALUE(Value) ((Value >> ATA_CMDBLK_PREV_ENCODE_SHIFT) & ATA_CMDBLK_PREV_ENCODE_MASK)
#define ATA_CMDBLK_DECODE_CURR_VALUE(Value) ((Value >> ATA_CMDBLK_CURR_ENCODE_SHIFT) & ATA_CMDBLK_CURR_ENCODE_MASK)

struct _ATA_PORT_DEVICE_OBJECT;
struct _ATA_HOST_OPERATIONS;
struct _ATA_HOST_DEVICE_OBJECT;
struct _ATA_PORT_OPERATIONS;

#define ATA_ENDPOINT_DEVCAP_ATAPI                           (1ULL << 0)
#define ATA_ENDPOINT_DEVCAP_REMOVEABLE                      (1ULL << 1)
//RESERVED                                                  (1ULL << 2)
#define ATA_ENDPOINT_DEVCAP_DMA_SUPPORT                     (1ULL << 3)
#define ATA_ENDPOINT_DEVCAP_IORDY_SUPPORT                   (1ULL << 4)
#define ATA_ENDPOINT_DEVCAP_LBA_SUPPORT                     (1ULL << 5)
#define ATA_ENDPOINT_DEVCAP_IORDY_DISABLED                  (1ULL << 6)
#define ATA_ENDPOINT_DEVCAP_OVERLAP_SUPPORT                 (1ULL << 7)
//RESERVED                                                  (1ULL << 8)
#define ATA_ENDPOINT_DEVCAP_QUEUE_SUPPORT                   (1ULL << 9)
#define ATA_ENDPOINT_DEVCAP_INTERLEAVE_DMA                  (1ULL << 10)
#define ATA_ENDPOINT_DEVCAP_NOP_SUPPORT                     (1ULL << 11)
#define ATA_ENDPOINT_DEVCAP_READBUFF_SUPPORT                (1ULL << 12)
#define ATA_ENDPOINT_DEVCAP_WRITEBUFF_SUPPORT               (1ULL << 13)
#define ATA_ENDPOINT_DEVCAP_HPAFS_SUPPORT                   (1ULL << 14) //Host Protected Area Feature Set
#define ATA_ENDPOINT_DEVCAP_DEVICE_RESET_SUPPORT            (1ULL << 15)
#define ATA_ENDPOINT_DEVCAP_SERVICE_SUPPORT                 (1ULL << 16)
#define ATA_ENDPOINT_DEVCAP_RELEASE_INTERRUPT_SUPPORT       (1ULL << 17)
#define ATA_ENDPOINT_DEVCAP_LOOK_AHEAD_SUPPORT              (1ULL << 18)
#define ATA_ENDPOINT_DEVCAP_WRITE_CACHE_SUPPORT             (1ULL << 19)
#define ATA_ENDPOINT_DEVCAP_PACKET_SUPPORT                  (1ULL << 20)
#define ATA_ENDPOINT_DEVCAP_PM_SUPPORT                      (1ULL << 21)
#define ATA_ENDPOINT_DEVCAP_REMOVEABLE_MEDIA_FEATURE        (1ULL << 22)
#define ATA_ENDPOINT_DEVCAP_SECURITY_MODE_SUPPORT           (1ULL << 23)
#define ATA_ENDPOINT_DEVCAP_SMART_SUPPORT                   (1ULL << 24)
#define ATA_ENDPOINT_DEVCAP_FLUSH_CACHE_SUPPORT             (1ULL << 25)
#define ATA_ENDPOINT_DEVCAP_DEVCONF_OVERLAY_SUPPORT         (1ULL << 26)
#define ATA_ENDPOINT_DEVCAP_SETMAX_SECURITY_SUPPORT         (1ULL << 27)
#define ATA_ENDPOINT_DEVCAP_SETFEAT_SUPPORT                 (1ULL << 28)
#define ATA_ENDPOINT_DEVCAP_POWER_UP_SUPPORT                (1ULL << 29)
#define ATA_ENDPOINT_DEVCAP_DOWNLOAD_MICROCODE_SUPPORT      (1ULL << 30)

//start here 127
#define ATA_ENDPOINT_DEVCAP_REMOVEABLE_MEDIA_STAT_FEAT      (1ULL << 31)
#define ATA_ENDPOINT_DEVCAP_ENHANCED_SECURITY_ERASE_FEAT    (1ULL << 32)
#define ATA_ENDPOINT_DEVCAP_SECURITY_COUNT_EXPIRED          (1ULL << 33)
#define ATA_ENDPOINT_DEVCAP_SECURITY_LEVEL                  (1ULL << 34)
#define ATA_ENDPOINT_DEVCAP_SECURITY_FROZEN                 (1ULL << 35)
#define ATA_ENDPOINT_DEVCAP_SECURITY_LOCKED                 (1ULL << 36)
#define ATA_ENDPOINT_DEVCAP_SECURITY_ENABLED                (1ULL << 37)
#define ATA_ENDPOINT_DEVCAP_SECURITY_SUPPORT                (1ULL << 38)


typedef struct _ATA_ENDPOINT_DEVICE_OBJECT{
    struct _ATA_PORT_DEVICE_OBJECT* Port;
    UINT8                           ChannelDev;
    UINT64                          DeviceCap;
    UINT32                          MaxLba;
    UINT32                          SectorSize;
    UINT8                           MaxMDmaSupport;
    UINT8                           MDmaSelected;
    UINT8                           PioModesSupported;
    UINT8                           MaxQueueDepth;
    UINT8                           MaxSpecVersionSupport;
    UINT8                           PacketSize;
    UINT8                           MaxUDmaSupport;
    UINT8                           UDmaSelected;
    CHAR                            SerialNumber[21];
    CHAR                            FirmwareVersion[9];
    CHAR                            ModelNumber[41];
}ATA_ENDPOINT_DEVICE_OBJECT, * PATA_ENDPOINT_DEVICE_OBJECT;

#define ATA_PORT_FLAGS_NO_IRQS  (1 << 0)

typedef struct _ATA_PORT_DEVICE_OBJECT{
    SIZE                            PortNumber;
    mutex_t*                        ChannelLock;
    ListHeader                      QueuedCommands;
    PLOUSINE_DMA_DEVICE             OptionalDmaDevice;
    struct _ATA_HOST_DEVICE_OBJECT* HostDevice;
    struct _ATA_PORT_OPERATIONS*    Operations;
    ULONG                           PortFlags;
    PVOID                           PortPrivateData;
    PTHREAD                         CommandWorkerThread;
}ATA_PORT_DEVICE_OBJECT, * PATA_PORT_DEVICE_OBJECT;

#define ATA_COMMAND_PACKET_FLAGS_DMA        (1UL << 0)
#define ATA_COMMAND_PACKET_FLAGS_TRAN_CMD   (1UL << 1)
#define ATA_COMMAND_PACKET_FLAGS_OUT_CMD    (1UL << 2)
#define ATA_COMMAND_PACKET_FLAGS_POLL       (1UL << 3)
#define ATA_COMMAND_PACKET_FLAGS_PACKET_CMD (1UL << 4)
#define ATA_COMMAND_PACKET_FLAGS_EXT_CMD    (1UL << 5)


typedef struct _ATA_COMMAND_PACKET{
    LOUSTATUS                   CommandStatus;
    LOUSTATUS                   CleanupStatus;
    ATOMIC_BOOLEAN              CommandDone;
    ListHeader                  QueuedCommands;
    ULONG                       CommandFlags;
    SIZE                        PacketSize;
    UINT8                       PacketData[16];
    SIZE                        PioSize;
    PVOID                       CommandPrivateData;
    union{
        PVOID                   PioDataIn;
        PVOID                   PioDataOut;
        PLOUSINE_DMA_TRANSFER   DmaDataIn;
        PLOUSINE_DMA_TRANSFER   DmaDataOut;
    };
    union{
        struct PACKED{
                                STANDARD_ATA_COMMAND_PACKET;
        }                       Packet;
        struct PACKED{
                                STANDARD_ATA_COMMAND_PACKET_EX;
        }                       PacketEx;
    };
}ATA_COMMAND_PACKET, * PATA_COMMAND_PACKET;

typedef struct _ATA_PORT_OPERATIONS{
    LOUSTATUS (*AtaPortDevicePrepCommand)(PATA_PORT_DEVICE_OBJECT PortDevice, PATA_COMMAND_PACKET CommandPacket);
    LOUSTATUS (*AtaPortDeviceIssueCommand)(PATA_PORT_DEVICE_OBJECT PortDevice, PATA_COMMAND_PACKET CommandPacket);
    LOUSTATUS (*AtaPortDeviceGetCommandStatus)(PATA_PORT_DEVICE_OBJECT PortDevice, PATA_COMMAND_PACKET CommandPacket);
    LOUSTATUS (*AtaPortDeviceCleanupCommand)(PATA_PORT_DEVICE_OBJECT PortDevice, PATA_COMMAND_PACKET CommandPacket);
    LOUSTATUS (*AtaPortDeviceReset)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceStart)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceStop)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceWake)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceSleep)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDevicePowerUp)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDevicePowerDown)(PATA_PORT_DEVICE_OBJECT PortDevice);
}ATA_PORT_OPERATIONS, * PATA_PORT_OPERATIONS;

#define ATA_HOST_FLAGS_SUPPORTS_PIO     (1UL << 0)
#define ATA_HOST_FLAGS_SUPPORTS_DMA     (1UL << 1)
#define ATA_HOST_FLAGS_DUAL_CHANNEL     (1UL << 2)

typedef struct _ATA_HOST_DEVICE_OBJECT{
    PPCI_DEVICE_OBJECT              PDEV;
    mutex_t*                        ChannelLocks;
    struct _ATA_HOST_OPERATIONS*    Operations;
    ULONG                           HostFlags;
    UINT8                           MaxMDmaSupport;
    UINT8                           MaUMDmaSupport;
    UINT8                           MaxPioSupport;
    UINT8                           MDmaSelected;
    UINT8                           UDmaSelected;
    UINT8                           PioSelected;
    PVOID                           HostPrivateData;
    SIZE                            PortCount;
    PATA_PORT_DEVICE_OBJECT         PortDevices;
    PTHREAD*                        PortIoManager;
}ATA_HOST_DEVICE_OBJECT, * PATA_HOST_DEVICE_OBJECT;

typedef struct _ATA_HOST_OPERATIONS{
    LOUSTATUS (*AtaHostDeviceReset)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceStart)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceStop)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceWake)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceSleep)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDevicePowerUp)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDevicePowerDown)(PATA_HOST_DEVICE_OBJECT HostDevice);
}ATA_HOST_OPERATIONS, * PATA_HOST_OPERATIONS;

#define ForEachAtaPort(Host, Position, i) \
    for( \
        i = 0, Position = &Host->PortDevices[i]; \
        i < Host->PortCount; \
        i++ , Position = &Host->PortDevices[i] \
    ) 

#ifdef ATA_CORE_INTERNALS_H

DRIVER_EXPORT LOUSTATUS AtaCoreAllocateHostDevice(PATA_HOST_DEVICE_OBJECT* HostDeviceOut, SIZE PrivateDataSize, SIZE PrivateDataAlignment);
DRIVER_EXPORT void AtaCoreFreeHostDevice(PATA_HOST_DEVICE_OBJECT HostDevice);
DRIVER_EXPORT LOUSTATUS AtaCoreAllocatePortsForHost(PATA_HOST_DEVICE_OBJECT HostDevice, SIZE PortCount, SIZE PrivateDataSize, SIZE PrivateDataAlignment);
DRIVER_EXPORT void AtaCoreFreeAtaPortsFromHost(PATA_HOST_DEVICE_OBJECT HostDevice);
DRIVER_EXPORT LOUSTATUS AtaCoreRegisterAtaHostDevice(PATA_HOST_DEVICE_OBJECT NewHostDevice);

#else

DRIVER_IMPORT LOUSTATUS AtaCoreAllocateHostDevice(PATA_HOST_DEVICE_OBJECT* HostDeviceOut, SIZE PrivateDataSize, SIZE PrivateDataAlignment);
DRIVER_IMPORT void AtaCoreFreeHostDevice(PATA_HOST_DEVICE_OBJECT HostDevice);
DRIVER_IMPORT LOUSTATUS AtaCoreAllocatePortsForHost(PATA_HOST_DEVICE_OBJECT HostDevice, SIZE PortCount, SIZE PrivateDataSize, SIZE PrivateDataAlignment);
DRIVER_IMPORT void AtaCoreFreeAtaPortsFromHost(PATA_HOST_DEVICE_OBJECT HostDevice);
DRIVER_IMPORT LOUSTATUS AtaCoreRegisterAtaHostDevice(PATA_HOST_DEVICE_OBJECT NewHostDevice);

#endif


#include "Ahci.h"

#endif