#ifndef _ATA_CORE_H
#define _ATA_CORE_H

#include <cstdlib.h>

#define STANDARD_ATA_COMMAND_PACKET \
    union{ \
        UINT8   Features; \
        UINT8   Error; \
    }; \
    UINT8       SectorCount; \
    UINT8       LbaLow; \
    UINT8       LbaMid; \
    UINT8       LbaHigh; \
    UINT8       Device; \
    union{ \
        UINT8   Command; \
        UINT8   Status; \
    }

#define STANDARD_ATA_COMMAND_PACKET_EX \
    union{ \
        UINT16   Features; \
        UINT8    Error; \
    }; \
    UINT16       SectorCount; \
    UINT16       LbaLow; \
    UINT16       LbaMid; \
    UINT16       LbaHigh; \
    UINT8        Device; \
    union{ \
        UINT8    Command; \
        UINT8    Status; \
    }

//Non Data Protocol

typedef struct PACKED _ATA_COMMAND_GENERIC{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_GENERIC, * PATA_COMMAND_GENERIC;

typedef struct PACKED _ATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE, * PATA_COMMAND_CFA_ERASE_SECTORS_STRUCTURE;

//Non Data Protocol
typedef struct PACKED _ATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE, * PATA_COMMAND_CFA_REQUEST_EXTENDED_ERROR_CODE_STRUCTURE;

//Pio Data In Protocol
typedef struct PACKED _ATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE, * PATA_COMMAND_CFA_TRANSLATE_SECTOR_STRUCTURE;

//Pio Data Out Protocol
typedef struct PACKED _ATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE, * PATA_COMMAND_CFA_WRITE_MULTIPLE_WITHOUGHT_ERASE_STRUCTURE;

//Pio Data Out Protocol
typedef struct PACKED _ATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE, * PATA_COMMAND_CFA_WRITE_SECTORS_WITHOUGHT_ERASE_STRUCTURE;

//Non Data Protocol
typedef struct PACKED _ATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE, * PATA_COMMAND_CHECK_MEDIA_CARD_TYPE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_CHECK_POWER_MODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_CHECK_POWER_MODE_STRUCTURE, * PATA_COMMAND_CHECK_POWER_MODE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_CONFIGURE_STREAM_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_CONFIGURE_STREAM_STRUCTURE, * PATA_COMMAND_CONFIGURE_STREAM_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_STRUCTURE,
    ATA_COMMAND_DEVICE_CONFIGURATION_RESTORE_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_RESTORE_STRUCTURE, 
        ATA_COMMAND_DEVICE_CONFIGURATION_FREEZE_LOCK_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_FREEZE_LOCK_STRUCTURE, 
            ATA_COMMAND_DEVICE_CONFIGURATION_IDENTIFY_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_IDENTIFY_STRUCTURE,
                ATA_COMMAND_DEVICE_CONFIGURATION_SET_STRUCTURE, * PATA_COMMAND_DEVICE_CONFIGURATION_SET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DEVICE_RESET_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DEVICE_RESET_STRUCTURE, * PATA_COMMAND_DEVICE_RESET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE, * PATA_COMMAND_DOWNLOAD_MICROCODE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC, * PATA_COMMAND_EXECUTE_DEVICE_DIAGNOSTIC;

typedef struct PACKED _ATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE, * PATA_COMMAND_FLUSH_CACHE_EX_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_FLUSH_CACHE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_FLUSH_CACHE_STRUCTURE, * PATA_COMMAND_FLUSH_CACHE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE, * PATA_COMMAND_GET_MEDIA_STATUS_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE, * PATA_COMMAND_IDENTIFY_DEVICE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE, * PATA_COMMAND_IDENTIFY_PACKET_DEVICE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDLE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDLE_STRUCTURE, * PATA_COMMAND_IDLE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE, * PATA_COMMAND_IDLE_IMMEDIATE_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_EJECT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_EJECT_STRUCTURE, * PATA_COMMAND_MEDIA_EJECT_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_LOCK_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_LOCK_STRUCTURE, * PATA_COMMAND_MEDIA_LOCK_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_MEDIA_UNLOCK_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_MEDIA_UNLOCK_STRUCTURE, * PATA_COMMAND_MEDIA_UNLOCK_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_NOP_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_NOP_STRUCTURE, * PATA_COMMAND_NOP_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_PACKET_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_PACKET_STRUCTURE, * PATA_COMMAND_PACKET_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_BUFFER_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_BUFFER_STRUCTURE, * PATA_COMMAND_READ_BUFFER_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_DMA_STRUCTURE, * PATA_COMMAND_READ_DMA_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_EXT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_READ_DMA_EXT_STRUCTURE, * PATA_COMMAND_READ_DMA_EXT_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_QUEUED_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET;
}ATA_COMMAND_READ_DMA_QUEUED_STRUCTURE, * PATA_COMMAND_READ_DMA_QUEUED_STRUCTURE;

typedef struct PACKED _ATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE{
    STANDARD_ATA_COMMAND_PACKET_EX;
}ATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE, * PATA_COMMAND_READ_DMA_QUEUED_EXT_STRUCTURE;



#define ATA_COMMAND_CODE_NOP                                    0x00
#define ATA_COMMAND_CODE_CFA_REQUEST_EXTENDED_ERROR             0x03
#define ATA_COMMAND_CODE_DEVICE_RESET                           0x08
#define ATA_COMMAND_CODE_READ_SECTOR                            0x20
#define ATA_COMMAND_CODE_READ_SECOTRS_EX                        0x24
#define ATA_COMMAND_CODE_READ_DMA_EXT                           0x25
#define ATA_COMMAND_CODE_READ_DMA_QUEUED_EXT                    0x26
#define ATA_COMMAND_CODE_READ_NATIVE_MAX_ADDRESS_EXT            0x27
#define ATA_COMMAND_CODE_READ_MULTIPLE_EXT                      0x29
#define ATA_COMMAND_CODE_READ_STREAM_DMA                        0x2A
#define ATA_COMMAND_CODE_READ_STREAM_PIO                        0x2B
#define ATA_COMMAND_CODE_READ_LOG_EXT                           0x2F
#define ATA_COMMAND_CODE_WRITE_SECTOR                           0x30 
#define ATA_COMMAND_CODE_WRITE_SECTOR_EXT                       0x34
#define ATA_COMMAND_CODE_WRITE_DMA_EXT                          0x35
#define ATA_COMMAND_CODE_WRITE_DMA_QUEUED_EXT                   0x36
#define ATA_COMMAND_CODE_SET_MAX_ADDRESS_EXT                    0x37
#define ATA_COMMAND_CODE_CFA_WRITE_SECTORS_WOUT_ERASE           0x38
#define ATA_COMMAND_CODE_WRITE_MULTIPLE_EXT                     0x39
#define ATA_COMMAND_CODE_READ_VERIFY_SECTOR                     0x40
#define ATA_COMMAND_CODE_READ_VERIFY_SECTOR_EXT                 0x42
#define ATA_COMMAND_CODE_CONFIGURE_STREAM                       0x51
#define ATA_COMMAND_CODE_SEEK                                   0x70
#define ATA_COMMAND_CODE_CFA_TRANSLATE_SECTOR                   0x87
#define ATA_COMMAND_CODE_EXECUTE_DEVICE_DIAGNOSTICS             0x90
#define ATA_COMMAND_CODE_DOWNLOAD_MICROCODE                     0x92
#define ATA_COMMAND_CODE_PACKET                                 0xA0
#define ATA_COMMAND_CODE_IDENTIFY_PACKET_DEVICE                 0xA1
#define ATA_COMMAND_CODE_SERVICE                                0xA2
#define ATA_COMMAND_CODE_SMART_DISABLE_OPERATIONS               0xB0
#define ATA_COMMAND_CODE_SMART_TOGGLE_AUTOSAVE                  0xB0
#define ATA_COMMAND_CODE_SMART_ENABLE_OPERATIONS                0xB0
#define ATA_COMMAND_CODE_SMART_EXECUTE_OFF_LINE                 0xB0
#define ATA_COMMAND_CODE_SMART_READ_DATA                        0xB0
#define ATA_COMMAND_CODE_SMART_READ_LOG_SECTOR                  0xB0
#define ATA_COMMAND_CODE_SMART_RETURN_STATUS                    0xB0
#define ATA_COMMAND_CODE_SMART_WRITE_LOG_SECTOR                 0xB0
#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION                   0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_FREEZE_LOCK     0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_IDENTIFY        0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_RESTORE         0xB1
//#define ATA_COMMAND_CODE_DEVICE_CONFIGURATION_SET             0xB1
#define ATA_COMMAND_CODE_CFA_ERASE_SECTORS                      0xC0
#define ATA_COMMAND_CODE_READ_MULTIPLE                          0xC4
#define ATA_COMMAND_CODE_WRITE_MULTIPLE                         0xC5
#define ATA_COMMAND_CODE_SET_MULTIPLE_MODE                      0xC6
#define ATA_COMMAND_CODE_READ_DMA_QUEUED                        0xC7
#define ATA_COMMAND_CODE_READ_DMA                               0xC8
#define ATA_COMMAND_CODE_WRITE_DMA                              0xCA
#define ATA_COMMAND_CODE_WRITE_DMA_QUEUED                       0xCC
#define ATA_COMMAND_CODE_CFA_WRITE_MULTIPLE_WO_ERASE            0xCD
#define ATA_COMMAND_CODE_CHECK_MEDIA_CARD_TYPE                  0xD1
#define ATA_COMMAND_CODE_GET_MEDIA_STATUS                       0xDA
#define ATA_COMMAND_CODE_MEDIA_LOCK                             0xDE
#define ATA_COMMAND_CODE_MEDIA_UNLOCK                           0xDF
#define ATA_COMMAND_CODE_STANDBY_IMMEDIATE                      0xE0
#define ATA_COMMAND_CODE_IDLE_IMMEDIATE                         0xE1
#define ATA_COMMAND_CODE_STANDBY                                0xE2
#define ATA_COMMAND_CODE_IDLE                                   0xE3
#define ATA_COMMAND_CODE_READ_BUFFER                            0xE4
#define ATA_COMMAND_CODE_CHECK_POWER_MODE                       0xE5
#define ATA_COMMAND_CODE_SLEEP                                  0xE6
#define ATA_COMMAND_CODE_FLUSH_CACHE                            0xE7
#define ATA_COMMAND_CODE_WRITE_BUFFER                           0xE8
#define ATA_COMMAND_CODE_FLUSH_CACHE_EXT                        0xEA
#define ATA_COMMAND_CODE_IDENTIFY_DEVICE                        0xEC
#define ATA_COMMAND_CODE_MEDIA_EJECT                            0xED
#define ATA_COMMAND_CODE_SET_FEATURES                           0xEF
#define ATA_COMMAND_CODE_SECURITY_SET_PASWORD                   0xF1
#define ATA_COMMAND_CODE_SECURITY_UNLOCK                        0xF2
#define ATA_COMMAND_CODE_SECURITY_ERASE_PREPARE                 0xF3
#define ATA_COMMAND_CODE_SECURITY_ERASE_UNIT                    0xF4
#define ATA_COMMAND_CODE_SECURITY_FREEZE_LOCK                   0xF5
#define ATA_COMMAND_CODE_SECURITY_DISABLE_PASSWORD              0xF6
#define ATA_COMMAND_CODE_READ_NATIVE_MAX_ADDRESS                0xF8
#define ATA_COMMAND_CODE_SET_MAX_ADDRESS                        0xF9

typedef enum {
    ATA_DEVICE_COMMAND_STATUS_SUCCESS = 0,
    ATA_DEVICE_COMMAND_STATUS_TRY_AGAIN_LATER,
    ATA_DEVICE_COMMAND_STATUS_PANIC,
    ATA_DEVICE_COMMAND_STATUS_RESET,
    ATA_DEVICE_COMMAND_STATUS_NEEDS_RESET,
    ATA_DEVICE_COMMAND_STATUS_ABORTED,
    ATA_DEVICE_COMMAND_STATUS_NOT_SUPPORTED,
    ATA_DEVICE_COMMAND_STATUS_MEDIA_ERROR,
    ATA_DEVICE_COMMAND_STATUS_USER_ACCESSABLE_ADDRESS_NOT_FOUND,

}ATA_DEVICE_COMMAND_STATUS;

#define ATA_CMDBLK_PREV_ENCODE_SHIFT            8
#define ATA_CMDBLK_PREV_ENCODE_MASK             0xFF
#define ATA_CMDBLK_CURR_ENCODE_SHIFT            0
#define ATA_CMDBLK_CURR_ENCODE_MASK             0xFF

#define ATA_CMDBLK_ENCODE_PREV_VALUE(Value) ((UINT16)Value << ATA_CMDBLK_PREV_ENCODE_SHIFT)
#define ATA_CMDBLK_ENCODE_CURR_VALUE(Value) ((UINT16)Value << ATA_CMDBLK_CURR_ENCODE_SHIFT)
#define ATA_CMDBLK_DECODE_PREV_VALUE(Value) ((Value >> ATA_CMDBLK_PREV_ENCODE_SHIFT) & ATA_CMDBLK_PREV_ENCODE_MASK)
#define ATA_CMDBLK_DECODE_CURR_VALUE(Value) ((Value >> ATA_CMDBLK_CURR_ENCODE_SHIFT) & ATA_CMDBLK_CURR_ENCODE_MASK)

#define ATA_HOST_FLAGS_SUPPORTS_PIO     (1UL << 0)
#define ATA_HOST_FLAGS_SUPPORTS_DMA     (1UL << 1)

struct _ATA_HOST_OPERATIONS;
struct _ATA_HOST_DEVICE_OBJECT;
struct _ATA_PORT_OPERATIONS;

typedef struct _ATA_PORT_DEVICE_OBJECT{
    struct _ATA_HOST_DEVICE_OBJECT* Host;
    struct _ATA_PORT_OPERATIONS*    Operations;
    PVOID                           PortPrivateData;
}ATA_PORT_DEVICE_OBJECT, * PATA_PORT_DEVICE_OBJECT;

typedef struct _ATA_PORT_OPERATIONS{
    LOUSTATUS (*AtaPortDeviceReset)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceStart)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceStop)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceWake)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDeviceSleep)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDevicePowerUp)(PATA_PORT_DEVICE_OBJECT PortDevice);
    LOUSTATUS (*AtaPortDevicePowerDown)(PATA_PORT_DEVICE_OBJECT PortDevice);
}ATA_PORT_OPERATIONS, * PATA_PORT_OPERATIONS;

typedef struct _ATA_HOST_DEVICE_OBJECT{
    PPCI_DEVICE_OBJECT              PDEV;
    struct _ATA_HOST_OPERATIONS*    Operations;
    ULONG                           HostFlags;
    PVOID                           HostPrivateData;
    SIZE                            PortCount;
    PATA_PORT_DEVICE_OBJECT         PortDevices;
}ATA_HOST_DEVICE_OBJECT, * PATA_HOST_DEVICE_OBJECT;

typedef struct _ATA_HOST_OPERATIONS{
    LOUSTATUS (*AtaHostDeviceReset)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceStart)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceStop)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceWake)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDeviceSleep)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDevicePowerUp)(PATA_HOST_DEVICE_OBJECT HostDevice);
    LOUSTATUS (*AtaHostDevicePowerDown)(PATA_HOST_DEVICE_OBJECT HostDevice);
}ATA_HOST_OPERATIONS, * PATA_HOST_OPERATIONS;



#include "Ahci.h"

#endif